### ISSUE TITLE
latex compile of sphinx docs doesn't work on ollie

### ISSUE THREAD

**Issue by dbarbi** [esm-tools/esm_tools#1]
Running Sphinx v1.8.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: [] 0 added, 1 changed, 0 removed
reading sources... [100%] history
/home/ollie/mandresm/esm_tools/docs/history.rst:1: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '../HISTORY.rst'.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/ollie/mandresm/esm_tools/docs/readme.rst: WARNING: document isn't included in any toctree
done
processing esm_tools.tex...index introduction ten_steps installation transitioning esm_master esm_versions faq packages contributing authors history
resolving references...
writing... done
copying images... [100%] ESM-TOOLS_LOGO_RGB_72dpi.jpg
copying TeX support files...
done
build succeeded, 2 warnings.
The LaTeX files are in _build/latex.
Run 'make' in that directory to run these through (pdf)latex
(use `make latexpdf' here to do that automatically).
make[1]: Entering directory `/home/ollie/mandresm/esm_tools/docs/_build/latex'
latexmk -pdf -dvi- -ps-  'esm_tools.tex'
make[1]: latexmk: Command not found
make[1]: *** [esm_tools.pdf] Error 127
make[1]: Leaving directory `/home/ollie/mandresm/esm_tools/docs/_build/latex'
make: *** [latexpdf] Error 2

**Comment by pgierz** [comment]
Looks like something silly...did you clean up the default files made by the cookiecutter? HISTORY.rst is one of those... it needs to be removed from the index.rst for that error to go away 

And latexmk not found is something for Malte to look at...

**Comment by mandresm** [comment]
In Mistral I get the following error when I try to compile the manual:
```
/usr/bin/python: No module named sphinx
make: *** [latexpdf] Error 1
```

So it seems it's missing _sphinx_, I checked for _latexmk_ and it is also missing it.

**Comment by MiguelAndresMartinez** [comment]
> 
> 
> Looks like something silly...did you clean up the default files made by the cookiecutter? HISTORY.rst is one of those... it needs to be removed from the index.rst for that error to go away
> 
> And latexmk not found is something for Malte to look at...
