### ISSUE TITLE
Write namelist in uppercase vs lowercase?

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#10]
Hi all

I'm trying to run OpenIFS AMIP runs with ESM-Tools. 
OpenIFS tries to find namelist chapters named "NAMCTL" or "NAMPAR0" in the namelist, but the f90nml package writes everything lowercase "namctl" or "nampar0". So OpenIFS can not find the namelist chapters and crashes immediately. 

Is there a way we can write namelists in uppercase? 
There seems to be a line of code in the f90nml package that sets lowercase to be the default, but I don't know if we have a flag somewhere that sets "uppercase = True" or something similar. 

Cheers
Joakim

**Comment by pgierz** [comment]
Fortran shouldn't be case sensitive...? Do you have a traceback? Maybe there's just a spelling error.

**Comment by pgierz** [comment]
Looking at the f90nml docs: https://f90nml.readthedocs.io/en/latest/usage.html

There's a attribute of `Namelist` objects that specifies uppercase or lowercase. If you can confirm that OpenIFS has case sensitivity, I can add a section to the "general" section where you can specify upper or lowercase namelists.

**Comment by joakimkjellsson** [comment]
Hi Paul

Yes, I replaced one namelist chapter name by uppercase and that worked. So I know that OpenIFS requires uppercase. If you could add an option for this to esm-tools that would be great!

The reason why it's case sensitive is probably because OpenIFS does everything the hard way. For each namelist chapter to read IFS first does "rewind" to get back to top of namelist, then goes through each line in the namelist and uses "index" to see if the chapter name occurs in the line. Then IFS does "read" for the namelist chapter. I think the "index" function might be case-sensitive. 
Better be nice to IFS and keep everything uppercase... 

Many thanks for the quick response!
/Joakim

**Comment by pgierz** [comment]
... 🤦 this doesn't conform to the fortran standard. Ok, I'll hack something together

**Comment by joakimkjellsson** [comment]
I guess the correct way would be to do: 
REWIND (_namelist_id_)
READ (_namelist_id_, _namelist_chapter_name_)

I don't know why IFS goes about it in such a complicated way... 
But it might be nice to be able to control lowercase vs uppercase in ESM-Tools. Might be some other model that does the same thing. 

Thanks again!
/Joakim

**Comment by pgierz** [comment]
OK, can you try using the branch nml_case of esm_runscripts? You can add a new parameter in the openifs yaml:

```yaml
openifs:
   namelist_case: "uppercase"
``` 

If I understand `f90nml` correctly, this **should** now result in what you want. If you need help with installing esm_runscripts specific branches, I think we had written some documentation for that; but basically just clone that repo, switch branches, and `pip install -e`

**Comment by joakimkjellsson** [comment]
Awesome! That fixed it, Paul! 
IFS now processes namelists properly. 

Thanks again!
Joakim

**Comment by pgierz** [comment]
Cool. Only 2 lines of code. Python is so much easier than the shell version. Closing this and merging...

**Comment by pgierz** [comment]
Cool. Only 2 lines of code. Python is so much easier than the shell version. Closing this and merging...
