### ISSUE TITLE
HIST simulation using ECHAM6.3.05p2-wiso on albedo, errors in forcing files

### ISSUE THREAD

**Issue by QinggangGao** [esm-tools/esm_tools#1015]
Dear developers

I am trying to run a HIST simulation from 1870 to the present using ECHAM6.3.05p2-wiso on albedo, but I meet errors in forcing files. While the main problem seems to be missing aero_coarse_*year*.nc files, there are files in the forcing directory like aero_coarse_1850.nc, which are from the wrong year. In addition, do you maybe have standard runscripts for this kind of task? Below are more detailed descriptions.

**Experiment location**: /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0
**Runscript location**:    /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/scripts/amip_echam6_1m.yaml

**log file**: /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/run_18700101-18700131/log/amip_700_5.0_echam_compute_6177518.log
errors in log file: FATAL ERROR in aero_read_opt: file aero_coarse_1869.nc does not exist

**Warning during job submission**:
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/greenhouse_historical.nc
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/MAC-SP.nc
WARNING: File not found: /albedo/scratch/user/qigao001/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/run_18700101-18700131/forcing/echam/greenhouse_gases.nc
WARNING: File not found: /albedo/scratch/user/qigao001/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/run_18700101-18700131/forcing/echam/MAC-SP.nc

**esm_tools version**: 6.23.3
esm_tools> git log
commit de3611297e36951ebb324ce650f38faab15965fc (HEAD -> release, origin/release, origin/HEAD, origin/484-error-handeling-in-case-of-empty-yaml-block)
Merge: f7fd219e bc258031
Author: Miguel <63242832+mandresm@users.noreply.github.com>
Date:   Wed Aug 2 13:35:03 2023 +0200

    Merge pull request #1012 from esm-tools/fix/resolve_symlinks
    
    fix/resolve_symlinks

**Comment by mandresm** [comment]
Hi Qinggang,

The branch `fix/echam_hist` should solve this problem. I'll merge it to release as soon someone approves the PR.

**Comment by QinggangGao** [comment]
Hi Miguel

Thank you very much for your swift reply. The warning message disappeared but the error message still remains as below.

FATAL ERROR in aero_read_opt: file aero_coarse_1869.nc does not exist

log file: /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/run_18700101-18700131/log/amip_700_5.0_echam_compute_6179064.log

**Comment by mandresm** [comment]
Do you know which files for aero_coarse you need for this type of simulation? Do you know where those files live in Albedo (path)?

**Comment by QinggangGao** [comment]
The Error message is "FATAL ERROR in aero_read_opt: file aero_coarse_1869.nc does not exist" in the log file: /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/run_18700101-18700131/log/amip_700_5.0_echam_compute_6179064.log

But I can find the following files aero_coarse_1849.nc, aero_coarse_1850.nc, aero_coarse_1851.nc, in the forcing directory /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0/run_18700101-18700131/forcing/echam.

All three forcing files point to the same file in Albedo: /albedo/pool/ECHAM6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_coa.nc

So I assume there are two problems: 1) esm_tools does not copy aero_coarse_*.nc files for the correct years (i.e. 1869, 1870, 1871, instead of 1849, 1850, and 1851). 2) I think the aerosols should change during the historical period. Do you know why it is not?

**Comment by mandresm** [comment]
I can very easily make ESM-Tools to copy 1869, 1870, 1871, instead of 1849, 1850, and 1851. The fact that is not configured that way, is because whoever configured the `HIST` scenario considered (probably after reading the ECHAM manual) that those files were what was needed for the type of simulation they were preparing.

That we can easily swap the files to get ECHAM not to complain is an easy business, but that doesn't mean that is scientifically sound (if we load the files that are incorrect). MPIESM scripts do a lot of "magic" in these sense, therefore, my question is: do you know which files are needed for your type of simulation? and if you don't consulting the ECHAM manual is necessary.

@pgierz any clue about what's going on here and why for other people using `HIST` is enough with aero_coarse_1849/1850/1851

**Comment by mandresm** [comment]
Page 56 seems to give a hint about that: https://pure.mpg.de/rest/items/item_1810486_4/component/file_1810485/content

If you want to use the transient aerosols it should be enough with adding the following to your runscript:
```yaml
echam:
    add_forcing_files:
        aerocoarse:  histaerocoarse
```
You can find where the source of that file is defined in line 36 of `configs/components/echam/echam.datasets.yaml`. The definition of the file is there and available to be used, but to "activate it" and being able to copied it you need to include it into the `forcing_files` in the way I wrote above.

If you are using transient aerosols and I'm reading the ECHAM manual correctly, ECHAM will probably complain about `aero_farir_yyyy.nc` files as well. As for the previous file you also have a `histaerofarir` file ready to be used in line 43 of `configs/components/echam/echam.datasets.yaml`.

**Comment by QinggangGao** [comment]
Thank you. I tried the following settings but it does not work as well.

    forcing_sources:
         "histaerocoarse":
             "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_coa.nc":
                 to: 1864
             "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_coa_@YEAR@.nc":
                 from: 1865
                 to: 2000
         "histaerofarir":
             "${forcing_dir}/aero/${resolution}_aeropt_kinne_lw_b16_coa.nc":
                 to: 1864
             "${forcing_dir}/aero/${resolution}_aeropt_kinne_lw_b16_coa_@YEAR@.nc":
                 from: 1865
                 to: 2000
        "histaerofin":
                "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_fin_1865.nc":
                        to: 1864
                "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_fin_@YEAR@.nc":
                        from: 1865
                        to: 2000
    add_forcing_files:
        aerocoarse:  histaerocoarse
        aerofarir:  histaerofarir
        aerofin:  histaerofin
    forcing_in_work:
        aerocoarse: "aero_coarse_@YEAR@.nc"
        aerofarir: "aero_farir_@YEAR@.nc"
        aerofin: "aero_fine_@YEAR@.nc"

From my understanding, 1) it should be enough to use PI files for aerocoarse and aerofarir, and ECHAM6 should know how to link 1849/1850/1851 files to 1869/1870/1871 files, which is not the case for now. 2) For aerofin, there is no error message now, but I would expect that it is annual varying from 1870 to present.

Should I run PI simulation from 1850, where there seems to be no SST/SIC boundary conditions?

**Comment by QinggangGao** [comment]
Update: When I use the following settings, the error message becomes “FATAL ERROR in aero_read_opt: file aero_fine_1869.nc does not exist“. That is, ECHAM can link to 1869/1870/1871 files of aerocoarse and aerofarir. But it can still not point to the right file for aerofin.

    forcing_sources:
        "piaerocoarse": "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_coa.nc"
        "piaerofarir": "${forcing_dir}/aero/${resolution}_aeropt_kinne_lw_b16_coa.nc"
        "histaerofin":
                "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_fin_1865.nc":
                        to: 1864
                "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_fin_@YEAR@.nc":
                        from: 1865
                        to: 2000
    add_forcing_files:
        aerocoarse:  piaerocoarse
        aerofarir:  piaerofarir
        aerofin:  histaerofin
    forcing_in_work:
        aerocoarse_1849: "aero_coarse_1849.nc"
        aerocoarse_1850: "aero_coarse_1850.nc"
        aerocoarse_1851: "aero_coarse_1851.nc"
        aerofarir_1849: "aero_farir_1849.nc"
        aerofarir_1850: "aero_farir_1850.nc"
        aerofarir_1851: "aero_farir_1851.nc"
        aerofin_1849: "aero_fine_1849.nc"
        aerofin_1850: "aero_fine_1850.nc"
        aerofin_1851: "aero_fine_1851.nc"
        aerocoarse: "aero_coarse_@YEAR@.nc"
        aerofarir: "aero_farir_@YEAR@.nc"
        aerofin: "aero_fine_@YEAR@.nc"

**Comment by mandresm** [comment]
You only need:

```yaml
echam:
    add_forcing_files:
        aerocoarse:  histaerocoarse
```

The rest is loaded already from configs/components/echam/echam.datasets.yaml (for more info about ESM-Tools, and how it reads and puts together all the information and copies the files read the YAML chapter in the documentation: https://esm-tools.readthedocs.io/en/latest/yaml.html).

If that line alone does not solve the error, let me know. In that case I would also be interested in what's the content of the `run_<DATE>/work` folder.

**Comment by QinggangGao** [comment]
Hi, I tried the above instruction by only add that line. It still led to the error message: "FATAL ERROR in aero_read_opt: file aero_coarse_1869.nc does not exist".

Experiment is installed here: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_701_5.0`
log file is here: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_701_5.0/run_18700101-18700131/log/amip_701_5.0_echam_compute_6183806.log`
`run_<DATE>/work` folder is here: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_701_5.0/run_18700101-18700131/work`

In the `run_<DATE>/work` folder, there are files aero_coarse/farir/fine_1849/1850/1851.nc, but no files for the simulation year 1870.

I tried the following settings and it worked. But the fine aerosol always point to the same file: `/albedo/work/projects/p_pool_echam6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_fin_1865.nc`.

Settings:

>     forcing_sources:
>         "piaerocoarse": "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_coa.nc"
>         "piaerofarir": "${forcing_dir}/aero/${resolution}_aeropt_kinne_lw_b16_coa.nc"
>         "piaerofin": "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_fin_1865.nc"
>     add_forcing_files:
>         aerocoarse:  piaerocoarse
>         aerofarir:  piaerofarir
>         aerofin:  piaerofin
>     forcing_in_work:
>         aerocoarse_1849: "aero_coarse_1849.nc"
>         aerocoarse_1850: "aero_coarse_1850.nc"
>         aerocoarse_1851: "aero_coarse_1851.nc"
>         aerofarir_1849: "aero_farir_1849.nc"
>         aerofarir_1850: "aero_farir_1850.nc"
>         aerofarir_1851: "aero_farir_1851.nc"
>         aerofin_1849: "aero_fine_1849.nc"
>         aerofin_1850: "aero_fine_1850.nc"
>         aerofin_1851: "aero_fine_1851.nc"
>         aerocoarse: "aero_coarse_@YEAR@.nc"
>         aerofarir: "aero_farir_@YEAR@.nc"
>         aerofin: "aero_fine_@YEAR@.nc"

Experiment location: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/amip_700_5.0`

**Comment by mandresm** [comment]
Looking at it right now...

**Comment by mandresm** [comment]
ESM-Tools is tryinbg to look for this files, but the files are missing in the pool. The ouput of ESM-Tools when you run the runscript shows that:

```
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_coa_1870.nc
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_coa_1869.nc
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_coa_1871.nc        
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_coa_1868.nc
WARNING: File not found: /albedo/pool/ECHAM6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_coa_1872.nc
```

I will look on how the pool looks into Levante, and copy them if necessary.

**Comment by QinggangGao** [comment]
Yes, thank you in advance.

**Comment by mandresm** [comment]
in `/pool/data/ECHAM6/input/r0008/T63/aero` in `Levante` there is only:
```
sulfate  T63_aeropt_kinne_lw_b16_coa.nc  T63_aeropt_kinne_sw_b14_coa.nc  T63_aeropt_kinne_sw_b14_fin_1865.nc
```

and I don't see anything in the documentation of ECHAM that suggests there should be one file per each year. @pgierz, @pengyangsong and @l975421700, do you know what would be de desire behavior here? Which file should we link copy to be remaned as `aero_coarse_1869.nc`?

**Comment by pgierz** [comment]
I am not 100% sure about this, but optical aerosols might be in the same general category as ozone and need an extra year on each end.

**Comment by pgierz** [comment]
Ignore my previous comment. I'll post a link to the responsible Fortran code later today.

**Comment by QinggangGao** [comment]
Thank you very much for your time. Please note that I can indeed run the simulation using the following settings. As ECHAM6 manual indicates that we can use PI coarse and farir aerosols (i.e. piaerocoarse, piaerofarir, natural origin) for historical simulation, I think the main issue is how to use historical fine aerosols (anthropogenic origin, rather than piaerofin) for historical simulation. I will try to check whether it exists on albedo.

> Settings:
> 
> > ```
> > forcing_sources:
> >     "piaerocoarse": "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_coa.nc"
> >     "piaerofarir": "${forcing_dir}/aero/${resolution}_aeropt_kinne_lw_b16_coa.nc"
> >     "piaerofin": "${forcing_dir}/aero/${resolution}_aeropt_kinne_sw_b14_fin_1865.nc"
> > add_forcing_files:
> >     aerocoarse:  piaerocoarse
> >     aerofarir:  piaerofarir
> >     aerofin:  piaerofin
> > forcing_in_work:
> >     aerocoarse_1849: "aero_coarse_1849.nc"
> >     aerocoarse_1850: "aero_coarse_1850.nc"
> >     aerocoarse_1851: "aero_coarse_1851.nc"
> >     aerofarir_1849: "aero_farir_1849.nc"
> >     aerofarir_1850: "aero_farir_1850.nc"
> >     aerofarir_1851: "aero_farir_1851.nc"
> >     aerofin_1849: "aero_fine_1849.nc"
> >     aerofin_1850: "aero_fine_1850.nc"
> >     aerofin_1851: "aero_fine_1851.nc"
> >     aerocoarse: "aero_coarse_@YEAR@.nc"
> >     aerofarir: "aero_farir_@YEAR@.nc"
> >     aerofin: "aero_fine_@YEAR@.nc"
> > ```

**Comment by QinggangGao** [comment]
> I tried the following settings and it worked. But the fine aerosol always point to the same file: `/albedo/work/projects/p_pool_echam6/input/r0008/T63/aero/T63_aeropt_kinne_sw_b14_fin_1865.nc`.

In this folder `/albedo/work/projects/p_pool_echam6/input/r0008/T63/aero`, there is indeed only one fine aerosol file `T63_aeropt_kinne_sw_b14_fin_1865.nc`.

But I can find fine aerosol files for each year from 1849 to 2005 here `/albedo/work/projects/p_pool_echam6/T63/aero` or from 1865 to 2000 here `/albedo/work/projects/p_pool_echam6/T63/aero2`.

Would it be right to let esm_tools point to the latter folders?

**Comment by QinggangGao** [comment]
Hi, I can run the simulation now even without setting `aerocoarse:  histaerocoarse`. I changed the namelist.echam according to the one provided by esm_tools for HIST, so that it does not show warning message for coarse aerosol files.

The only problem left is that esm_tools still do not link the right fine aerosol files for the right years.

Experiment location: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/test0`
runscripts: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/test0/scripts/amip_echam6_1m.yaml`
Forcing file folder: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/test0/run_18700101-18700131/forcing/echam`

As you can see in the forcing folder, it points to three fine aerosol files at year 1849/1850/1851. Can we change this behaviour to use fine aerosol files in the folder `/albedo/work/projects/p_pool_echam6/T63/aero2` for each year?

**Comment by mandresm** [comment]
It is possible, I cannot tell however whether those are the correct files you want to use.

To achieve that you simply need to change the source of those files in your runsctrip, for example for `aero2`:
```yaml
echam:
    forcing_sources:
        histaerocoarse: ${pool_dir}/${resolution}/aero2/${resolution}_aeropt_kinne_sw_b14_fin_@YEAR@.nc
    add_forcing_files:
        aerocoarse: histaerocoarse
```

However, I have no idea what that means in terms of physics, and we cannot take responsibility for that. I you, or some other ECHAM expert, are sure that those are the files needed for a very specific type of scenario, and that's well documented in the ECHAM manual then we can implement it in ESM-Tools. Otherwise, we cannot risk to implement a default into the release that might be using the wrong files.

**Comment by mandresm** [comment]
> The only problem left is that esm_tools still do not link the right fine aerosol files for the right years.

This might not be an error or a problem. It might depend on the simulation you are running whether you want to use one file or another. From the ECHAM's manual:

```
Optical properties of coarse mode
aerosols in the solar spectral
range. Since these are mostly
of natural origin, climatological
boundary conditions are sufficient
for historic times.
```

It seems to be suggesting that you always use `aero/{RES} aeroptkinne sw b14 coa.nc`

**Comment by QinggangGao** [comment]
Thank you for the remind. I am not sure at all. Do you maybe know whoever has run a HIST simulation using either ECHAM or AWI-ESM?

**Comment by mandresm** [comment]
Yes, I think @pgierz will be looking into that soon to give you a clearer answer on that

**Comment by PengyangSong** [comment]
It depends on how you set "iaero" in the namelist.echam
We usually set to 8 and 9, in your case probably should be 3.
In echam source code "stepon.F90" search "iaero" you will understand.

**Comment by QinggangGao** [comment]
Thank you for the insight.

From the ECHAM6 user guide I can see:
iaero = 3: aerosol climatology compiled by S. Kinne
iaero = 8: anthropogenic aerosols modelled in simple plumes (see sec- tion A.16) together with natural back- ground aerosols of 1850 according to S. Kinne and volcanic aerosols after G. Stenchikov.

A direct setting of iaero = 3 will lead to error message `FATAL ERROR in aero_read_opt: file aero_coarse_1869.nc does not exist`. From stepon.f90, if iaero=8 or 9, l_aero_kinne_1850 = .TRUE.. Does it means it will always use the value for 1850?

If I understand correctly, I should use historical fine aerosol varying from 1870 to 2000, as it is mainly of anthropogenic origin. Then the question is whether the files in the folder `/albedo/work/projects/p_pool_echam6/T63/aero2` are right ones to use.

**Comment by PengyangSong** [comment]
Yes, note the difference between "prev_radiation_date" and "prev_radiation_date_1850" in the code.
I didn't use historical fine aerosol so I haven't checked the related files.

**Comment by mandresm** [comment]
Thanks @PengyangSong!

**Comment by mandresm** [comment]
@christian-stepanek, @PengyangSong, is it maybe time to ask Kalle Wieners (the ECHAM expert)? If it turns out that aero2 are the correct files for aerosol climatology, we could always add an option into ESM-Tools that set's the correct variables in the namelists and copy the correct files for historical aerosols.

**Comment by chrisdane** [comment]
`year_weight` from `MAC-SP.nc` scales the monthly climatology aerosols as detailed in appendix A.16 of the echam docu (the `E` term in eq. A.47). The routine `set_time_weight` applies this annual scaling in `mo_simple-plumes.f90`. This is what we normally did, as Pengyang said (i.e. `iaero = 8`).

I don't know where the files in `/albedo/work/projects/p_pool_echam6/T63/aero2` come from. If you want to dig deeper there, I suggest to contact sebastian.rast@mpimet.mpg.de and stefan.kinne@zmaw.de. 

Cheers

**Comment by QinggangGao** [comment]
Thank you for the information.

It might be a stupid question: I understand it is useful to use simple plume assumptions for future scenarios, but why is it also used for historical periods, rather than historical observations? 

I assume it might actually be very similar and I do not mind which one to use. It is just good for me to know and be consistent with other simulations. Also, this paper should be cited if we use simple plume assumptions right? `First forcing estimates from the future CMIP6 scenarios of anthropogenic aerosol optical properties and an associated Twomey effect  (https://gmd.copernicus.org/articles/12/989/2019/)`.

**Comment by chrisdane** [comment]
Your question is not stupid at all! If you use `iaero=8` (which you should; do you want to use another value?) and want to cite something, please use (from appendix A.16 from the echam docu)
> Stevens, B. et al. (2017): MACv2–SP: a parametrization of anthropogenic aerosol optical
properties and an associated Twomey effect for use in CMIP6 . Geosci. Model Dev., 10,
433–452.

**Comment by QinggangGao** [comment]
Thank you. I think this is the solution I am looking for. Thanks Miguel for the help. This issue can be closed for me.
