### ISSUE TITLE
specific transient forcings for AWI-CM3

### ISSUE THREAD

**Issue by jian-shi72** [esm-tools/esm_tools#1029]
**Is your feature request related to a problem? Please describe.**
When I attempt to do a accelerated orbital transient experiment using AWI-CM3, I didn't find the switch that uses a list of orbital parameters/GHGs in a table (like "use_transient_forcing = true" for AWI-ESM2). Is there such a function for AWI-CM3 (especially for the orbit)?

**Describe the solution you'd like**
Just like the solution in AWI-ESM2:
use_transient_forcing: True
transient_forcing_table: /some/path/to/a/table

**Comment by nwieters** [comment]
Hi @jian-shi72,

I think this is a direct question to a specific model configuration. Therefore, I will convert this into a discussion for now.
We can change it back to an issue later, should it still be necessary.
