### ISSUE TITLE
What to do when OASIS restart files are not found

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#1049]
Good evening

I updated ESM-Tools recently and found that the behaviour when OASIS restart files are not found has changed. In the past, ESM-Tools just threw a warning but now it actually refuses to start. I think I like the new behaviour better, but it has one annoying feature: The OASIS files now have to be named `<restart_file>_<prev_start_date>-<prev_end_date>`, e.g. `sstocean_18400101-18401231` if we are starting in 1 Jan 1841. 

Quite often, I save restart files without the time stamp in a separate, shared folder, e.g. just `sstocean` and use them for several branch off runs. Also, FOCI-OpenIFS has one file `rnrunoff` which is always zero, and thus never gets a time stamp, making branch offs with FOCI-OpenIFS impossible. 

So I have a suggestion: ESM-Tools can first search for the proper restart file, and if that is not found it searches for the restart file without time stamp. If that's not found either, then the error is triggered. 

For example, one would add this to `src/esm_runscripts/oasis.py`:
```python
if len(glob_restart_file) == 1:
                         restart_file = os.path.basename(glob_restart_file[0])
                     elif len(glob_restart_file) == 0:
                        print( "Restart file missing: %s" % (glob_search_file,) ) 
                               
                        # Joakim: 
                        # If the file <restart_file>_<prev_start_date>_<prev_enddate> does not exist
                        # then search for <restart_file>
                        glob_search_file_generic = ( f"{config['ini_restart_dir']}{restart_file}" )
                        glob_restart_file_generic = glob.glob(glob_search_file_generic)
                        glob_restart_file_generic.sort()
                        if len(glob_restart_file_generic) == 1:
                            restart_file = os.path.basename(glob_restart_file_generic[0])
                        else:
                            print( "Did not find %s either" % (glob_search_file_generic,) )
                            
                            user_error(
                                "Restart file missing",
                                f"No OASIS restart file for ``{restart_file}`` found "
                                f"matching the pattern ``{glob_search_file}``"
                            )
                     else:
                         if not gconfig["isinteractive"]:
```

How do the rest of you feel about this? We could perhaps make it so that ESM-Tools actually stops and requests the user to explicitly give the thumbs up (or at least press "y") to use `<restart_file>`, just so that the warning is super clear. 

Cheers
Joakim

**Comment by mandresm** [comment]
Hi @joakimkjellsson, I think that the functionality you are asking for was implemented as a fix, right after we introduced the new logic of Oasis restart files. This was the PR:

https://github.com/esm-tools/esm_tools/pull/994/files#diff-f1543c1113264714a5adf1e6959151c790f77c7685ad5d6b6a361bb2d4eee348L475-R482

Please, see if your branch contains the commit id [24fcbdf](https://github.com/esm-tools/esm_tools/pull/994/commits/24fcbdf58f27026d8f48fa91d8ec19928916d3e2)

If it doesn't, you're problem might be solved by simply merging the latest `release` into your branch.

Apologies for the inconvenience...

**Comment by mandresm** [comment]
Hi Joakim again!

I've just seen that your branch contains the last changes I was referring to. I've also seen #1044.

I think I now fully understand the problem. I am suggesting another edition to Sebastian's suggestion.

**Comment by mandresm** [comment]
Closes #1049

**Comment by mandresm** [comment]
Can I close this issue now?

**Comment by mandresm** [comment]
I'm closing this as it has been solved.
