### ISSUE TITLE
New heterogeneous sbatch for newer versions of SLURM

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#1050]
@tsemmler05 wrote in an email to me, @JanStreffing and @nwieters:

Hi Jan, Miguel, and Nadine!

Not sure who to address and also I can't find the github issue about the optimization of AWI-CM on ECMWF-atos.

According to ECMWF support, I should not define nodes manually to avoid that omp_num_threads not equal 1 is even slower than omp_num_threads = 1 (see their explanation at the end of the email).

I will try to implement these changes into the esm runscripts.

You can find my edited run scripts here:

/scratch/duts/runtime/awicm3-frontiers-xios/OMP1/scripts/OMP1_compute_20000101-20000101.run and OMP2_compute_20000101-20000101.run

Regards,

Tido.

## Tickets from ECMWF

Dear [Tido Semmler](https://jira.ecmwf.int/secure/ViewProfile.jspa?name=duts) ,

I believe the issue you are having is related to the cpu binding not being done correctly.  I see that you are basically trying to do by hand what Slurm is capable of doing natively. As [Daniel Varela Santoalla](https://jira.ecmwf.int/secure/ViewProfile.jspa?name=usv) was suggesting, I believe there may be a better and cleaner way to run your coupled model, using Slurm's heterogeneous step feature. This way, you would rely on Slurm to take care of the different geometries for each of the 4 executables, and ensure proper cpu binding as well.

Here is a self-contained example that you can run to see what is happening and how the cpu binding for each task/thread is properly done, so there is no sharing of cpus amongst them that could impact their performance. You can save it int your account and submit it with sbatch to see the result:
```
    #!/bin/bash
    #SBATCH -q np
    #SBATCH -N 8
    #SBATCH --hint=nomultithread
    #SBATCH -o test-coupled-%j.out
    #SBATCH -e test-coupled-%j.out

    # Execution layout
    mpi_tasks_fesom=256
    omp_threads_fesom=1
    mpi_tasks_oifs=256
    omp_threads_oifs=2
    mpi_tasks_rnfmap=1
    omp_threads_rnfmap=128
    mpi_tasks_xios=1
    omp_threads_xios=32

    module load hpcx-openmpi

    # Fetch and build affinity checker xthi
    # Tweak it slightly to be able to simulate different executables
    [[ ! -e xthi.c ]] && wget https://docs.nersc.gov/jobs/affinity/xthi.c
    sed -i -e "s/Hello from/%s/" -e "s/   rank, thread/   argv[0], rank, thread/" xthi.c
    mpicc -fopenmp -o xthi xthi.c

    # Simulate different executables
    for i in fesom oifs rnfmap xios; do
        ln -sf xthi $i
    done

    # Ensure OpenMP correct pinning
    export OMP_PLACES=threads

    # Avoid PMI hangs with heterogeneous jobs
    export SLURM_MPI_TYPE=none

    # Use srun in heterogeneous steps mode.
    # Each executable will have a different layout, minimum allocation is one node for each.
    # See https://slurm.schedmd.com/heterogeneous_jobs.html#het_steps
    srun -n $mpi_tasks_fesom -c $omp_threads_fesom ./fesom : -n $mpi_tasks_oifs -c $omp_threads_oifs ./oifs : -n $mpi_tasks_rnfmap  -c $omp_threads_rnfmap ./rnfmap : -n $mpi_tasks_xios -c $omp_threads_xios ./xios | sort -k 3,3n -k 5,5n 
```

I am here simulating your 4-way coupled run with a special program that will tell you which rank and thread it is, as well as the host and cpu number where it is running. I tried to maintain your geometry as much as possible, except I reduced fesom's tasks to just a couple of nodes to save some resources. In this example, you would get 2 nodes for fesom (256x1/128), 4 nodes for oifs (256x2/128), 1 node for rnfmap (1x128/128) and 1 node for xios (1x32/128, a portion of the node cpus would not be used), so 8 nodes in total. Note as well the --hint=nomultithread in the header to make sure only physical cores are used (128 per node). As you can see each one of them would be running with a different task/thread layout according to their needs. There is no need to undefine SLURM variables, create your own hostlists, multi-prog file, tasksets, wrappers, etc. with this technique.

I would suggest you run that job to see what you get, and then if it convinces you try to use it as a base for your real run replacing the dummy executables by the real ones and with the right node cound and layout for fesom.

Regards,

Xavi

-----
Daniel Varela Santoalla
1 hour ago

Hi [Tido Semmler](https://jira.ecmwf.int/secure/ViewProfile.jspa?name=duts)

[Xavier Abellan](https://jira.ecmwf.int/secure/ViewProfile.jspa?name=usxa) and me have been having a look at this and there is another way of submitting heterogeneous jobs without the hostlist, just letting slurm do the arrangements and perhaps maintaining the CPU "pinning" that may give the best results. Otherwise the risk is end up using multiple threads in the same CPU which could indeed reduce performance.

https://slurm.schedmd.com/heterogeneous_jobs.html

We wanted to make some tests to confirm this though.

Kind regards
Daniel

**Comment by mandresm** [comment]
Hi @tsemmler05,

To me this seems a new type of syntax to run heterogeneous slurm jobs. We have support for one of the oldest syntaxes that avoids the use of `taskset` (if you select in your runscript `computer.taskset: false` then you'll get a different `.run` file without taskset and something that looks more similar to what they are proposing) but that never really worked well with the systems we tried (it was not a problem with ESM-Tools but a problem that slurm in Levante, Albedo, Juelich, was not really well configured for using this feature well).

The good news are that this new syntax ECMWF is proposing is even cleaner and very easy to set up. Is it okay if I work on it tomorrow? @nwieters is busy with some developments in ESM-Tools and @JanStreffing is defending his thesis soon.

**Comment by tsemmler05** [comment]
Hi @mandresm!

Sure; actually yesterday evening I already saw this computer.taskset choice and tried it. But indeed some further work is needed to get it right. I am working on branch ecmwf.atos (haven't pushed my changes that I tried out yesterday since they didn't work properly). So, indeed, your help tomorrow would be appreciated.

**Comment by tsemmler05** [comment]
At least, I can confirm that it is worth implementing this for ecmwf.atos into the esm tools; after manually editing the .run script I noticed that my job ran clearly faster on ECMWF atos.

**Comment by JanStreffing** [comment]
Hello @tsemmler05, could you make a check run with taskset=false so we can see our grammar differs from Xavis test script?

In the past we had a lot more trouble with slrum het jobs that with tasksets, which is why we kept this feature around. But if the ECMWF admins are willing to support, we can give it another shot.

**Comment by tsemmler05** [comment]
This is the job script that comes out with taskset=false:

/scratch/duts/runtime/awicm3-frontiers-xios/OMPtest4/run_20000101-20000101/scripts/OMPtest4_compute_20000101-20000101.run

If one compares this with the manually edited script

/scratch/duts/runtime/awicm3-frontiers-xios/OMP2/run_20000101-20000101/scripts/OMP2_compute_20000101-20000101.run

one sees that the SBATCH header is wrong in the OMPtest4, and that the srun commands are different. In the automatically generated run script in OMPtest4, there is some redundant information; only ntasks and OMP_NUM_THREADS (-n and -c) need to be given. There are also some other differences in the flags.

**Comment by tsemmler05** [comment]
The manually edited OMP2 script is the one that runs efficiently.

**Comment by mandresm** [comment]
Hi @tsemmler05, thanks a lot for your tests! I'll take over tomorrow!

**Comment by mandresm** [comment]
Hi @tsemmler05,

I have pushed to the `ecmwf-atos` branch a fix that will get rid of the `#SBATCH hetjob` flags, that were correct for other systems with slurm, but apparently for this system they are not needed.

You'll then get something that looks very similar to what they gave you, but with some extra flags in the `srun` command that should do no harm:

```
time srun -l --kill-on-bad-exit=1 --cpu_bind=none \
--nodes=1 --ntasks=128 --ntasks-per-node=128 --cpus-per-task=1 --export=ALL,OMP_NUM_THREADS=1 ./fesom \
: --nodes=2 --ntasks=128 --ntasks-per-node=64 --cpus-per-task=2 --export=ALL,OMP_NUM_THREADS=2 ./oifs -v ecmwf -e awi3 \
: --nodes=1 --ntasks=1 --ntasks-per-node=1 --cpus-per-task=128 --export=ALL,OMP_NUM_THREADS=128 ./rnfma \
: --nodes=1 --ntasks=4 --ntasks-per-node=4 --cpus-per-task=32 --export=ALL,OMP_NUM_THREADS=32 ./xios.x  2>&1 &
```

`--ntasks` is the same as `-n`, `--cpus-per-task` the same as `-c`, `--ntasks-per-node` won't harm as it just specifies the maximum number of tasks per node (see the line of OpenIFS, you'll be asking for 128 MPI tasks in total, but limiting the number of tasks per node to 64 to leave room for 2 OpenMP threads without needing to multithread). I think the `--export` shouldn't harm either and the same goes for `--cpu_bind=none` which I believe is the default if you don't deifne it.

Please, let me know if with these modifications it starts to be fast again for you.

**Comment by mandresm** [comment]
Hi @tsemmler05, can we close this issue now?
