### ISSUE TITLE
installation docu confusing and out of date?

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#1054]
**Request/contribution description**
Installation of esm_tools not clear on https://esm-tools.readthedocs.io/en/latest/installation.html.

**Suggested chapter/section in the documents**
I think points 1 to 5 from lower half of the current page (that part apparently does not have a proper section identifier) should come right at the top.
From these, I also think points 1-3 are not needed? Point 1 may be needed, but for installation its not necessary to add it to bashrc or whatever. I do not have it in my .bashrc and using latest `esm_runscripts` and `esm_master` works fine. I suggest:
1. git clone
2. the locale stuff just in current terminal (if really needed)
3. ./install.sh
4. check if it works: `esm_tools --version`   
If possible, please try to include the `before you continue` in these steps.

Thanks for consideration and cheers,
Chris

**Comment by mandresm** [comment]
If you are referring to this section https://esm-tools.readthedocs.io/en/latest/installation.html#installing, points 1-3 are needed for most of the systems and are a good safety measure to prevent against all that can go wrong in setting up the python environment in HPCs. You might not have them in your `.bashrc` but on your `.bash_profile`. If you still don't have them anywhere, problems will probably come later on, when you try to run and you have installed all the tools in python 3.6 (or whatever deprecated version of python the system is giving you by default) but you are loading for the compute nodes 3.9 or whatever is the default defined for that machine in the `configs/machines/<your_machine>`. The only thing that we might be able to remove in the future is `LC_ALL` and `LANG` variables, but not all python versions will be happy with that, specially the old ones.

**Comment by chrisdane** [comment]
Ah ok now I understand the reason for the confusion: there are two top-level sections: [Installation](https://esm-tools.readthedocs.io/en/latest/installation.html) and [ESM Tools](https://esm-tools.readthedocs.io/en/latest/installation.html#installing). My initial post refers to the 1st, you to the 2nd.

Then I suggest to combine those two for clarity.

Thanks!

**Comment by nwieters** [comment]
Hi,
I started to work on the documentation related to this issue. It is still wip. But you can have a look in the PR #1087.
Feedback is welcome. Thank you.
