### ISSUE TITLE
ECHAM6 HIST simulation at year 2014: Missing ozone forcing file for 2015 

### ISSUE THREAD

**Issue by QinggangGao** [esm-tools/esm_tools#1060]
Dear team

I am running a HIST simulation using ECHAM6 from 1870 to 2014, which failed in the last year 2014 because of a missing ozone forcing file for 2015. Do you know why the ozone information for 2015 is required for the year 2014, and how shall I avoid it? Below are descriptions of the error.

esm_tools version: 6.23.3
echam6 version: 6.3.05p2-wiso
Experiment folder: /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/hist_700_5.0
log file: /albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/hist_700_5.0/run_20140101-20140131/log/hist_700_5.0_echam_compute_6639873.log
Error message: FATAL ERROR in read_o3clim_4: run terminated.

Regards, Qinggang

**Comment by nwieters** [comment]
Dear Qinggang,
it seems that I do not have permission to enter your experiment folder. Can you please give access to it, then I will have a look into your experiment log files.
Thank you.

**Comment by QinggangGao** [comment]
Hi Nadine

Thank you. It should be accessible now. Sorry for that.

Regards

**Comment by chrisdane** [comment]
fyi, echam needs ozon files from year+1 for temporal interpolation. for cmip6, we used the 2015 file from a ssp scenario for the last historical year 2014 and the 2099 file for year 2100 of a ssp scenario run. these cases are covered here:
https://github.com/esm-tools/esm_tools/blob/f62b40f2aa205f4dbaa1a67b17d97897240ba672/configs/components/echam/echam.datasets.yaml#L112-L123
So in your runscript/esm_tools, check the `scenario` and corresponding path.

**Comment by QinggangGao** [comment]
Hi Christian

Thank you. I found it in runscript/esm_tools. May I ask, how can I tell ECHAM6 which scenario to choose (e.g. ssp262 or ssp585)? Now I set scenario: "HIST".

Regards, Qinggang

**Comment by chrisdane** [comment]
make a check run (`esm_runscripts ... -c`) for the year 2014 and search the `finished_config` for these entries:
```
echam:
    forcing_sources:
        ...
        ozone_year_2014: /pool/data/ECHAM6/input/r0007/T63/ozone/T63_ozone_historical_2014.nc
        ozone_year_2015: /pool/data/ECHAM6/input/r0008/T63/ozone/T63_ozone_ssp370_2015.nc
        ...
```
if those files all exist (and hence are in `work`), you are good to go

**Comment by nwieters** [comment]
> Hi Christian
> 
> Thank you. I found it in runscript/esm_tools. May I ask, how can I tell ECHAM6 which scenario to choose (e.g. ssp262 or ssp585)? Now I set scenario: "HIST".
> 
> Regards, Qinggang

If you are running a historical simulation, I think by setting the scenario in line 118 in @chrisdane example:
E.g. (change ssp126 to another scenario of your choice)
```
"ozone_hist_scenario": 
         "${forcing_dir}/ozone/${resolution}_ozone_historical_1850.nc": 
                 to: 1850 
         "${forcing_dir}/ozone/${resolution}_ozone_historical_@YEAR@.nc": 
                 from: 1851 
                 to: 2014 
         scenario: ssp126
         "${forcing_dir}/ozone/${resolution}_ozone_${scenario}_@YEAR@.nc": 
                 from: 2015 
                 to: 2099 
         "${forcing_dir}/ozone/${resolution}_ozone_${scenario}_2099.nc": 
                 from: 2100 
```

**Comment by nwieters** [comment]
Dear Qinggang,
is the solution suggested by @chrisdane working for you?
If not, please let me know, then I will have a look. 

But I think I still need permission for the folder 
/albedo/scratch/user/qigao001/

Thank you.

**Comment by QinggangGao** [comment]
Hi Nadine

I tried to set "scenario: ssp370" in line 118 as suggested by Christian, but I got the following error message during a check run:

Traceback (most recent call last):
  File "/albedo/home/qigao001/.local/bin/esm_runscripts", line 8, in <module>
    sys.exit(main())
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/cli.py", line 285, in main
    Setup()
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/albedo/work/user/qigao001/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/filelists.py", line 1325, in assemble
    config = replace_year_placeholder(config)
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/filelists.py", line 605, in replace_year_placeholder
    ] = find_valid_year(
  File "/albedo/work/user/qigao001/esm_tools/src/esm_runscripts/filelists.py", line 504, in find_valid_year
    from_info = float(config[entry].get("from", min_val))
AttributeError: 'str' object has no attribute 'get'

**Comment by QinggangGao** [comment]
Hi, when I replace ${scenario} as ssp370, there is no warning message. I will let you know whether it works soon.

**Comment by nwieters** [comment]
Dear Qinggang,
setting this via scenario variable also crashes for me with the same error. 
Hard-coding the scenario as you did works for me (at leat in a check run with -c)

I will try to resolve the error when using the variable. Probably next week.
Let me know if this solution is sufficient for you for now.

**Comment by QinggangGao** [comment]
Hi Nadine

Thank you. Hard-coding the scenario works for me. This solution is sufficient for me now.

Regards, Qinggang

**Comment by mandresm** [comment]
@chrisdane, thanks for your help!

@l975421700, in which file have you substituted `${scenario}` with `ssp370`?

**Comment by QinggangGao** [comment]
Hi Miguel. I substituted ${scenario} with ssp370 as below in the file Christian mentioned: esm_tools/configs/components/echam/echam.datasets.yaml.

 ```
"ozone_hist_scenario": 
         "${forcing_dir}/ozone/${resolution}_ozone_historical_1850.nc": 
                 to: 1850 
         "${forcing_dir}/ozone/${resolution}_ozone_historical_@YEAR@.nc": 
                 from: 1851 
                 to: 2014 
         # scenario: ssp126, ssp119, ssp245, ssp370, ssp585 
         "${forcing_dir}/ozone/${resolution}_ozone_ssp370_@YEAR@.nc": 
                 from: 2015 
                 to: 2099 
         "${forcing_dir}/ozone/${resolution}_ozone_ssp370_2099.nc": 
                 from: 2100 
```

**Comment by mandresm** [comment]
I see. Maybe this is kind of obvious, and you've already tried, but have you tried changing the `scenario` variable in your yaml runscript to `ssp370` both for `echam` and `jsbach` sections?

**Comment by QinggangGao** [comment]
Hi. No, because I set scenario as "HIST" in echam section. I thought that if I change scenario to ssp370, some other forcing files might change unexpectedly.

**Comment by mandresm** [comment]
That's a good point, better be on the safe side. We will look at how to fix this next week, so that the next person doesn't have the same problem again.

**Comment by nwieters** [comment]
As far as I understood it, the overall scenario should stay HIST but only in this 'ozone_hist_scenario' forcing_sources/choose block, scenario needs to be changed temporarily to ssp370. My example above
```
"ozone_hist_scenario": 
         "${forcing_dir}/ozone/${resolution}_ozone_historical_1850.nc": 
                 to: 1850 
         "${forcing_dir}/ozone/${resolution}_ozone_historical_@YEAR@.nc": 
                 from: 1851 
                 to: 2014 
         scenario: ssp126
         "${forcing_dir}/ozone/${resolution}_ozone_${scenario}_@YEAR@.nc": 
                 from: 2015 
                 to: 2099 
         "${forcing_dir}/ozone/${resolution}_ozone_${scenario}_2099.nc": 
                 from: 2100
```
gives an syntax error.
But it works the same way @l975421700 tried it.
I will have a look on how to make the syntax work with a scenario variable within the choose block.

**Comment by mandresm** [comment]
Hi @l975421700, with the last push to release this problem is now fixed without the need of modifying anything in your runscript or in the config files.
