### ISSUE TITLE
ERA5-nudged ECHAM6 simulation: Nudging data file not found.

### ISSUE THREAD

**Issue by QinggangGao** [esm-tools/esm_tools#1061]
Dear team

I plan to run an ERA5-nudged ECHAM6 simulation on albedo. I found an example runscript in the esm_tools repository and started from here: esm_tools/runscripts/echam/echam-nudging-ollie-restart-monthly.yaml.

There are some settings that point to a directory on ollie (/work/ollie/paleodyn/nudging/ERA5), which I cannot find on albedo. Do you know where this folder is on albedo?

echam:
    forcing_sources:
        era5_atm: "/work/ollie/paleodyn/nudging/ERA5/atmos/T63/era5${echam.res}${echam.levels}_${echam.current_date!syear}${echam.current_date!smonth}.nc"        
        sst: "/work/ollie/paleodyn/nudging/ERA5/sea/T63/T63_era5sst_@YEAR@.nc"    
        sic: "/work/ollie/paleodyn/nudging/ERA5/sea/T63/T63_era5sic_@YEAR@.nc"

Regards, Qinggang

**Comment by QinggangGao** [comment]
Hi, I found out that the folder might be here: /albedo/work/projects/paleo_work/paleodyn_from_work_ollie_projects/paleodyn/nudging/ERA5/sea/T63. But I do not have access to the folder /albedo/work/projects/paleo_work. Could I apply for the permission?

**Comment by nwieters** [comment]
Dear Qinggang,
in order to get permission to the paleo_work project, you need to request this over the AWI cloud service.
This can't be done through esm-tools.

**Comment by QinggangGao** [comment]
Thank you. I cannot find how to apply for access on AWI cloud service, so I send email to helpdesk@awi.de.

**Comment by QinggangGao** [comment]
The permission can be applied on https://cloud.awi.de/. Thank you.
