### ISSUE TITLE
ECHAM6 HIST ERA5-nudged simulation: simulation stopped at 202112 because of missing era5 SST forcing files of 2023

### ISSUE THREAD

**Issue by QinggangGao** [esm-tools/esm_tools#1069]
Dear Team

I am running an ERA5-nudged HIST simulation using ECHAM6 up to 2022. But it failed at 202112 because of missing ERA5 SST forcing files of 2023. May I ask, why is this file necessary and how to circumvent it?

esm_tools version: 6.23.3
exp folder: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/nudged_701_5.0`
log file: `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/nudged_701_5.0/run_20211201-20211231/log/nudged_701_5.0_echam_compute_6746462.log`
Error message: 

>   0:  readsst: fn0: sst2021 fn1: sst2022 fn2: sst2023 nist:           20
>   0:  This is an AMIP run (lamip = .true.).
>   0:  Reading sst from files sst2021     , sst2022     , sst2023
>   0:  Could not open file <sst2023     >
>   0: FATAL ERROR in readsst: run terminated.
>

**Comment by mandresm** [comment]
Hi @l975421700,

I guess this is a similar case as for the issue #1060 but I'm not an ECHAM expert. @antoniofis10000 have runned nudged simulations with ECHAM coupled to FESOM, do you have an explanation for this?

The solution is probably to use thge feature `years_before`/`years_after` in your runscript. I'll have a look at it in a couple of hours.

**Comment by antoniofis10000** [comment]
Hi both.
I am sorry but I have never run AMIP experiments (in our simulations we are resolving the ocean using FESOM instead of reading the data from a file). So I am not sure at which extend the sst forcing file for 2023 is used in the 2022 simulations (I know for the atmospheric nudging the first two timesteps for 2023 will be really used).
I hope you are able to find a solution soon.

Best wishes,
Antonio.

**Comment by QinggangGao** [comment]
Hi Both

Thank you. I tried to remove the age feature `need_year_after` and `need_2years_after` in the runscript `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/nudged_701_5.0/scripts/nudged_echam6_1m.yaml`, but there is still error message in the log file `/albedo/work/user/qigao001/albedo_scratch/output/echam-6.3.05p2-wiso/pi/nudged_701_5.0/run_20211201-20211231/log/nudged_701_5.0_echam_compute_6746462.log` as below. It occurs at the very end of the simulation.

 

>  0:  readsst: fn0: sst2021 fn1: sst2022 fn2: sst2023 nist:           20
>   0:  This is an AMIP run (lamip = .true.).
>   0:  Reading sst from files sst2021     , sst2022     , sst2023
>   0:  Could not open file <sst2023     >
>   0: 
>   0: ================================================================================
>   0: 
>   0: FATAL ERROR in readsst: run terminated.
>   0:  FINISH called from PE: 0
>

**Comment by chrisdane** [comment]
Hi @l975421700  

For this AMIP run Echam apparently needs the files `sst2021`, `sst2022` and `sst2023`, i.e. current year plus 2. You do not need to run the model to wait for the error. Just make a check run and verify that those files are in the work directory. The `finished_config` file documents where the esm_tools look for the files. 

I do not fully understand your problem. Is your problem that the necessary files are available somewhere but you cannot tell the esm_tools to properly set them up for the run? Or is your problem that you don't know where to find proper forcing files at all?

For the first problem, proceed exactly as for other forcing files in the `echam.config` and `echam.datasets.yaml` configs, as e.g. for `ozone`. 
For the second problem, I don't think this is the right place to ask.

Thanks for clarifying,
Chris

**Comment by QinggangGao** [comment]
Hi Chris

Thank you. When I did a check run, it did not show a warning message about missing forcing file sst2023. 

My problem is that, in the folder `/albedo/work/projects/paleo_work/paleodyn_from_work_ollie_projects/paleodyn/nudging/ERA5/sea/T63/`, there is no sst file for 2023. I do not know where to find it, and I doubt there could be one as we are still in 2023. In `finished_config `, esm_tools does not mention anything about sst2023.

There is a file T63_era5sst_202301.nc, but I am not sure whether I should use it and how to use it. In `echam.datasets.yaml `, there is only one subsection about sst:

 forcing_sources:
         # sst
         "amipsst":
                 "${forcing_dir}/amip/${resolution}_amipsst_@YEAR@.nc":
                         from: 1870
                         to: 2016
         "pisst": "${forcing_dir}/${resolution}${ocean_resolution}_piControl-LR_sst_1880-2379.nc"


Regards, Qinggang

**Comment by chrisdane** [comment]
For ozone, `echam.datasets.yaml` does
```
forcing_sources:
        "ozone_hist_scenario":
                "${forcing_dir}/ozone/${resolution}_ozone_${scenario}_2099.nc":
                        from: 2100
```
, i.e. from model year 2100 and beyond, the same file from 2099 will be used.

Would something like that solve your problem?

I don't know why the esm_tools do not report `sst2023` as a missing file (they should?).

Cheers,
Chris

**Comment by mandresm** [comment]
@chrisdane and @antoniofis10000, thanks for your input!

@l975421700, I also don't know the answer about the missing file but I've seen @christian-stepanek is the owner of those files in here `/albedo/work/projects/paleo_work/paleodyn_from_work_ollie_projects/paleodyn/nudging/ERA5/sea/T63/`. @christian-stepanek, do you have a recommendation for which file to use in this case?

**Comment by christian-stepanek** [comment]
Good evening. These files have been prepared by Alexandre Cauquoin who works with @mwerner-awi. The files originate from here: /albedo/work/user/acauquoi/nudging/ERA5/sea/. Until we have a pool directory the files are available at the location that you mentioned.

The newest data that Alexandre prepared is indeed for January this year. Not sure whether I understand the problem correctly. From my point of view nudging beyond the year for which sst reanalysis data is available does not make much sense - in contrast to the ozone problematic where indeed the data of the most recent forcing year is just copied and reused perpetually. Indeed, for some forcing files ECHAM would like to see data up to two years into the future. Maybe with regard to sst data, and for nudging, there is a specific trick (that @mwerner-awi might now) to overcome this hurdle, but I unfortunately do not know an out-of-the-box recipe to run until the most recent date for which data is available.

**Comment by mwerner-awi** [comment]
Dear All,

@l975421700 and @christian-stepanek: just rename the file T63_era5sst_202301.nc to T63_era5sst_2023.nc and T63_era5sic_202301.nc to T63_era5sic_2023.nc. This should solve your problem.

Explanation: ECHAM always expects three SST and SIC files: the previous year, the current year, and the next year. The reason for this is that these files only contain sst and sea ice cover values on the 15th of each month. The interpolation between the months is done by ECHAM itself. Thus, for running an experiment until 202212, the values of 15th of 202301 are required to do the interpolation for the second half of December 2022.

Btw, this problem has nothing to do with nudging but is the usual requirement of ECHAM if you want to force the model with yearly varying SST and SIC files.

**Comment by mandresm** [comment]
Thanks @mwerner-awi and @christian-stepanek for the clarifications.

@l975421700, did the solution providewd by @mwerner-awi solved the issue? It is always possible to rename it on the experiment folder itself via ESM-Tools using `add_forcing_sources` in your runscript if you prefer that. The syntax is equivalent to that that @chrisdane suggested. Please, let me know if you need further help with that, or if I can close the issue.

**Comment by QinggangGao** [comment]
Dear all

That all makes sense, thank you. I solved the problem by changing  `@YEAR@` to `${echam.current_date!syear}` below:

>         sst: "/albedo/work/projects/paleo_work/paleodyn_from_work_ollie_projects/paleodyn/nudging/ERA5/sea/T63/T63_era5sst_@YEAR@.nc"
>         sic: "/albedo/work/projects/paleo_work/paleodyn_from_work_ollie_projects/paleodyn/nudging/ERA5/sea/T63/T63_era5sic_@YEAR@.nc"

This issue can be closed for me.

Regards, Qinggang
