### ISSUE TITLE
yaml file for levante could not be determined (branch: awiesm-2.1-recom-scen)

### ISSUE THREAD

**Issue by a270105** [esm-tools/esm_tools#1076]
I need to redo some experiments with changed parameters. The old experiments were done with the model `awiesm-2.1-recom-par-tracers` which was installed via the esm-tools branch `awiesm-2.1-recom-scen`. I only changed the parameters and started a branch-off experiment from my old experiment. The experiment should run for 300 years and the first year was fine. However, to start the second year I got this error massage in `my_experiment_compute_year...log`:
```

WARNING:root:The yaml file for this computer (l40104.lvt.dkrz.de) could not be determined!
WARNING:root:Continuing with generic settings...
sbatch.bin: error: This does not look like a batch script.  The first
sbatch.bin: error: line must start with #! followed by the path to an interpreter.
sbatch.bin: error: For instance: #!/bin/sh
```
The .run script indeed starts without #!/bin/sh and my account information, etc. What happened and why is it not the case for the first year?

I remember that the branch `awiesm-2.1-recom-scen` was merged to the release last year. Does the error relate to some updates in the release branch which could be missing in `awiesm-2.1-recom-scen`? I updated the levante.yaml in esm_tools/configs/machines and it did not help.

My new experiment is here: /work/bm1030/a270105/awiesm-output/LGM_Kver0d1. I had to resubmit the runscript for each year from 4000 to 4004. But you can still see the error massage in log/LGM_Kver0d1_awiesm_compute_400{1..3}....

**Comment by chrisdane** [comment]
Duplicate of https://github.com/esm-tools/esm_tools/issues/872. Update your esm_tools and it should work.

**Comment by a270105** [comment]
OK, thanks!
