### ISSUE TITLE
documentation needs updates

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#1088]
**Request/contribution description**
The information at https://esm-tools.readthedocs.io/en/latest/installation.html#before-you-continue is outdated.

**Suggested chapter/section in the documents**
Accessing components in DKRZ server
Before you continue

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
Applies to ESM-tools as a whole.

**Contribution**
Update the email address. Dirk Barbi is not a person to contact anymore.
Update the HPC section from ollie to albedo. Note that the install.sh script does not run out-of-the-box on albedo even if the for ollie suggested modules are loaded. On albedo, pip is called pip3 - the install procedure started for me when replacing pip with pip3 in install.sh but then ended with an unsatisfied dependency.
Could not find a version that satisfies the requirement pydantic==1.10.2 (from esm-tools==6.25.1)

**Comment by nwieters** [comment]
Hi @christian-stepanek,

thank you for your suggestions on how to improve this section in the documentation.

This issue is a bit related to issue #1054 . I am currently working on an update of the documentation regarding installation etc. I will add your suggestions into the PR #1087 .

**Comment by nwieters** [comment]
> Update the HPC section from ollie to albedo. Note that the install.sh script does not run out-of-the-box on albedo even if the for ollie suggested modules are loaded. On albedo, pip is called pip3 - the install procedure started for me when replacing pip with pip3 in install.sh but then ended with an unsatisfied dependency.

I can't reproduce this error. I get pip in different versions on Albedo. Also without loading any modules.

**Comment by nwieters** [comment]
Just for completeness. You need to load python module to get pip on albedo.
`module load python`

**Comment by nwieters** [comment]
> Could not find a version that satisfies the requirement pydantic==1.10.2 (from esm-tools==6.25.1)

I think this is because you tried this using a miniconda installation. Maybe this miniconda is for a python verison that is not compatible to the esm-tools packages.
