### ISSUE TITLE
Documentation cookbook entry on how to setup AWI-ESM simulations with modified topography

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#1102]
**Request/contribution description**
A cookbook entry on how to setup AWI-ESM simulations with modified topography

**Suggested chapter/section in the documents**
Cookbook

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
Include the runscript and/or other relevant files that you modified (indicate file paths if necessary).

**Contribution**
In case this is a contribution, please include here the text to be added to the documentation.

**Comment by nwieters** [comment]
Hi @christian-stepanek , @mandresm ,
I added a section in the ESM-Tools documentation cookbook for a short discription on how to do a simulation with modified topography. I took the description @christian-stepanek send me via email. 
You can have a look at the changed documentation here: https://esm-tools.readthedocs.io/en/1102-documentation-cookbook-entry-on-how-to-setup-awi-esm-simulations-with-modified-topography/cookbook.html#awi-esm-simulations-with-modified-topography
Let me know, if the text is ok for you or if I can still do same adjustments to it.

**Comment by christian-stepanek** [comment]
Dear Nadine,

thanks a lot for this, it is very helpful for paleoclimate modellers new to ECHAM6 and greatly appreciated. I would have some updates to the text, some newer information did not make it into the description. Can I edit my self? Or shall I send remarks for you to implement?

**Comment by nwieters** [comment]
Hi @christian-stepanek,
you can edit the text yourself. if you want. Or send me the edited new text. That is up to you.
Thank you.

**Comment by christian-stepanek** [comment]
Dear @nwieters , please see my suggested changes that I committed. It may be that I broke some formatting, though. Sorry.
