### ISSUE TITLE
Wrong version at runtime in coupled setup.

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1149]
on branch: https://github.com/esm-tools/esm_tools/tree/feat/awicm3-v3.3
I run this runscript with awicm3 version: 
https://github.com/esm-tools/esm_tools/blob/457099cf69e8b7088acf485ee1e1c06081cd6112/runscripts/awicm3/v3.3/awicm3-v3.3-levante-TCO95L91-CORE2.yaml#L4

This sets the following coupling:
https://github.com/esm-tools/esm_tools/blob/457099cf69e8b7088acf485ee1e1c06081cd6112/configs/setups/awicm3/awicm3.yaml#L71-L74

Which selects this OpenIFS version:
https://github.com/esm-tools/esm_tools/blob/457099cf69e8b7088acf485ee1e1c06081cd6112/configs/couplings/fesom-2.5%2Boifs-48r1%2Bxios-2.5/fesom-2.5%2Boifs-48r1%2Bxios-2.5.yaml#L4

When I run the runscript up top, I get the following output in the finished config yaml:
```
oifs:
    version: 43r3
```

Where did I go wrong?

**Comment by nwieters** [comment]
Hi @JanStreffing,

for me it worked when I added the oifs version in the awicm3.yaml file for the specific major_version v3.3. The Fesom version is also set the same way.

I added in 

```
oifs:
    choose_general.major_version:
        "v3.3":
            version: "48r1"
```

In my case I added it in line 222.

Let me know if this solved the issue for you.

**Comment by JanStreffing** [comment]
That worked! ty!
I guess this is one of the cases where esm_master and esm_runscripts act differently. Master gets the version number from the coupling, while runscripts needs the separate variable. I had never run into this so far, as I always used 43r3 for openifs.

**Comment by nwieters** [comment]
Hi @JanStreffing ,
thank you for the comment. That is good to know that esm_master and esm_runscripts show a different behaviour in this respect.
