### ISSUE TITLE
pool on mistral and distributed example run scripts currently not functional for awi-cm2 simulations

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#115]
Currently, awicm-2 simulations do not run out-of-the-box on mistral.

1. There is a problem with the fesom pool in that at least for the CORE2 mesh not all necessary files are available
2. The example YAML-file does not provide a working setup without changes "under the hood"

I propose the following two solutions:

1. Update the data pool with regard to the mesh_CORE2_finaltopo_mean that I have copied 
 from ollie to here:
```
/work/ba1066/a270061/mesh_CORE2_finaltopo_mean/
```
2. provide the following simulation YAML as a "better working example" for mistral:
```
/pf/a/a270061/esm_tools_v4/myrunscripts/PI_ctrl_awiesm-2.1_LR_mistral.yaml
```
I think generally we should try to provide for each machine at least one working experiment YAML file to keep the learning curve for newcomers less steep.

**Comment by pgierz** [comment]
To point 1: Talk to tido

To point 2: Please remind me this afternoon once you have your tests finished. I'd do it for you, but I don't want to play with my test branches too much right now...If you'd like to do it yourself:

```
$ cd /where/your/esm_tools/are
$ git checkout prep_release # Goes to the branch prep release, which will become 4.2
$ git checkout -b new_runscript_example
$ cp /pf/a/a270061/esm_tools_v4/myrunscripts/PI_ctrl_awiesm-2.1_LR_mistral.yaml runscripts
$ git add runscript/PI_ctrl_awiesm-2.1_LR_mistral.yaml 
$ git commit -m "runscript example for mistral"
$ git push --set-upstream origin new_runscript_example
```

Then open a pull request online, and make sure it points to prep_release as the target branch to merge into (and **not** release)

**Comment by pgierz** [comment]
Hey @christian-stepanek, can you double check if this is purely an issue with the pool?

**Comment by pgierz** [comment]
Closing for now, please open a new issue if we still need to discuss pool problems (I guess, we will need to discuss them still)
