### ISSUE TITLE
Setting use_venv in runscipt has no effect

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#1150]
**Describe the bug**
Setting the variable `use_venv` in runscript -> general section has no effect, since it will be overwritten by `None` from command_line_config.
This causes esm_runscripts to always asking whether an venv should be generated. Even if set to `False` in the runscript.

**To Reproduce**
Call `esm_runscripts` without `--open-run`

**Expected behavior**
Runscript variable for `use_venv` should be taken when no `--open-run` is given as argument.

**Screenshots**

**System (please complete the following information):**
 - Supercomputer: [which machine you are on]
 - Version [Please run `esm_tools --version`]

esm_tools, version 6.29.0

**Additional context**

**Comment by nwieters** [comment]
Short update. Thank you @JanStreffing for your comment in the ESM-Tools meeting. This error is new in release. I will try to find the commit that introduced it and implement a fix.

**Comment by JanStreffing** [comment]
good to know.
last version bump in my branch is: https://github.com/esm-tools/esm_tools/commit/9e2cae8b58b70a41e76096fe74b1083d0bbd635f
