### ISSUE TITLE
Re-Design of output and logging

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#116]
Currently a logger is implemented in all the tools (which is not used) and print statements are used to inform the user on progress of the tools.
Suggestion: Implement proper logging that works across all the tools. With that the verbosity of the output can be easily modified (debug, info, warn, error level settings) in the python logger. This requires a lot of boring work going through ALL the tools and replacing the `print` statements with `logger.info(...)` statements. In addition logging to file(s) is easy to implement. The log level should then be configurable via the runscript yaml.
Who volunteers to do this :-)

**Comment by seb-wahl** [comment]
Also the print of `esm_runscripts` is very long now e.g. do we really need print all namelist contents. I think it would be better to have a print like: `echam namelist settings: /path/to/namelist/echam/in/run_xxxx-xxxx/work/namelist.echam` etc.

**Comment by pgierz** [comment]
If we aren't opposed to a new dependency: https://loguru.readthedocs.io/en/stable/index.html

We get fancy colors, easy routing of logs to multiple files/stdout. I'll have a look over the weekend.

**Comment by dbarbi** [comment]
solved by paul in release 5
