### ISSUE TITLE
improvement of File Dictionaries documentation

### ISSUE THREAD

**Issue by SpontEIN** [esm-tools/esm_tools#117]
The documentation on the file dictionaries (https://esm-tools.readthedocs.io/en/latest/yaml.html#file-dictionaries) is very difficult to understand and should be improved, especially by more explicit examples.

This section is crucial for many scientific users. Changing and adding input and forcing files is what we mostly do to run our simulations. There is the function `add_forcing_sources` which sounds like something I want to use, but there is no documentation on it. 

It took me quite some time to figure out how the dictionary forcing_files is interacting with forcing_sources. After understanding how it works, the following sentence made sense to me, before I could not make sense of it:
> This means that for a scenario PI-CTRL the files that are handled by ESM-Tools will be exclusively the ones specified inside forcing_files, defined in the forcing_sources as pisst, pisic, piaerocoarse, piaerofin, piaerofarir and piozone, and they are tagged with new general keys (sst, sic, …) that are common to all scenarios. The source files not included in forcing_files won’t be used.

I will try to come up with some improvement suggestions, but first I need to get a better understanding of how this works.

**Comment by pgierz** [comment]
Could you perhaps make a small list of cases you would like to have examples for?

**Comment by SpontEIN** [comment]
First of all some more specific questions here:
1. the `option` table (https://esm-tools.readthedocs.io/en/latest/yaml.html#file-dictionaries) refers to the `target` or the `target path`. It is unclear for which dict `option` which `target` is the default?
2. What is the hierarchy of modifications in the different config files? In case of echam we use 3 yaml files (`my_runscript.yaml`, `echam.yaml` and `echam.datasets.yaml`) + a namelist. When I specify different `my_fictitious_forcing.nc` files in these yaml files, which one will be used for the run?
3. the `file_tag` keys in `forcing_fields` and `forcing_sources` are different (e.g. `sst`). I can not use `sst` key in `forcing_sources`, instead I need to use `forcing_files` to connect `sst: pisst` (where `pisst` is the key used in `forcing_sources`). Why?
4. the `in_work` option only handels how and where files FROM the work directory are copied TO (the mysterious `target`)? i.e. to `output` dir, `forcing` dir, `restart` dir etc. That ist what the documentation in the `option` table suggests. However I think it does more. From `echam.yaml`:
```  
forcing_in_work:
        sic: "unit.96"
        sst: "unit.20"
```
It looks like this dictionary also defines how the file linked via `sst` will be called in the work dir.


---
> Could you perhaps make a small list of cases you would like to have examples for?

good idea Maybe the existing ECHAM example can be extended:
1. the `option` table also implies that the files dicts are used to handle where the files will be copied to and maybe renamed. But first of all I need to know how to get `my_fictitious_forcing.nc` file into the work dir. There should be an example for that. Maybe also highlighting the different ways how to do that (e.g. `add_forcing_sources` vs modify `forcing_sources` directly). 
2. in the bash script version I could just use an `ln -s` to link some files into the work dir, how can I do this now? These linked  files are are unknown to echam, because `my_coupled_submodel` needs them as input in the work dir?
3. an example should also explain how I can introduce new `file_tag` keys, or make clear if this is at all possible?

**Comment by mandresm** [comment]
The YAML chapter is infact one of the most important chapters and we are still working on it. You can actually check a much recent version in the [prep_release](https://esm-tools.readthedocs.io/en/prep_release/yaml.html) version and this will soon be the default once release 4.2 is out. I'll keep working on this chapter after release and include your comments.
