### ISSUE TITLE
installing echam

### ISSUE THREAD

**Issue by yoluo001** [esm-tools/esm_tools#1241]
When installing echam, enter the following statement "esm_master install-echam-6.3.05p2" and an error occurs after running, as shown in the following screenshot.

![Screenshot 2024-10-25 at 12 15 06](https://github.com/user-attachments/assets/da3f7d5c-ae26-4033-bdcb-320b9a4535f9)

**Comment by pgierz** [comment]
This is a `glibc` error, and affects all of `albedo`, might be linked to the container image currently on the login nodes.

**Comment by pgierz** [comment]
Hi @yoluo001,

I have a provisional fix which should allow you to compile the model. I'm not sure why this hasn't popped up before, maybe you are the first person to run ECHAM-6.3.05p2 standalone on Albedo.

In your `echam-6.3.05p2` source code folder, you need to modify the following file to allow the linker to find `librt.so`:

```diff
diff --git a/cdi/src/CMakeLists.txt b/cdi/src/CMakeLists.txt
index 2183e78..c8b80ae 100644
--- a/cdi/src/CMakeLists.txt
+++ b/cdi/src/CMakeLists.txt
@@ -23,6 +23,7 @@ target_compile_definitions(${PROJECT_NAME} PUBLIC VERSION="1.7.0" gFortran HAVE_
 target_link_libraries(${PROJECT_NAME}
    PRIVATE yaxt
    INTERFACE ${NETCDF_C_LIBRARIES} ${HDF5_C_LIBRARIES}
+   rt
 )
 if(${CMAKE_C_COMPILER_ID} STREQUAL Intel)
        # enable c99 for intel (icc defaults to c89) (gcc already defaults to a c dialect of this century)
```
With that addition (one little line) it compiles for me. Let me know how it works for you.

Cheers,
Paul

**Comment by yoluo001** [comment]
Dear Paul,

I tried to modify it as what you said, but it seems to fail. If it is convenient for you, could you share the file you successfully ran with me?
Thanks a lot.

All the best,
Yongyue
30. Oct 2024 09:57，Paul Gierz ***@***.***> 写道：



Hi @yoluo001<https://github.com/yoluo001>,

I have a provisional fix which should allow you to compile the model. I'm not sure why this hasn't popped up before, maybe you are the first person to run ECHAM-6.3.05p2 standalone on Albedo.

In your echam-6.3.05p2 source code folder, you need to modify the following file to allow the linker to find librt.so:

diff --git a/cdi/src/CMakeLists.txt b/cdi/src/CMakeLists.txt
index 2183e78..c8b80ae 100644
--- a/cdi/src/CMakeLists.txt
+++ b/cdi/src/CMakeLists.txt
@@ -23,6 +23,7 @@ target_compile_definitions(${PROJECT_NAME} PUBLIC VERSION="1.7.0" gFortran HAVE_
 target_link_libraries(${PROJECT_NAME}
    PRIVATE yaxt
    INTERFACE ${NETCDF_C_LIBRARIES} ${HDF5_C_LIBRARIES}
+   rt
 )
 if(${CMAKE_C_COMPILER_ID} STREQUAL Intel)
        # enable c99 for intel (icc defaults to c89) (gcc already defaults to a c dialect of this century)

With that addition (on little line) it compiles for me. Let me know how it works for you.

Cheers,
Paul

**Comment by pgierz** [comment]
Hi @yoluo001, 

could you send me the path to your model code? I'll have a look.

Cheers PG

**Comment by yoluo001** [comment]
Hi Paul,

Ok, the path is "/albedo/work/user/yoluo001/model_codes/echam-6.3.05p2”. Thanks a lot.

Best wishes,
Yongyue
4. Nov 2024 09:23，Paul Gierz ***@***.***> 写道：



Hi @yoluo001<https://github.com/yoluo001>,

could you send me the path to your model code? I'll have a look.

Cheers PG

**Comment by pgierz** [comment]
Hi @yoluo001, it doesn't look like you modified anything! If I run git status on that folder, I just get:

```
yoluo001@albedo0:/albedo/work/user/yoluo001/model_codes/echam-6.3.05p2$ git status
On branch 6.3.05p2
Your branch is up to date with 'origin/6.3.05p2'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	build/
```

So, you need to add the line I suggested in `cdi/src/CMakeLists.txt`. I used root privileges and did that for you. If I now run the compile command:
```
yoluo001@albedo0:/albedo/work/user/yoluo001/model_codes$ esm_master comp-echam-6.3.05p2
... lots of output ...
Install the project...
-- Install configuration: "Release"
-- Installing: /albedo/work/user/yoluo001/model_codes/echam-6.3.05p2/src/echam/bin/echam6
```
it works fine. I also can now see the echam executable:
```
yoluo001@albedo0:/albedo/work/user/yoluo001/model_codes$ ls echam-6.3.05p2/bin/
echam6
```

I'll close the issue now, since it works :-)

**Comment by yoluo001** [comment]
Dear Paul，
It turns out that I added the statements you told me to another file by mistake. Now it works. Thank you very much.
All the best,
Yongyue

4. Nov 2024 11:30，Paul Gierz ***@***.***> 写道：



Hi @yoluo001<https://github.com/yoluo001>, it doesn't look like you modified anything! If I run git status on that folder, I just get:

***@***.***:/albedo/work/user/yoluo001/model_codes/echam-6.3.05p2$ git status
On branch 6.3.05p2
Your branch is up to date with 'origin/6.3.05p2'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        build/


So, you need to add the line I suggested in cdi/src/CMakeLists.txt. I used root privileges and did that for you. If I now run the compile command:

***@***.***:/albedo/work/user/yoluo001/model_codes$ esm_master comp-echam-6.3.05p2
... lots of output ...
Install the project...
-- Install configuration: "Release"
-- Installing: /albedo/work/user/yoluo001/model_codes/echam-6.3.05p2/src/echam/bin/echam6


it works fine. I also can now see the echam executable:

***@***.***:/albedo/work/user/yoluo001/model_codes$ ls echam-6.3.05p2/bin/
echam6


I'll close the issue now, since it works :-)
