### ISSUE TITLE
Recomp problem

### ISSUE THREAD

**Issue by hajlaci** [esm-tools/esm_tools#1248]
```
esm_master recomp-awiesm3-v3.4/lpj_guess
    Executing commands in this order:
         mkdir -p awiesm3-v3.4
         cd awiesm3-v3.4
         sed -i 's/xios-2.5+/xios/g' oifs-48r1/bundle.yml
         sed -i 's/oasis3-mct-5.2/oasis/g' oifs-48r1/bundle.yml
         cd lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/
         rm -rf build
         cd ..
         rm -f ./bin/guess
         cd lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/
         mkdir -p /work/ab0995/a270270/model_codes/awiesm3-v3.4/lpj-guess/sources/LPJ-GUESS-lpjg_v4p1//build; cd /work/ab0995/a270270/model_codes/awiesm3-v3.4/lpj-guess/sources/LPJ-GUESS-lpjg_v4p1//build; cmake .. -DOASIS=ON; make -j8
         cd ..
         mkdir -p ./bin
         cp  lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/build/guess  bin
         cd ..
cp: cannot stat '../comp-lpj_guess-4.1.2_script.sh': No such file or directory
```
This part of the code is problem since it uses cd .. but actually it should use cd -

 cd lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/
  rm -rf build
  cd ..

The used branch is feat/awiesm3-v3.4

**Comment by mandresm** [comment]
I think this is wrong:

https://github.com/esm-tools/esm_tools/blob/faa1540aa66d98c708ed0f8a8e0b50601fccc8ff/configs/components/lpj_guess/lpj_guess.yaml#L28

It should be ` comp_command: "mkdir -p build; cd build; cmake ..; make -j8" `

`comp_command` behaves differently whether it is a standalone compilation or coupled compilation and it should all be done automatically under the hood.

Let me know if that works.

**Comment by hajlaci** [comment]
No it didn't. Same problem:

Executing commands in this order:
         mkdir -p awiesm3-v3.4
         cd awiesm3-v3.4
         sed -i 's/xios-2.5+/xios/g' oifs-48r1/bundle.yml
         sed -i 's/oasis3-mct-5.2/oasis/g' oifs-48r1/bundle.yml
         cd lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/
         rm -rf build
         cd ..
         rm -f ./bin/guess_T159
         cd lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/
         mkdir -p /work/ab0995/a270270/model_codes/awiesm3-v3.4/lpj-guess/sources/LPJ-GUESS-lpjg_v4p1//build; cd /work/ab0995/a270270/model_codes/awiesm3-v3.4/lpj-guess/sources/LPJ-GUESS-lpjg_v4p1//build; cmake .. -DOASIS=ON; make -j8
         cd ..
         mkdir -p ./bin
         cp  lpj-guess/sources/LPJ-GUESS-lpjg_v4p1/build/guess_T159  bin
         cd ..
cp: cannot stat '../comp-lpj_guess-4.1.2_script.sh': No such file or directory

**Comment by mandresm** [comment]
Hi @hajlaci, I made a fix for `esm_master`. It should start working now as you intended to use it. I have pushed directly to the branch `feat/awiesm3-v3.4`. Please, let me know if that solves the problem :)

**Comment by hajlaci** [comment]
Yes it's working! Thank's a lot!

**Comment by mandresm** [comment]
You are welcome! :)

**Comment by mandresm** [comment]
I've pushed and even better solution, basically doing what you suggested at the beginning, using `cd -`. Originally, I thought that would break other parts of the code, but after looking at it more carefully, that solution won't break anything, and it is less error prone than the one I've implemented originally yesterday.

Feel free to pull again in the branch, and let me know if the new commit breaks anything for you.

**Comment by mandresm** [comment]
Hi @hajlaci, I made a mistake on the bugfix so I am reopening the issue

**Comment by mandresm** [comment]
Hi @hajlaci! Please update now with `release`. I fixed a bug there.

**Comment by hajlaci** [comment]
Thanks a lot!
