### ISSUE TITLE
Installation of AWIESM-2.6: Cloning into 'oasis' fails

### ISSUE THREAD

**Issue by mbutzin** [esm-tools/esm_tools#1252]
**Describe the problem you are facing**
A clear and concise description of what are you aiming to do and what is not working.

I cannot install AWIESM-2.6 because I do not get access to the OASIS repository at gitlab.awi.de. 

**To Reproduce**

mbutzin@albedo0:~/esm_work$ esm_master install-awiesm-2.6
[ ... ]
Cloning into 'oasis'...
Username for 'https://gitlab.awi.de': mbutzin
Password for 'https://mbutzin@gitlab.awi.de': 
remote: HTTP Basic: Access denied. If a password was provided for Git authentication, the password was incorrect or you're required to use a token instead of a password. If a token was provided, it was either incorrect, expired, or improperly scoped. See https://gitlab.awi.de/help/topics/git/troubleshooting_git.md#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://gitlab.awi.de/paleodyn/Models/oasis3-mct.git/'
Cloning into 'echam-6.3.05p2'...
[ This works ...]

ERROR: Download error
---------------------
There were problems downloading some of the components involved in the operation install-awiesm-2.6. Make sure the user names and passwords you introduced are correct. Also, check that you have access and reading permissions to the repositories listed below. If you don't, contact the person in charge of that particular repository (see contact in the repository list below).

Repositories with problems:
oasis3mct: https://gitlab.awi.de/paleodyn/Models/oasis3-mct.git
    contact: miguel.andres-martinez(at)awi.de, paul.gierz(at)awi.de
    failed command: git clone -b 2.8mct-awiesm-2.1 https://gitlab.awi.de/paleodyn/Models/oasis3-mct.git oasis
    error message:
Command '['git', 'clone', '-b', '2.8mct-awiesm-2.1', 'https://gitlab.awi.de/paleodyn/Models/oasis3-mct.git', 'oasis']' returned non-zero exit status 128.

**System (please complete the following information):**
 - Supercomputer: [which machine you are on]
albedo
 - Version [Please run `esm_tools --version`]
6.43.4

**Additional context**

**Comment by mandresm** [comment]
Hi @mbutzin,

I have added you to the repository. Please, let me know if it works for you now.

Kind regards,
Miguel

**Comment by mbutzin** [comment]
Yes, it works -- thank you, @mandresm!
