### ISSUE TITLE
recomp-fesom-2.6 fails

### ISSUE THREAD

**Issue by mbutzin** [esm-tools/esm_tools#1256]
**Describe the bug**

I successfully installed (and run) FESOM-2.6 on Levante but after modifiying the FESOM source code I cannot recompile FESOM with 'esm_master recomp-fesom-2.6.' However,  esm_master comp-fesom-2.6 works as expected.

**To Reproduce**

a270108@levante4:~/esm_codes$ esm_master recomp-fesom-2.6
    Executing commands in this order:
         cd fesom-2.6
         rm -rf build CMakeCache.txt
         cd -
         rm -f fesom-2.6/bin/fesom.x
         cd fesom-2.6
         mkdir -p build; cd build; cmake -DCMAKE_INSTALL_PREFIX=../ ..;   make install -j `nproc --all`
         cd -
         mkdir -p fesom-2.6/bin
Traceback (most recent call last):
  File "/home/a/a270108/.local/bin/esm_master", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_master')())
  File "/home/a/a270108/esm_tools/src/esm_master/cli.py", line 113, in main
    main_flow(parsed_args, target)
  File "/home/a/a270108/esm_tools/src/esm_master/esm_master.py", line 107, in main_flow
    user_task.execute(ignore_errors)  # env)
  File "/home/a/a270108/esm_tools/src/esm_master/task.py", line 447, in execute
    os.chdir(command.replace("cd ", ""))
FileNotFoundError: [Errno 2] No such file or directory: '-'

**Expected behavior**

Full compilation works without errors:
a270108@levante4:~/esm_codes$ esm_master comp-fesom-2.6
    Executing commands in this order:
         cd fesom-2.6
         mkdir -p build; cd build; cmake -DCMAKE_INSTALL_PREFIX=../ ..;   make install -j `nproc --all`
         cd -
         mkdir -p fesom-2.6/bin
-- setting default build type: Release
...
[ 99%] Building Fortran object src/CMakeFiles/fesom.x.dir/fesom_main.F90.o
[100%] Linking Fortran executable ../bin/fesom.x
[100%] Built target fesom.x
Install the project...
-- Install configuration: "Release"

**Screenshots**

**System (please complete the following information):**
 - Supercomputer: Levante
 
 - Version: 6.43.4

**Additional context**

**Comment by mandresm** [comment]
Yes, a PR was merged a bug. The tag affected is precisely `6.43.4`. I just added a fix, please try it now after pulling and making sure you are using `6.43.5` version.

**Comment by mbutzin** [comment]
Now it works, thanks.
