### ISSUE TITLE
model setup doesn't show up in esm_master

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#126]
Starting from @seb-wahl focioifs.yaml setup I'm trying to write an awicm3 setup. wip can be found in branch [https://github.com/esm-tools/esm_tools/tree/awicm3-on-v4.2](awicm3-on-v4.2)

The model name given is awicm3. However `esm_master awicm3` does not show any options:
```
No targets found for keyword awicm3. Type 'esm_master' to get a full list
of available targets.
```

I'm guessing something is configured or formatted incorrectly in my awicm3.yaml.
Any idea what it can be?

**Comment by seb-wahl** [comment]
You must have something wrong in your esm_tools installation. If I do the following:
```bash
glogin2:~/esm/esm_tools/configs $ git checkout awicm3-on-v4.2
Branch 'awicm3-on-v4.2' folgt nun Remote-Branch 'awicm3-on-v4.2' von 'origin'.
Zu neuem Branch 'awicm3-on-v4.2' gewechselt
glogin2:~/esm/esm_tools/configs $ esm_versions check
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.0
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.0 (development install, on branch: awicm3-on-v4.2, describe=v4.2.0-1-g3e79143)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.4.0
glogin2:~/esm/esm_tools/configs $ esm_master awicm3

awicm3 is not an available target. Did you mean one of those:
setups:
    awicm3:
       3.0: ['comp', 'clean', 'get', 'update', 'status', 'log', 'install', 'recomp']
       3.1: ['comp', 'clean', 'get', 'update', 'status', 'log', 'install', 'recomp']

glogin2:~/esm/esm_tools/configs $
```
everything looks ok.

**Comment by JanStreffing** [comment]
Mhm those are the old version numbers 3.0 and 3.1 that I was using before. I decided to use 1.0 since awicm3 is already distinct from awicm by the name of yaml.

```
        available_versions:
        - '1.0'
        choose_version:
          '1.0':
            couplings:
            - fesom-2.0+oifs-43r3-awi

        version: "1.0"
```


I seem to be using the same esm_tools component versions:
```
esm_versions check
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0 (development install, on branch: release, describe=v4.2.0)
esm_master: 4.2.0
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.0 (development install, on branch: awicm3-on-v4.2, describe=v4.2.0-1-g3e79143)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.4.0
```

only difference is: esm_environment: 4.2.0 (development install, on branch: release, describe=v4.2.0). I cloned the esm_environment by hand after deleting a very old (6 months) version before. Can this make the difference?

**Comment by seb-wahl** [comment]
There's indeed something wrong here:
```bash
glogin1:~/esm/esm_tools/configs $ esm_master awicm3

awicm3 is not an available target. Did you mean one of those:
setups:
    awicm3:
       3.0: ['comp', 'clean', 'get', 'update', 'status', 'log', 'install', 'recomp']
       3.1: ['comp', 'clean', 'get', 'update', 'status', 'log', 'install', 'recomp']

glogin1:~/esm/esm_tools/configs $
glogin1:~/esm/esm_tools $ esm_master install-awicm3-3.0 -c
attach_to_config_and_reduce: File fesom2 of model fesom2 could not be found. Sorry.
```
I'm a bit lost here. I have the suspicion that something's wrong with the `fesom-2.0.yaml`. @pgierz @mandresm @dbarbi may have an idea what's wrong. I'm a bit lost in your fesom vs fesom-2.0 difference.

**Comment by seb-wahl** [comment]
In addtion I currently don't have an idea where the 3.0 and 3.1 version numbers come from that `esm_master` prints above. They are NOT in `configs/setups/awicm3/awicm3.yaml :-(

**Comment by JanStreffing** [comment]
Paul said that may be from the esm_master.pkl file

**Comment by mandresm** [comment]
Hi Jan, I'm having a look. I have a few questions regarding the `awicm3.yaml`:

- Is the choose block in line 540 incorrectly indented?
- Are the preprocessor and postprocessor sections correctly indented?

Even if I change the indent of these sections I am still facing the same problem as you. I'll keep having a look at it.

**Comment by pgierz** [comment]
OK, we have discovered the problem. It turns out two things were biting each other:

1. Jan's file had some unfortunate tab/space mixing. Sadly, the yaml loader (not from us, it's 3rd party) is picky about that, and refuses to load the yaml file if you mix these. Please, **only** use spaces.

2. We have an exception handle that actually checks this, and, if you have tabs, it **should** tell you that you messed up, and throw an error.

....however, the part of esm_master that gathers all the information runs asynchronously. We have a part that checks each element of the async routines for exceptions, and should give them back. However, the switch is badly named: https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently

Dirk and I both looked at it and assumed return exceptions means "return if no exceptions happened", instead of "return despite exceptions"...it's documented correctly, but the name is confusing...

we had `return_exeptions=True`, instead of `False`. I'll patch esm_master, and give it a command line switch to optionally turn off the async stuff.

**Comment by JanStreffing** [comment]
Works. Thank you!

**Comment by pgierz** [comment]
Once the patch goes in I'll close this. @JanStreffing, to keep the code more maintainable, we're trying to start requiring reviews. Github should have bugged you via email to have a look. If the changes are readable and make sense to you, push the big button ;-)

**Comment by pgierz** [comment]
Hotfix for esm master was merged. The bug should no longer occur as of `4.2.1`. Closing this...
