### ISSUE TITLE
model output data is scattered due to disk space; which expid should be used? 

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#129]
Hi

Due to disk space issues I need to continue a run on another location. Which expid should the continuation have? 

If I use the same expid for both runs, i.e.
```
run 1: expid1 from y1 to y100 at /path1
run 2: expid1 from y101 to y200 at /path2
```
is it possible to "combine" all data from /path1 and /path2 in a convenient way? If, e.g., someone gives me disk space on /path1, may I simply copy everything from /path2 to /path1 to have only one directory with the data from y1 to y200? Would the internal esm-tools structure allow that (filenames, timestamps, etc.)? 

If I use another expid for the second run, i.e.
```
run 1: expid1 from y1 to y100 at /path1
run 2: expid2 from y101 to y200 at /path2
```
the data of the two runs cannot be combined in the future, I guess?

Is there a recommendation from your side?

Thanks a lot,
Chris

**Comment by pgierz** [comment]
Are you using the shell or python version?

**Comment by chrisdane** [comment]
shell

**Comment by pgierz** [comment]
Shell is legacy. Good luck 😂

Jokes aside, I’ll have a closer look tomorrow.

**Comment by pgierz** [comment]
Name both experiments the same, and set `$BASE_DIR` to `/path2` where you have space. It **must** be different from `/path1`, or the old shell version will assume you are continuing the run. Maybe that is what you want anyway, but with space concerns, it's understandable that you need to use a different directory.

> is it possible to "combine" all data from /path1 and /path2 in a convenient way? If, e.g., someone gives me disk space on /path1, may I simply copy everything from /path2 to /path1 to have only one directory with the data from y1 to y200? Would the internal esm-tools structure allow that (filenames, timestamps, etc.)?

This should be possible. I would do the copy with `rsync`, best in a dry-run mode first, e.g.:

```shell
$ rsync -avzhP --dry-run /path/to/path2/ /path/to/path1/ # Note the **important trailing slash on both!!!**
```

**Comment by chrisdane** [comment]
Thanks. How about the python version?

**Comment by pgierz** [comment]
I don't think anyone has tried that yet for the Python Version...Would you agree that this is something we should test out, and ideally put into the handbook?

For the shell version, can you try with one year, and let me know if it works?
