### ISSUE TITLE
ECHAM restart problems

### ISSUE THREAD

**Issue by ghost** [esm-tools/esm_tools#130]
Hi, 
I started a 3 year ECHAM standalone time slice simulation on mistral that is located at

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_LAMO_HICE_sara_3years/`

with the corresponding runscript at

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_LAMO_HICE_sara_3years/scripts/echam_johannes.yaml`

Currently, I am submitting a new job for each year.
As intended restarts files are written at the end of each year, but it's currently not using them when starting the subsequent year. Therefore, the problem apparrently is that for each year the same initial run is done as for the first year.

I'm not completely sure, but I think a potential source of this problem might be that in the echam namelist of the runs for the 2nd and 3rd year 
e.g. 
 `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_LAMO_HICE_sara_3years/run_18510101-18511231/work/echam.namelist`

 the `dt_start` parameter is defined and increased accordingly. However, as explained in some ECHAM docs

> Make sure that dt_start is either not present in the RUNCTL namelist or has still the (old)start date of the beginning of the experiment

this parameter shouldn't be defined when starting from restart. `lresume` is set to True as expected for the 2nd and 3rd year.
Any ideas how to fix this problem?

Cheers Johannes

**Comment by mandresm** [comment]
Could you please copy here the output of `esm_versions check`?

**Comment by pgierz** [comment]
...can you also paste a link to the echam docs? That seems like something we definitely should be taking care on.

**Comment by ghost** [comment]
> 
> 
> Could you please copy here the output of `esm_versions check`?


output of `esm_versions check`:

> You are using the following esm_tools versions:
> -----------------------------------------------
> esm_archiving : unknown version!
> esm_autotests : unknown version!
> esm_calendar: 4.0.1
> esm_database: 4.0.0
> esm_environment: 4.2.0
> esm_master: 4.2.0
> esm_parser: 4.2.1
> esm_profile: 4.0.0
> esm_rcfile: 4.0.0
> esm_runscripts: 4.2.1
> esm_tools: 4.2.0 (development install, on branch: Johannes, describe=v4.2.0-2-gc9f93fe-dirty)
> esm_plugin_manager: 4.2.0
> esm_version_checker: 4.4.0
> 

The simulation I described above I did with the predecessor esm_version before updating to 4.2.
However, I also started a shorter simulation over 3 months with monthly restart files with the current updated esm version located at 

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/3month_restart`

But the problem somehow still remained.

**Comment by ghost** [comment]
> 
> 
> ...can you also paste a link to the echam docs? That seems like something we definitely should be taking care on.

https://mpimet.mpg.de/fileadmin/staff/rastsebastian/echam_6.1_lecture.pdf

These are lecture slides that are referenced in the original echam docs. See page 17/18 under "Starting a rerun" for the statement about `dt_start`.

(The original ECHAM docs may be here : https://icdc.cen.uni-hamburg.de/fileadmin/user_upload/icdc_Dokumente/ECHAM/echam6_userguide.pdf)

**Comment by mandresm** [comment]
> I'm not completely sure, but I think a potential source of this problem might be that in the echam namelist of the runs for the 2nd and 3rd year
> e.g.
> `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_LAMO_HICE_sara_3years/run_18510101-18511231/work/echam.namelist`
> 
> the `dt_start` parameter is defined and increased accordingly. However, as explained in some ECHAM docs
> 
> > Make sure that dt_start is either not present in the RUNCTL namelist or has still the (old)start date of the beginning of the experiment
> 
> this parameter shouldn't be defined when starting from restart. `lresume` is set to True as expected for the 2nd and 3rd year.

In `esm_tools/configs/components/echam/echam.yaml` I found this lines:
```
350 choose_lresume:
351         False:
352                 restart_in_modifications:
353                         "[[streams-->STREAM]]":
354                                 - "vdate <--set_global_attr-- ${start_date!syear!smonth!sday}"
355                                   # - fdate "<--set_dim--" ${year_before_date}
356                                   # - ndate "<--set_dim--" ${steps_in_year_before}
357         True:
358                 # pseudo_start_date: $(( ${start_date} - ${time_step} ))
359                 namelist_changes:
360                         namelist.echam:
361                                 runctl:
362                                         dt_start: "remove_from_namelist"
```

Those lines should take care of removing `dt_start` from the namelist, so in principle that should do the job. I will look into it in more detail.

**Comment by mandresm** [comment]
To test this I have been using the runscript `echam-mistral-initial-monthly.yaml` (monthly restarts) for time-saving purposes.

With this runscript, `dt_start` is also not removed from `namelist.echam` in restart runs, and that needs to be addressed (I already found a solution for that). However, when I compare output from the different runs I find that this output is different, so it does not seem to be doing a repetition of the first run over and over again. @jobo95, could you please clarify how do you know that the restart files are not used by ECHAM in restart runs?

**Comment by ghost** [comment]
Yes, you are right. It doesn't produce exactly the same run for each restart.
However, it's definitely not using the restart files proberbly.

For my monthly restart runs, you may have a look at some difference Plots between January (initial run) and February (rerun)
with
`ncview /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/3month_diff/diff_Jan_Feb.nc`

or between January and March( rerun) with

`ncview /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/3month_diff/diff_Jan_Mar.nc`

You can clearly see that the different runs resemble eachother extremely during the first time steps (e.g. SP,U10M,T2M etc.)
From virtual inspection I would also suppose that for the second restart the difference to the initial run increases compared to the first restart (so in `diff_Jan_Mar.nc` you can generally see bigger differences than in `diff_Jan_Feb.nc`).
(I know Sara Khosravi shortly having had ECHAM restart problems with ESM shell version, where some incorrect definitions of time variables led to time shifts that accumulated with increasing restart number .But no idea whether this comes somehow into play here...)

The Echam log file `/mnt/lustre02/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/3month_restart/run_18500201-18500228/work/echam6.log` for the first restart states in the beginning:

```
29  Namelist file namelist.echam reopened
30  Read date (initial/restart):  1. Jan     1850 00:00:00
31  Basic initialization of time manager <echam time manager> done.
32  Experiment resumed at:  1. Feb     1850 00:00:00
33  Set manager to resumed time step + 1.
34  Namelist file namelist.echam reopened
35  Reset resume date from namelist:  1. Feb     1850 00:00:00
36  Start date replaced by namelist start date:  1. Feb     1850 00:00:00
37  init_manager: Set start date to resume date, force initial run
38  Time step and start date evaluation done.
39  Initial state of time manager <echam time manager> is locked now!
40  State of manager >>echam time manager<<
41  Step counter :            0
42  Time step [s]:    200.000000000000
43  Initial date:  1. Feb     1850 00:00:00
44  Current date:  1. Feb     1850 00:00:00
45 
46  Using DT_STOP for model stop.
47  Stop experiment at:  1. Mar     1850 00:00:00
48  Previous date: 31. Jan     1850 23:56:40
49  Next date    :  1. Feb     1850 00:03:20

```

In line 37 it's somehow explicitly stating that it's forcing an inital run and when comparing with other log files, e.g. step counter in line 41 shouldn't be set to zero.
So I think it's doing an initial run each time + something odd that I currently don't understand enough..

That's what I could figure out until now..

**Comment by mandresm** [comment]
Thanks a lot, we are currently looking at that.

**Comment by mandresm** [comment]
The problem should be solved now, at least the part in which `dt_start` is removed for restarts. I am currently working on preventing this type of mistakes to happen (overriding `namelist_changes` without notifying the user), but you can have a go, run a simulation and check if ECHAM is doing what is supposed to do.

**Comment by ghost** [comment]
So I repeated the simulation with monthly restart and it seems to be working properly now. When comparing the monhtly restart simulation with a three month non-restarted simulation the output bascially doesn't differ, except for the first time step of each month it differs very slightly (but I think that's a minor and nonsignificant issue at least for me, maybe to due some differences in  output timing for the first output after restart....).

So thank you very much !

**Comment by pgierz** [comment]
OK, then, if you're happy we will close this! Let us know if you have anything else.

**Comment by ghost** [comment]
> 
> 
> So I repeated the simulation with monthly restart and it seems to be working properly now. When comparing the monhtly restart simulation with a three month non-restarted simulation the output bascially doesn't differ, except for the first time step of each month it differs very slightly (but I think that's a minor and nonsignificant issue at least for me, maybe to due some differences in output timing for the first output after restart....).
> 
> So thank you very much !

Hi, 
I'd like to come to that small issue I mentioned in the end.
So when comparing a 3-month  simulation with monthly restart

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/three_month_restart/`

with a 3-month simulation without restart

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/three_month_norestart/`

then the outdata of both siimulations are bascially the same. However, the first output step after restart differs slightly from the without-restart simulation. e.g.

`cdo diff /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/three_month_norestart/unknown/three_month_norestart_185002.01_g3b6h /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/three_month_restart/unknown/three_month_restart_185002.01_g3b6h`


I'd really like to figure out whats going on here before starting a longer simulation, so does someone may has an idea about it?
Seems like a small bug at some place in the Python version, in the Shell version it doesn't appear..

**Comment by pgierz** [comment]
To help finding the differences, could you post the namelists (or paths) so we can see what's happening? I suspect this has to do with dt_start, putdata, or similar. There might be small changes with the first/last stuff that leads to the differences you describe

**Comment by ghost** [comment]
The paths to the namelists you can find in the respective work folders. So for e.g. restart in February

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/three_month_restart/run_18500201-18500228/work/namelist.echam`

and for the non-restarted run

`/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/three_month_norestart/run_18500101-18500331/work/namelist.echam`

**Comment by mandresm** [comment]
Thanks Johannes, I'll be having a look at it ASAP.

**Comment by mandresm** [comment]
@jobo95 pointed out via email:
"The only small thing I currently noticed and could  contribute is about this tiny inconsistency between restarted and non-restarted simulations for the first time step after restart (issue #130)."

**Comment by dbarbi** [comment]
This has a lot of links to issue #236, please check there too.

**Comment by JanStreffing** [comment]
> OK, then, if you're happy we will close this! Let us know if you have anything else.

It seems that the original issue as solved.
