### ISSUE TITLE
forrtl: severe (29): file not found, unit 99, file /work/ollie/nwieters/ESM/Test_esm_tools/esm_experiments//awicm2_yaml_test_001/run_20000101-20000131/fesom.clock

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#15]
I have two runscripts for awicm-2.0 which are (at least what I can say) the same. One in old style and the other as yaml file: /work/ollie/nwieters/ESM/Test_esm_tools/esm_experiments/awicm-2.0_runscripts
The yaml runscpript ends up in an error saying
forrtl: severe (29): file not found, unit 99, file /work/ollie/nwieters/ESM/Test_esm_tools/esm_experiments//awicm2_yaml_test_001/run_20000101-20000131/fesom.clock

The *.run version runs totaly fine. Can anyone see the difference?

I am using esm_tools on branch 'release' with version:
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 3.0.1
esm_database : unknown version!
esm_environment : 3.0.2
esm_master : 3.1.5
esm_parser : 3.0.3
esm_profile : 3.0.0
esm_rcfile : 3.0.1
esm_runscripts : 3.1.4
esm_tools : 3.1.4
esm_version_checker : 3.2.4

**Comment by nwieters** [comment]
This error is ALWAYS occuring, not only with runscripts in YAML format.

It seems that this error is depending on the length of the experiment id.
In the example above:
awicm2_test_001: worked
awicm2_yaml_test_001: failed

The error is saying that the path to the fesom.clock file is missing the part 'work/' which is exactly the number of letters that the experimentids differ.
Is there a restriction of string length for the path to the work folder or to the experimentid?
@dbarbi @pgierz any ideas?

**Comment by pgierz** [comment]
> Is there a restriction of string length for the path to the work folder or to the experimentid?

No.

There is an internal FESOM id length restriction. I think it is exactly the length of `fesom` but I could be wrong

**Comment by nwieters** [comment]
I have another experiment and it cuts the path always after 100 letters.

**Comment by nwieters** [comment]
Yes, this is an issue of FESOM. Just found out that it has restriction to character length of 100 for different variables. Never had this problem before.
I will close this issue.
