### ISSUE TITLE
Binaries are taken from wrong directory after restart

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#160]
**Describe the bug**
The model binaries are not found after a restart when the model directory, given under `model_dir` in the YAML file, is renamed or moved.
```
slurmstepd: error: execve(): /work/ollie/lackerma/awicm_pism_tests/test_paul03/run_20040101-20041231/work/./echam6: No such file or directory
```
Because of this, I assume the binaries are not taken from `EXP_DIR/bin/` but from `model_dir` given in the YAML file for every restart.

**Expected behavior**
The binaries should be taken from `EXP_DIR/bin/`

**System (please complete the following information):**
 - Supercomputer: Ollie
 - Version
```
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.6 (development install, on branch: release, describe=v4.2.6-1-g4116b68-dirty)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.5.0
```

**Additional context**
link to the experiment:
```
/work/ollie/lackerma/awicm_pism_tests/test_paul03
```

**Comment by pgierz** [comment]
This may be solved when we implement changes for #99 (see #128 and https://github.com/esm-tools/esm_runscripts/pull/35)

**Comment by dbarbi** [comment]
Ok, I checked the code and you are right, nothing is taken from the experiment folder so far. I am writing a hotfix right now. Thanks for reporting.

**Comment by dbarbi** [comment]
That should be fixed with branch hotfix/issue160 of packages:

- esm_tools
- esm_runscripts
- esm_master
- esm_plugin_manager

Please check
