### ISSUE TITLE
module CDO not loaded in mistral.yaml -> run fails at the beginning of the second model year

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#168]
**Describe the bug**
On mistral, the module CDO is not loaded. Apparently CDO is involved in generation of restart files of the OASIS coupler, as such are not created after the end of the first year if the CDO module is not loaded. Consequently, AWI-ESM2.1 simulations, that depend on OASIS restart files generated with CDO, will fail at the start of the second year.

**To Reproduce**
Take the release branch of esm-tools 4.2 and run an AWI-ESM2.1 simulation on mistral. The first year will run without any problem, but the second year will start with an OASIS "long number bug" that indicates that no restart files from the first model year where found.

**To overcome this problem**
- add the line '- "load cdo"' to module_actions of the mistral.yaml (e.g. ~/esm_tools_v4.2/esm_tools/configs/machines/mistral.yaml)
- start a new simulation, and voilá, the simulation will proceed also after the first model year

**Expected behavior**
A simulation should continue after the first model year has finished, i.e. without a crash caused by missing oasis restart files. This behavior can be realized by fixing the mistral.yaml as outlined above.

**Log-files**
Please find here a list of log files that illustrate the problem:

- log file of the first year of a simulation that crashes because of a lack of loading the cdo module on mistral, note the various CDO related error messages from line 73191 on:   /work/ba1066/a270061/esm_experiments_v4/test_PI_4xCO2_proper_reinit/scripts/test_PI_4xCO2_proper_reinit_compute_20000101-20001231_24681857.log
- log file of the second year of the simulation above, note the errors around line 1355: /work/ba1066/a270061/esm_experiments_v4/test_PI_4xCO2_proper_reinit/run_20010101-20011231/scripts/test_PI_4xCO2_proper_reinit_compute_20010101-20011231_24684007.log
-check log files of simulation /work/ba1066/a270061/esm_experiments_v4/test_PI_4x_proper_reinit_1, run with a patched mistral.yaml, where the simulation flawlessly progresses also after the first model year

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.2
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.8 (development install, on branch: release, describe=v4.2.8-8-g37897af-dirty)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.6.0

**Additional context**
Does not apply.

**Comment by pgierz** [comment]
closed via #166 (merged by hand)
