### ISSUE TITLE
Explain how plugin system works for esm_runscripts

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#173]
**Request/contribution description**
We should have a page explaining how the plugin system works.

**Suggested chapter/section in the documents**
Under "esm_runscripts" section, we should have a separate page for plugins: where they are loaded from, how to define your own compute recipe for a specific model, usw.

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
Some models e.g. PISM; (@seb-wahl and maybe also GEOMAR models?) deviate from the default compute recipe. 

**Contribution**
I will write something tomorrow.

**Comment by dbarbi** [comment]
moved to trello board
