### ISSUE TITLE
File and information hierarchy

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#176]
**Request/contribution description**
I think we want this to be a short chapter by itself. In my opinion it should contain some graphs. We can create this graphs either as jpg but we could also use https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html
However, learning graphviz might delay us slightly, so we might want to include fast developed jpeg graphs and later on we can move on to graphviz.

Graphs in slides 11 and 12 of this ppt might be useful to get started:
https://onedrive.live.com/edit.aspx?cid=9d02a8e5a472db02&page=view&resid=9D02A8E5A472DB02!1179&parId=9D02A8E5A472DB02!103&app=PowerPoint

**Suggested chapter/section in the documents**
A chapter of its own.

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
ESM-Tools functionality

**Comment by dbarbi** [comment]
moved to trello board
