### ISSUE TITLE
Where to find the logging files

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#177]
**Request/contribution description**
I would write this section in esm_runscripts chapter and inside the cookbook. Details about this files are already included in the experiment directory structure table: https://esm-tools.readthedocs.io/en/latest/esm_runscripts.html#experiment-directory-structure

**Suggested chapter/section in the documents**
esm_runscripts chapter and cookbook

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
General

**Comment by dbarbi** [comment]
moved to trello board
