### ISSUE TITLE
ECHAM defaults documentation

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#178]
**Request/contribution description**
A list of the most important defaults configurations for ECHAM, available configuration sets and scenaries.

Maybe this is the last issue we should address in this project?

**Suggested chapter/section in the documents**
A ECHAM section inside a new chapter for model defaults/description?

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
ECHAM

**Comment by dbarbi** [comment]
moved to trello board
