### ISSUE TITLE
ESM-Tools Variables

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#180]
**Request/contribution description**
Complete the `ESM-Tools Variables` section and maybe make it be a short chapter of its own after the `YAML Syntax` chapter.

https://esm-tools.readthedocs.io/en/latest/yaml.html#esm-tools-variables

**Suggested chapter/section in the documents**
Maybe a chapter of its own?

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
General

**Comment by dbarbi** [comment]
moved to trello board
