### ISSUE TITLE
Running runscripts - Cookbook section

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#182]
**Request/contribution description**
How to run runscripts.

**Subsections**

- [ ] Initial run
- [ ] restart (with the same exp-id)
- [ ] branching off (different exp-id)
- [ ] branching off and redate

**Suggested chapter/section in the documents**
Cookbook

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
General

**Comment by dbarbi** [comment]
moved to trello board
