### ISSUE TITLE
Parallel or serial netCDF on Mistral

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#2]
Hi all

I had a go at running FOCI-1.0 on Mistral and found that NETCDFROOT and HDF5ROOT were pointing to serial libraries and not the parallel libraries. In the old esm-environment they always pointed to the parallel stuff. 
I've changed NETCDFROOT, NETCDFFROOT and HDF5ROOT to the parallel versions now (in branch foci2). 
Was there a good reason why we were not using the parallel libraries? Will some models, e.g. AWI-CM not work with parallel netCDF? 

Cheers
Joakim

**Comment by joakimkjellsson** [comment]
Update: After talking to DKRZ support, I've figured out that the combination we need is:

        - "HDF5ROOT=/sw/rhel6-x64/hdf5/hdf5-1.8.14-parallel-impi-intel14/"
        - "HDF5_ROOT=$HDF5ROOT"
        - "NETCDFROOT=/sw/rhel6-x64/netcdf/netcdf_c-4.3.2-parallel-impi-intel14/"
        - "NETCDFFROOT=/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.2-parallel-impi-intel14/"
        - "GRIBAPIROOT=/sw/rhel6-x64/grib_api/grib_api-1.15.0-intel14/"
        - 'HDF5_C_INCLUDE_DIRECTORIES=$HDF5ROOT/include'
        - "NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include"
        - "NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include"
        - "NETCDF_CXX_INCLUDE_DIRECTORIES=/sw/rhel6-x64/netcdf/netcdf_cxx-4.2.1-gcc48/include"

HDF5_ROOT used to point to version 1.8.16 which caused a conflict warning. I've therefore HDF5_ROOT and HDF5ROOT to be the same.

**Comment by pgierz** [comment]
Hello, I am going through old issues and closing stuff to prepare for version 6. I am going to guess that this is outdated, given that it is over a year old. Joakim, if you need any more discussion for HDF5 stuff, please open a new issue.
