### ISSUE TITLE
select choose block (e.g `useMPI`) in machine yaml not working

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#216]
It is not possible to overwrite variables in a machine yaml (e.g. `useMPI`  in `mistral.yaml`).

**To Reproduce**
use the latest release, open e.g. `config/components/oifs.yaml`, add the line `useMPI: intelmpi17`
```yaml
runtime_environment_changes:
...
...
    mistral:
      useMPI: intelmpi17
      add_export_vars:
```
(also tried `computer.useMPI`) and do
```bash
cd runscripts/oifs/
# adjust paths in `oifs-43r3-tco95-amip-mistral-initial-daily_SW.yaml` 
esm_runscripts -e bugtest1 oifs-43r3-tco95-amip-mistral-initial-daily_SW.yaml -c
vim /pf/b/b350071/esm-tools-latest/esm-experiments/bugtest1/run_20080101-20080101/scripts/*.sad
```
You will see that still intel18 is used. If I comment `useMPI` in `mistral.yaml` I get a key error when I try to run `esm_runscripts -e bugtest1 oifs-43r3-tco95-amip-mistral-initial-daily_SW.yaml -c`. The same happens for compiletime environment changes.

**Expected behavior**
I would expect that I can overwrite the `useMPI` statement from a runscript or component configuration.

**Screenshots**

**System (please complete the following information):**
 - Supercomputer: tested on mistral, but I got the same when doing similar things on my `feature/focioifs` branch on blogin.
 - Latest versions of all other components.

**Comment by mandresm** [comment]
This could potentially be solved by the `add_` changes I merged this morning. I'll check in an hour.

**Comment by seb-wahl** [comment]
Did you test whether this works now?

**Comment by mandresm** [comment]
I'm going to test it now.

**Comment by mandresm** [comment]
I confirm this is still a problem, I working already in the solution so I assign this issue to myself.

**Comment by seb-wahl** [comment]
Together with the issue that @nwieters reported (https://github.com/esm-tools/esm_tools/issues/232) I think a general cleanup of the interplay between the `slurm.yaml` and the machine.yaml's could help. I'm always lost if I try to modify the `SBATCH` header of the `.sad` runscript. Thank you @mandresm for having a go at this.
