### ISSUE TITLE
verbose.log in runscript folder

### ISSUE THREAD

**Issue by dbarbi** [esm-tools/esm_tools#242]
**Describe the bug**
Sometimes after a run a file called verbose.log ends up in the original runscripts folder

**System (please complete the following information):**
 - Supercomputer: mistral (doesn't matter I think)
 - Version 5.x

**Comment by mandresm** [comment]
I can confirm that the system does not matter. I just reproduced it in ollie. Already working on it.

**Comment by pgierz** [comment]
Miguel, it might be enough to tell this `logger.sink` command (or `set_sink`, I can't remember) where to write it's file. If the log folder is known at that point, then we can use that, alternatively, we can add the `verbose.log` file to part of the files that are cleaned up. As far as I understand, the cleanup job can also operate on files outside of the experiment tree.
