### ISSUE TITLE
Problem starting my experiment on awiesm.

### ISSUE THREAD

**Issue by StanleyAgu1** [esm-tools/esm_tools#246]
I am starting my first experiment on awiesm version using mistral, but I keep getting a lot of these errors;

`291: /mnt/lustre02/work/ab0246/a270162/esm-experiments/stanleymistral4/work/./echam6: error while loading shared libraries: libpnetcdf.so: cannot open shared object file: No such file or directory
 293: /mnt/lustre02/work/ab0246/a270162/esm-experiments/stanleymistral4/work/./echam6: error while loading shared libraries: libpnetcdf.so: cannot open shared object file: No such file or directory
 301: /mnt/lustre02/work/ab0246/a270162/esm-experiments/stanleymistral4/work/./echam6: error while loading shared libraries: libpnetcdf.so: cannot open shared object file: No such file or directory
`
I don’t know what the problem is.

<img width="1440" alt="Screenshot 2020-12-10 at 16 19 06" src="https://user-images.githubusercontent.com/73535862/101791218-91ae6c00-3b03-11eb-8a68-22fde94a1b3b.png">
 
I have uploaded a screenshot to help explain more.

**Comment by pgierz** [comment]
That looks like a `LD_LIBRARY_PATH` issue. To help use debug, could you please post the output of:

```
esm_versions check
```

as well as the `module load` commands at the top of your `.sad` file? That might give us a hint.

To clarify, which ECHAM version are you using?

**Comment by pgierz** [comment]
Also note: from the output, this looks like the shell version of esm-tools

**Comment by denizural** [comment]
Hi Stanley, 
could you please post your runscript here. Then I can help you to migrate that to the new version of ESM-Tools

**Comment by JanStreffing** [comment]
Old issue about specific runs that crashed. Likely not relevant to esm_tools development anymore. Closing here.
