### ISSUE TITLE
Error while installing awicm-2.0

### ISSUE THREAD

**Issue by StanleyAgu1** [esm-tools/esm_tools#249]
While Installing esm_master install-awicm-2.0, I got the following error message. I don’t know what is going on here

`a270162@mlogin100% esm_master install-awicm-2.0
Traceback (most recent call last):
  File "/pf/a/a270162/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270162/.local/lib/python3.6/site-packages/esm_master/cli.py", line 75, in main
    from .esm_master import main_flow
  File "/pf/a/a270162/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 9, in <module>
    from .general_stuff import (
  File "/pf/a/a270162/.local/lib/python3.6/site-packages/esm_master/general_stuff.py", line 1, in <module>
    import esm_tools
ModuleNotFoundError: No module named 'esm_tools'`

**Comment by pgierz** [comment]
It looks like your install is broken. Can you try updating everything to the latest version?

```
$ esm_versions check
$ esm_versions upgrade
```

If that doesn't work, you can erase your files by hand and make a new install. There is a uninstall section in the handbook: https://esm-tools.readthedocs.io/en/latest/installation.html#uninstall-esm-tools

**Comment by dbarbi** [comment]
please type
`git diff`
in your esm_tools folder and post the result, or send it to me via email

**Comment by StanleyAgu1** [comment]
> please type
> `git diff`
> in your esm_tools folder and post the result, or send it to me via email

Hi @dbarbi, this is the output I got 

`a270162@mlogin104% git diff
diff --git a/esm_tools/__init__.py b/esm_tools/__init__.py
deleted file mode 100644
index 5368e0d..0000000
--- a/esm_tools/__init__.py
+++ /dev/null
@@ -1,234 +0,0 @@
-"""
-=================================
-ESM Tools (Package Documentation)
-=================================
-
-This package contains almost no code, but instead is where most of the YAML
-configurations files are distributed. Default namelists are included as well as
-example runscripts. This section **only** documents the code contained in the
-module, please refer to the handbook for user documentation as well as API
-documentation for the various sub-modules of the project.
-
-Accessing Configuration
------------------------
-
-To access a particular configuration, you can use::
-
-    >>> ollie_config = read_config_file("machines/ollie")
-
-Important note here is that the configuration file **has not yet been parsed**,
-so it's just the dictionary representation of the YAML.
-"""
-
-__author__ = """Dirk Barbi, Paul Gierz"""
-__email__ = "dirk.barbi@awi.de"
-__version__ = "5.0.2"
-
-import os
-import shutil
-import sys
-
-import pkg_resources
-import yaml
-
-
-def _get_namelist_filepath_standard_install(namelist):
-    return pkg_resources.resource_filename("esm_tools.namelists", namelist)
-
-def _get_namelist_filepath_editable_install(namelist):
-    return pkg_resources.resource_filename("namelists", namelist)
-
-def _get_config_filepath_standard_install(config):
-    return pkg_resources.resource_filename("esm_tools.configs", config)
-
-def _get_config_filepath_editable_install(config):
-    return pkg_resources.resource_filename("configs", config)
-
-
-def get_config_as_str(config):
-    return pkg_resources.resource_string("esm_tools.configs", config)
:
`

**Comment by StanleyAgu1** [comment]
> It looks like your install is broken. Can you try updating everything to the latest version?
> 
> ```
> $ esm_versions check
> $ esm_versions upgrade
> ```
> 
> If that doesn't work, you can erase your files by hand and make a new install. There is a uninstall section in the handbook: https://esm-tools.readthedocs.io/en/latest/installation.html#uninstall-esm-tools

Hi @pgierz, 

` $ esm_versions check
 $ esm_versions upgrade`

both return the output 

`command not found`
