### ISSUE TITLE
Can not add a model in include_models that has a '-' in the name

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#25]
Maybe this issue is related to issue #4 ?

**Comment by nwieters** [comment]
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.0
esm_database : 4.0.0
esm_environment : 4.0.0
esm_master : 4.0.0
esm_parser : 4.0.0
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.0.2
esm_tools : version="4.0.1"
esm_plugin_manager : 4.0.0
esm_version_checker : 4.0.0

**Comment by nwieters** [comment]
For example:
If I add 'esm-interface' in the groug 'include_models' in the awicm-2.0.yaml file it will search for a model 'esm'.

**Comment by dbarbi** [comment]
ja... it assumes the "-" separated model from version number. try to avoid the "-"

**Comment by nwieters** [comment]
what a pity. ok, thanks. Then I need to change the esm-interface config folder
