### ISSUE TITLE
namelists not copied

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#255]
**Describe the bug**
`esm_runscripts` is not copying namelists to the `work` directory if their name do not start with `namelist` string. I found that while implementing MPIESM, where MPIOM namelists are named `OCECTL` and `NAMELIST_BGC`. If I rename these namelists to include `namelist` at the beginning (i.e. `namelist.ocectl` or `namelist.bgc`) then they are copied correctly. I would expect the same behaviour for any other model that has namelists which name do not start with `namelist` (i.e. `fort.4` in `OIFS`, @seb-wahl and @joakimkjellsson , have you experienced something similar?).

Here is the error:
```
report_missing_files
--------------------
================================================================================
MISSING FILES:
--  /work/ollie/mandresm/esm_yaml_test/test_mpiesm/run_20000101-20001231/input/jsbach/lctlib.def: 
        --> /home/ollie/mandresm/model_codes/mpiesm-1.2.01p1/lctlib_nlct21.def
--  /work/ollie/mandresm/esm_yaml_test/test_mpiesm/run_20000101-20001231/config/mpiom/OCECTL: 
        --> NONE_YET/mpiom/1.6.3p2/OCECTL
--  /work/ollie/mandresm/esm_yaml_test/test_mpiesm/run_20000101-20001231/config/mpiom/NAMELIST_BGC: 
        --> NONE_YET/mpiom/1.6.3p2/NAMELIST_BGC
```

**To Reproduce**
In theory, running any model which namelist name does not start with `namelist`.

**Expected behavior**
Namelists are copied independently of their name.

**System (please complete the following information):**
 - Supercomputer: ollie, but expected in all the systems
 - Version [Please run `esm_versions check`]
 ```
 +---------------------+-----------+---------------------------------------------------------+-------------------------------+-------------------------+
| package_name        | version   | file                                                    | branch                        | tags                    |
|---------------------+-----------+---------------------------------------------------------+-------------------------------+-------------------------|
| esm_calendar        | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_database        | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_environment     | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_master          | 5.0.1     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_motd            | 5.0.1     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_parser          | 5.0.2     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_plugin_manager  | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_profile         | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_rcfile          | 5.0.0     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
| esm_runscripts      | 5.0.5     | /home/ollie/mandresm/esm_runscripts                     | hotfix/trace_log_into_log_dir | v5.0.5-2-gee7aa56       |
| esm_tools           | 5.0.3     | /home/ollie/mandresm/esm_tools                          | feature/mpiesm                | v5.0.3-4-g6f687d1-dirty |
| esm_version_checker | 5.1.1     | /home/ollie/mandresm/.local/lib/python3.7/site-packages |                               |                         |
+---------------------+-----------+---------------------------------------------------------+-------------------------------+-------------------------+
 ```

**Additional context**
I think the problem is in this lines of the `filelists.py` in `esm_runscripts`:
https://github.com/esm-tools/esm_runscripts/blob/99e9a4b70ca86ba4406aea1f7631419081c25f9d/esm_runscripts/filelists.py#L557-L563

**Comment by mandresm** [comment]
I'm already working on a solution

**Comment by seb-wahl** [comment]
Now I understand why Joakim put at some point:
```yaml
config_sources:
        "fort.4": "${namelist_dir}/pictl/fort.4"
```
into `oifs.yaml`.

**Comment by mandresm** [comment]
That `config_sources` is there to copy the file, and is the same syntax I am using currently for MPIOM. I think the problem is with the file itself not being `namelist.fort.4`. I wonder if with the current configuration and the latest version `esm_runscripts`, it still copies the `fort.4` correctly.

**Comment by seb-wahl** [comment]
Yes it does if you have `~/.esmtoolsrc`, because in this case `${namelist_dir}` is defined, and the file can be found. I discovered this just during the last days, when I tried a clean install without a `NAMELIST_PATH=...` entry in `~/.esmtoolsrc`.

**Comment by joakimkjellsson** [comment]
Always thought it was weird that namelists had to be put under “config” files. ;-) 
Well, I’ve never had a problem of missing namelists, and I do not want to rename namelists since it would require some changes in the OpenIFS source code. 

Cheers
Joakim

**Comment by seb-wahl** [comment]
> Always thought it was weird that namelists had to be put under “config” files. ;-) Well, I’ve never had a problem of missing namelists, and I do not want to rename namelists since it would require some changes in the OpenIFS source code. Cheers Joakim
> […](#)

No the tools will be updated in a way that namelists can have arbitrary names.
