### ISSUE TITLE
OpenIFS nproc vs nproca*nprocb

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#291]
In the oifs.yaml we currently set:
https://github.com/esm-tools/esm_tools/blob/d84b6a2a16a05800a6fefee0ec11894042c8be6e/configs/components/oifs/oifs.yaml#L524-L535
This implies that we manually set MPI grid decomposition of `NGPTOTG` into `NPROCA*NPROCB`. In reality we use `NPROCA` as if it were `NPROC` and we leave it up to OpenIFS to calculate a good grid decomposition once the simulation starts. I have never seen anyone make use of `NPROCA*NPROCB`, and I think OpenIFS is likely making better choices automatically than most users could manually. I suggest we remove this an leave only `NPROC`. This would make life easier for when I implement `NPROC*OMP_NUM_PROC` into the slurm hostfile generation.

**Comment by joakimkjellsson** [comment]
Agreed! It's only like this because I copied the echam.yaml file...
Cheers
Joakim

**Comment by JanStreffing** [comment]
Perfect, I'll get to it.
@mandresm What branch to I best branch off of and make a pull request for?

**Comment by mandresm** [comment]
I would recommend to do that in the `geomar_awicm3` branch.

**Comment by JanStreffing** [comment]
Thank you!

**Comment by JanStreffing** [comment]
I did not touch `nproca*nprocb` for nemo. I saw that in the components yaml it uses `nproca*nprocb,` but in some of the runscript yaml files the nemo section acutually had `nproc`. I believe this `nproc` will be ignored and the default values will be used. 
Just a head up!

**Comment by joakimkjellsson** [comment]
Good. The nproca and nprocb are important for NEMO. There is a lot of work that goes into finding the optimal settings for a given resolution on a given machine.

**Comment by JanStreffing** [comment]
I think this was merged into the relevant branches that will eventually be merged into release. I'll close this here.
