### ISSUE TITLE
Migrate to Readthedocs

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#3]
List of projects that need to be migrated to readthedocs:

+ [x] `esm_calendar`
+ [x] `esm_archiving`
+ [x] `esm_tools`
+ [x] `esm_master`
+ [x] `esm_runscripts`
+ [x] `esm_parser`
+ [x] `esm_version_checker` (No documentation provided)
+ [x] `esm_profile`
+ [x] `esm_rcfile`
+ [x] `esm_environment`

**Comment by pgierz** [comment]
Example of how the new documentation will look (for the main project): https://esm-tools.readthedocs.io/en/docs/

**Comment by seb-wahl** [comment]
This first draft looks brilliant, and already has a lot of information I was missing in the past. How can we contribute e.g. to the FAQ? I haven't used readthedocs so far, so I appreciate help to get started.

**Comment by pgierz** [comment]
You need to do a "development install" and then push commits, which @MiguelAndresMartinez is writing how to do. Until that is in the done, here is what to do:

1. `git clone https://github.com/esm-tools/<REPO_YOU_WANT>`
2. Most of the projects have a subfolder called `docs`, where you can change the prose documentation. In-code documentation will soon follow for some of the projects. Examples of how that is done can be seen in `esm_archiving`, basically we just include the module doc-string. That's fine for some modules, but for the main repository esm_tools, we still have quite a bit of prose documentation... 

Right now, the branch `docs` is served on read the docs, I'll merge it into release on Friday.

In future, contributing the documentation should work as follows:

1. Clone your project
2. Make a new branch
3. Add comments, docstrings, prose documentation, whatever
4. Submit a pull request
5. One of the maintainers will merge it into release, where it will then show up in the main documentation.

As a bonus, note that you can also download a PDF if you click the little button on the bottom.
