### ISSUE TITLE
Using module that is not the default

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#313]
Compiling XIOS requires `netcdf_par.h` to be available within the netcdf library. Our default `netcdf/4.6.2_intel` on ollie does not have parallel netcdf / `netcdf_par.h`, however the older module `netcdf/4.4.1.1_intel_mpi` does. Is there a nicer solution than just append a `module unload netcdf; module load netcdf/4.4.1.1_intel_mpi` to the end of the list of module commands as it's done for ICON? Seems weird to always load the wrong module first, then unload it and replace it with the right one.

**Comment by mandresm** [comment]
Hi @JanStreffing, at the moment there is not such a feature. The improvements on the environment behavior happen mainly in the `export_vars`. This could be easily extended to module_actions, but I would need to work on that.

**Comment by JanStreffing** [comment]
Ok not a big deal. We can keep this open as a wishlist issue. I will go ahead and load -> unload -> load for now.

**Comment by JanStreffing** [comment]
We no longer use HPC admin installed netcdf libraries. Instead I install things quickly with: https://github.com/aWI-CM3/install_libs

Closing here.
