### ISSUE TITLE
Add module load gcc to mistral.yaml?

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#316]
Hey everyone.

The latest FESOM2 code contains a lot more c code than before, courtesy of Jan Hegewalds threaded parallel IO. As a results FESOM2 does not compile with the default mistral gcc anymore. 

Would it be save to add a load gcc to mistral.yaml? Or do you think this has to go into the fesom-2.0.yaml? It seems kinda reasonable to me to load a relatively modern version of gcc by default on every platform we work on.

**Comment by JanStreffing** [comment]
The only setup that I'm not sure if it likes this change would be AWI-ESM.

**Comment by seb-wahl** [comment]
As far as I know all the C code that is in FOCI (e.g. CDI lib, the complete XIOS code) is compiled with icc (the intel c compiler) that comes with the Intel module. If that still works and if we don't get module conflicts, I'm fine with the change. On the other hand we most likely won't run FOCI in ESM-Tools on mistral operationally before it's shutdown by the end of the year.

**Comment by JanStreffing** [comment]
After a bit of testing i can say that gcc/7.1.0 did work for FESOM2, but not for OpenIFS. I settled on gcc/4.8.2, the one that is also used in the native FESOM2 env.

**Comment by JanStreffing** [comment]
Mistral is on the way out and no new projects are starting on it anymore. Likely not relevant anymore. Closing here.
