### ISSUE TITLE
Fesomstandalone error message.

### ISSUE THREAD

**Issue by dchari** [esm-tools/esm_tools#330]
I made a fresh installation of the esm_tools and I ran a fesomstandalone simulation but ended up with the error below...

'''
Traceback (most recent call last):
  File "/pf/a/a270151/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270151/esm_runscripts/esm_runscripts/cli.py", line 199, in main
    Setup = SimulationSetup(command_line_config)
 File "/mnt/lustre01/pf/a/a270151/esm_runscripts/esm_runscripts/sim_objects.py", line 31, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/mnt/lustre01/pf/a/a270151/esm_runscripts/esm_runscripts/sim_objects.py", line 153, in get_total_config_from_user_config
    self.config = self.add_esm_runscripts_defaults_to_config(self.config)
  File "/mnt/lustre01/pf/a/a270151/esm_runscripts/esm_runscripts/sim_objects.py", line 169, in add_esm_runscripts_defaults_to_config
    FUNCTION_PATH = esm_rcfile.EsmToolsDir("FUNCTION_PATH")
AttributeError: module 'esm_rcfile' has no attribute 'EsmToolsDir'
'''

These are my ems_versions,
'''
esm_tools: 5.1.0 file: /mnt/lustre01/pf/a/a270151/esm_tools/esm_tools/__init__.py (development install, on branch: release, describe=v5.1.0-dirty)
esm_rcfile: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_rcfile/__init__.py
esm_runscripts: 5.1.7 file: /mnt/lustre01/pf/a/a270151/esm_runscripts/esm_runscripts/__init__.py (development install, on branch: release, describe=v5.1.7-1-g20b21a1)
esm_environment: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_environment/__init__.py
esm_master: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_master/__init__.py
esm_parser: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_parser/__init__.py
esm_calendar: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_calendar/__init__.py
esm_version_checker: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_version_checker/__init__.py
esm_archiving : unknown version!
esm_profile: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_profile/__init__.py
esm_database: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_database/__init__.py
esm_plugin_manager: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_plugin_manager/__init__.py
esm_motd: 5.0.0 file: /pf/a/a270151/.local/lib/python3.6/site-packages/esm_motd/__init__.py
esm_utilities : unknown version!
esm_cleanup : unknown version!
'''

**Comment by denizural** [comment]
Hi @dchari,

Sorry for the late response. I would say that this is a small bug in our system, that I also met previously. Could you please delete (or better `mv`) the file `.esmtoolsrc`. Eg. `mv .esmtoolsrc __esmtoolsrc`

Things have changed since the previous versions and the contents of the `.esmtoolrc` need to be refreshed. It seems like the default uninstall process does not remove the `.esmtoolsrc` file, and therefore, when the users who previously had version 4 make a new installation `esm_master` runs into this problem. 

What do you think @mandresm? I previously solved this issue manually by removing the `.esmtoolsrc` by hand. I can also implement that to the uninstall script.

**Comment by mandresm** [comment]
Hi @dchari

The problem is that you don't have the most up to date `esm_rcfile` package. Please, follow this steps:

1. `esm_versions clean`
2. `rm ~/.local/lib/python3.<your_version>/site-packages/esm*`
3. Install ESM-Tools again

**Comment by mandresm** [comment]
I think this issue is solved, if not please open it again :)
