### ISSUE TITLE
experiment ID (expid) cannot be defined in the runscript

### ISSUE THREAD

**Issue by mathanase** [esm-tools/esm_tools#331]
The documentation (User Manual, section 8.1.2.) describes the possibility of defining the experiment ID directly in the runscript, as:

>general
>        expid: "experiment_name"

instead of using the -e flag when calling esm_runscripts.

However, when doing so, my experiment ID is not recognized and the experiment folder is automatically named "test" as a default. 

It would make sense to implement this feature to avoid using the -e flag, or to remove this from the documentation.

Note: I am currently using the fix/venv_editable_install branch for esm_runscripts.

Thanks!

**Comment by pgierz** [comment]
Hi @mathanase,

I was taking care of the venv stuff. That should definitely be in release by now, so I could try upgrading and seeing if the problem persists.

**Comment by JanStreffing** [comment]
Sounds like this issue was solved a long time ago. Closing here.
