### ISSUE TITLE
Problem branching off a parent experiment

### ISSUE THREAD

**Issue by mathanase** [esm-tools/esm_tools#333]
Hi,

I have been trying to take advantage of the **ini_parent_exp_id** and **ini_restart_dir** variables to submit an experiment that branches off a short awicm3 spin-up run.

I followed instructions in section 15.2 of the ESM tools documentation (see "Branching off: An experiment that restarts from a previous experiment but with a different experiment id"). I thus defined **ini_parent_exp_id** and **ini_restart_dir** in my runscript and set all **lresume** variables to true (in general, oifs, fesom, and oasis).

However, I get the following message when trying to submit my job with **esm_runscript** :
 
> Traceback (most recent call last):
>   File "/pf/a/a270170/.local/bin/esm_runscripts", line 11, in <module>
>     load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
>   File "/mnt/lustre01/pf/a/a270170/esm_runscripts/esm_runscripts/cli.py", line 199, in main
>     Setup = SimulationSetup(command_line_config)
>   File "/mnt/lustre01/pf/a/a270170/esm_runscripts/esm_runscripts/sim_objects.py", line 42, in __init__
>     self.config = prepare.run_job(self.config)
>   File "/mnt/lustre01/pf/a/a270170/esm_runscripts/esm_runscripts/prepare.py", line 6, in run_job
>     helpers.evaluate(config, "prepare", "prepare_recipe")
>   File "/mnt/lustre01/pf/a/a270170/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
>     framework_recipe, framework_plugins, config
>   File "/pf/a/a270170/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
>     config = getattr(submodule, workitem)(config)
>   File "/mnt/lustre01/pf/a/a270170/esm_runscripts/esm_runscripts/prepare.py", line 616, in set_parent_info
>     config[model]["parent_date"] = config[model]["ini_parent_date"]
> KeyError: 'ini_parent_date'
>  

I do not quite get what the issue is with ' **ini_parent_date** ', and did not find information on the **ini_parent_date** variable in the documentation (only found **parent_date** or **parent_start_date**, which did not seem to be needed here).

Note: I am currently using the **fix/venv_editable_install** branch for **esm_runscripts** and the branch **feature/awicm3** for **esm_tools.**

 Am I missing something here? Or is this a branch/version issue? 

Many thanks in advance

**Comment by mandresm** [comment]
Hi Marylou,

You are absolutely right, the `ini_parent_date` variable needs to be also defined, if it is missing ESM-Tools will complain about it. There are two things missing here: a clearer error message and including the `ini_parent_date` into the documentation and cookbooks, sorry about that, I'll work on both at the endo of the week.

Please, let me know if including `ini_parent_date` does the job for you.

**Comment by mathanase** [comment]
Thanks, Miguel. 

Adding `ini_parent_date` removed the initial error but then I got a similar error for a `ini_parent_dir` variable:

> KeyError: 'ini_parent_dir'

After adding `ini_parent_date` and `ini_parent_dir` as follows:

> lresume: true
>     ini_parent_exp_id: "awicm3_TL159L60_spinup_01"
>     ini_restart_dir: "/work/ba1138/a270170/06_WORK/awicm-3.1/awicm3_TL159L60_spinup_01/restart/"
>     ini_parent_date: "2016-12-31"
>     ini_parent_dir: "/work/ba1138/a270170/06_WORK/awicm-3.1/awicm3_TL159L60_spinup_01/"

my job was successfully submitted. I hope I got the architecture right, but thanks!

**Comment by JanStreffing** [comment]
Sound like this issue was solved. Better error handling is still high on the priority list.
