### ISSUE TITLE
fesom2 warning namelist.diag somepath pool data not found 

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#335]
Hi

**Describe the bug**
Running
```
cd ~/esm/runscripts
esm_runscripts fesom2-mistral-initial-monthly.yaml -e test -c
```
yields the warnings
```
WARNING: File not found: /mnt/lustre01/pf/a/a270073/esm/esm_tools/namelists/fesom2/namelist.diag
WARNING: File not found: /work/ab0246/a270073/out/fesom-2.0/test/run_20010101-20010131/config/fesom/namelist.diag
MISSING FILES:

- missing source: /mnt/lustre01/pf/a/a270073/esm/esm_tools/namelists/fesom2/namelist.diag
- missing target: /work/ab0246/a270073/out/fesom-2.0/test/run_20010101-20010131/config/fesom/namelist.diag

- missing source: /work/ab0246/a270073/out/fesom-2.0/test/run_20010101-20010131/config/fesom/namelist.diag
- missing target: /work/ab0246/a270073/out/fesom-2.0/test/run_20010101-20010131/work/namelist.diag

- missing source: somepath
- missing target: opbndpath (from namelist.config in FESOM)

- missing source: /pool/data/AWICM/FESOM2/hydrography/
- missing target: climatedatapath (from namelist.config in FESOM)

- missing source: /pool/data/AWICM/FESOM2/forcing/
- missing target: forcingdatapath (from namelist.config in FESOM)

- missing source: somepath
- missing target: tideforcingpath (from namelist.config in FESOM)
```

**To Reproduce**
```
cd ~/esm/runscripts
esm_runscripts fesom2-mistral-initial-monthly.yaml -e test -c
```

**Expected behavior**
No warnings.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version

| package_name        | version   | file                                                          | branch   | tags   |
|---------------------|-----------|---------------------------------------------------------------|----------|--------|
| esm_analysis        | 0.3.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_archiving       | 0.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_environment     | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_master          | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_parser          | 5.1.2     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_runscripts      | 5.1.9     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |
| esm_tools           | 5.1.0     | /mnt/lustre01/pf/a/a270073/esm/esm_tools                      | release  | v5.1.0 |
| esm_version_checker | 5.1.3     | /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages |          |        |

**Comment by mandresm** [comment]
Hi @chrisdane , it should be solved now if you pull from `esm_tools`.

**Comment by chrisdane** [comment]
Yes that works, thanks Miguel!
