### ISSUE TITLE
fesom2 hydrography phc3.0_winter.nc missing on mistral

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#339]
**Describe the bug**
Running a default fesom2 initial experiment on mistral with `pool_dir: "/pool/data/AWICM/FESOM2/"` in the runscript results in the missing file error `/pool/data/AWICM/FESOM2/hydrography/phc3.0_winter.nc`.

**To Reproduce**
Run default fesom2 initial experiment on mistral.

**Expected behavior**
Fesom2 initial run should find initial data.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]

esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 0.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.9
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_tools
├─ version: 5.1.1
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: release
└─ tags: v5.1.1-1-g64f6ca0

esm_version_checker
├─ version: 5.1.3
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags:

**Comment by pgierz** [comment]
That's a pool issue, and has been an ongoing discussion for at least 3 years. Someone really needs to put the hat one and fix the pools at some point.

For now, you can download a set of "nonstandard pool files". Have a look here: https://gitlab.awi.de/paleodyn/boundary-conditions/nonstandard_pool_files

**Comment by JanStreffing** [comment]
A workaround was provided. Solving the original issue is down to the pool maintainer. This used to be Thomas Rackow, but went to ECMWF. I'm unsure who is responsible now. But I think this is an internal discussion not for this forum. Closing here.
