### ISSUE TITLE
trailing slash path ambiguity

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#340]
**Describe the bug**
Using `mesh_dir: "/pool/data/AWICM/FESOM2/MESHES/CORE2/` in the runscript works, but using `mesh_dir: "/pool/data/AWICM/FESOM2/MESHES/CORE2` does not work since the trailing slash is missing for paths constructed based on `mesh_dir`.

**To Reproduce**
Run a default fesom2 experiment with `mesh_dir: "/pool/data/AWICM/FESOM2/MESHES/CORE2/` (works) and with `mesh_dir: "/pool/data/AWICM/FESOM2/MESHES/CORE2` (does not work).

**Expected behavior**
In my view, esm-tools should be clever enough to check all user-provided paths if they are ok. If not, the esm-tools should fix the provided paths so that everything works (e.g. adding a trailing slash internally).

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]

esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 0.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.9
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_tools
├─ version: 5.1.1
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: release
└─ tags: v5.1.1-1-g64f6ca0

esm_version_checker
├─ version: 5.1.3
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags:

**Comment by pgierz** [comment]
ESM tools already checks if all paths that you provide exist. We even check if the paths needed by namelists exist (that wasn't a feature in the vintage shell version). 

What we could do is put all paths through either `pathlib.Path` or `os.normpath`.  In either case that removes all trailing slashes and any double slashes. As an example:

```python
import os
import pathlib

black_hole = "/dev////null//"

print(os.path.normpath(black_hole))
print(pathlib.Path(black_hole))

bad_path = "/this/isnt/real"
print(os.path.normpath(bad_path))
print(pathlib.Path(bad_path))
```
Response:
```
/dev/null
/dev/null

/this/isnt/real
/this/isnt/real
```

@koldunovn, thoughts from the FESOM people?

**Comment by denizural** [comment]
Hi @chrisdane and @pgierz,

I saw this error quite some time ago and decided to refactor all path constructions in esm tools by the `Pathlib` module. Then I realized that this process could be quite error prone and tedious. It is still in my TODO list and I think we can add that later on when the tools become much more stable.

@chrisdane is right and your example actually proves that @pgierz. If you omit the trailing path separator `/`  then esm-tools passes that path to the Fesom executable and Fesom then concatenates the mesh file name to that. This yields something like
`/pool/data/AWICM/FESOM2/MESHES/CORE2fesom_mesh_file`. Obviously, the missing `/` between `CORE2` and `fesom_mesh_file` crashes the Fesom run.

My quick & dirty solution is adding a trailing `/` to all paths in the Yaml files since an extra `/` (eg. `path//foo.txt`) does not cause any issues but omitting does (eg. `pathfoo.txt`). I also met similar issues in the `inspect` feature of `esm_runscripts`

**Comment by koldunovn** [comment]
Yes, the error @denizural describes is quite common and annoying, you should always have final slash in FESOM paths. Fixing this is in FESOM on my list (low priority however :)), but for the time being it would be nice if `esm_tools` can handle that automatically.

**Comment by pgierz** [comment]
Maybe another candidate for the long awaited and never programmed "sanity check" plugin 😉 

together with: is my JSBACH input file designed for dynveg or not, the ECHAM nproca/nprocb circus, and the first/last restart problem in ECHAM.

**Comment by JanStreffing** [comment]
I think the sanity check feature is working mainly at runtime, catching errors from the logfile. While the feature described here would be nice, it does not have high priority, as a fix on the user side is rather simple. (add the trailing slash). It also seems that there is a willingness to solve this on the FESOM side. I suggest to add it to https://github.com/FESOM/fesom2/projects/7

Closing here, as implementation in esm_tools seems unlikely. Please open again if anyone does decide to work on this feature afterall.
