### ISSUE TITLE
error message in the namelist.echam

### ISSUE THREAD

**Issue by akil-hossain** [esm-tools/esm_tools#346]
Hi there,

After going back to before Conc-Rad version of ECHAM and running esm_versions upgrade (to 5.1.4), I can not run any AWIESM experiment. It shows an error message in the namelist.echam (nprocar/nprocbr) -

`forrtl: severe (19): invalid reference to variable in NAMELIST input, unit 100, file /work/ollie/ahossain/micoene/experiments/MIO_oro_boot_wcr/run_20100101-20101231/work/namelist.echam, line 25, position 13`

Although I have removed nprocar/nprocbr in namelist changes by using “remove from namelist”, it is still in the namelist.echam and gives the same error message.

Can you please help me to figure out the problem?

My experiment directory - `/work/ollie/ahossain/micoene/experiments/MIO_boot_w1/`

esm_versions check:
```
+---------------------+-----------+---------------------------------------------------------+----------+-------------------------+
| package_name        | version   | file                                                    | branch   | tags                    |
|---------------------+-----------+---------------------------------------------------------+----------+-------------------------|
| esm_calendar        | 5.0.0     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_database        | 5.0.0     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_environment     | 5.1.0     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_master          | 5.1.1     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_motd            | 5.0.2     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_parser          | 5.1.5     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_plugin_manager  | 5.0.1     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_profile         | 5.0.0     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_rcfile          | 5.1.0     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_runscripts      | 5.1.11    | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
| esm_tools           | 5.1.2     | /work/ollie/ahossain/esm_tools                          | release  | v5.1.1-3-g3418bb0-dirty |
| esm_version_checker | 5.1.4     | /home/ollie/ahossain/.local/lib/python3.7/site-packages |          |                         |
+---------------------+-----------+---------------------------------------------------------+----------+-------------------------+
```

Best Regards
Akil
<img width="1336" alt="Screenshot 2021-05-25 at 12 39 28" src="https://user-images.githubusercontent.com/84776506/119484789-a8194e80-bd56-11eb-93c1-67e826b9a180.png">

**Comment by pgierz** [comment]
Hey Akil,

just so it's documented here as well, try the following in your YAML:

```yaml
echam:
    nprocar: "remove_from_namelist"
    nprocbr: "remove_from_namelist"
```

That *should* get rid of the entries.

**Comment by akil-hossain** [comment]
Hi there,

echam namelist error has gone but a new error is appeared -

`FATAL ERROR in init_lctlib: Error opening landcover library file   FINISH called from PE: 0`

**Comment by dbarbi** [comment]
Hi, that was a missing file in the echam repository. I added lctlib_nlct21.def now, please use "git pull" in the echam dir to get it.

**Comment by akil-hossain** [comment]
Hi Dirk,


Thanks a lot. There occur another error -


FATAL ERROR in mo_hydrology: set_riverflow_timestep:  The hydrology model should be called at least once a day. hd_calling_interval =        86850  seconds.
FINISH called from PE: 0

Please check out the attached yaml file.


Regards

Akil


________________________________

**Comment by dbarbi** [comment]
There is no attached file
can you please provide a path to your experiment?

**Comment by akil-hossain** [comment]
`/work/ollie/ahossain/micoene/experiments/MIO_boot_w`

**Comment by dbarbi** [comment]
So far I can't see anything unusual. The error message means that the puthd and gethd timesteps are not in sync with the dt_resume time of day, but all them seem to be the default. I am suspecting something off with one of the echam restart files, and will check now in more detail.
