### ISSUE TITLE
esm_master options in alphabetical order

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#356]
**Is your feature request related to a problem? Please describe.**
It would help if the output of `esm_master`, i.e. all available options, are printed in alphabetical order.

**Describe the solution you'd like**
Print alphabetically within the respective sections (setups, components, ...).

Thanks,  
Chris

**Comment by denizural** [comment]
I think you are reading my mind @chrisdane since I was currently working on that. Otherwise, if you are spying my computer, then it is not polite 😄

**Comment by chrisdane** [comment]
you never know :>

Thanks for working on this!

**Comment by pgierz** [comment]
There's also tab completion for esm-master. You need to teach it to your shell, though. Have a look at the README

**Comment by mandresm** [comment]
I think this issue is now solved and merged to `develop`. It will make it to release 6.0. Is that right @denizural ? If that's the case then we can close it.

**Comment by denizural** [comment]
@mandresm, Yes, actually it was in my TODO list. I placed it after the release of v6.0 to close it. But I can also do it now since I already showed the new interface to Christopher.
