### ISSUE TITLE
recompile fesom+recom only in coupled awicm setup

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#357]
**Is your feature request related to a problem? Please describe.**
When making a change in the recom code, both recom and fesom need to get recompiled. I am missing a `esm_master recomp-`-command that only recompiles these two models if they are coupled to echam via oasis (i.e. some kind of awicm-setup). Currently I use the setup `awicm-1.0-recom` and I would need to run `esm_master recomp-awicm-1.0-recom` to recompile everything which takes very long (~20 min).

**Describe the solution you'd like**
`esm_master recomp-fesom-recom-1.4-only` or similar to only recompile fesom and recom which takes only a few minutes.

**Describe alternatives you've considered**
`esm_master recomp-fesom-recom-1.4` is doing almost the right thing. Only the first two lines need to get changed from 
```
         mkdir -p fesom-recom-1.4
         cd fesom-recom-1.4
```
to 
```
         mkdir -p awicm-1.0-recom
         cd awicm-1.0-recom
``` 

Cheers,  
Chris

<details>
<summary>esm_versions check</summary>

esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 0.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.2
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_master
├─ branch: release
└─ tags: v5.1.2-1-gf5196ac

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.12
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts
├─ branch: release
└─ tags: v5.1.12-1-g5d9fa0b

esm_tools
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: DETACHED at 6e69e05
└─ tags: v5.0.17-61-g6e69e05-dirty

esm_version_checker
├─ version: 5.1.4
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_version_checker
├─ branch: release
└─ tags: v5.1.4
</details>

**Comment by dbarbi** [comment]
Hi Chris,
in principle, this works, in the following way:
esm_master recomp-awicm-1.0-recom/fesom
would for example only recompile the fesom part

**Comment by chrisdane** [comment]
Great that works, thanks!

In this example, the order is important though:
```
esm_master recomp-awicm-1.0-recom/recom # must first
esm_master recomp-awicm-1.0-recom/fesom # must second
```

Would be nice to have this in the docu.
