### ISSUE TITLE
print all defined esm variables 

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#358]
**Is your feature request related to a problem? Please describe.**
Variable definitions via the esm_tools are pretty nested and its sometimes cumbersome to trace them and get the actual value a variable gets in the end. After job submission, I wonder how certain variables are finally defined but there is no way to check.

**Describe the solution you'd like**
When the runscript is submitted (with or without `-check`), create a long list where all variables and their values defined by the esm_tools are listed.

Thanks a lot,  
Chris

**Comment by mandresm** [comment]
Hi @chrisdane ,

There are actually several ways to check. The easiest one is, after you ran esm_runscripts, with or without check, you repeat the exact same command but add `--inspect config` at the end (e.g. `esm_runscripts <your_runscript.yaml> -e <exp_id> ... --inspect config`). That will return (in yaml format) the final information put together by the tools from all the yaml files involved (including the runscript itself).

The other option is to check the file containing the same exact information in either one of these 2 locations:
- `<exp_path>/run_<DATE>/config/<exp_id>_finished_*.yaml`
- `<exp_path>/config/<exp_id>_finished_*.yaml` (if you want to check an older config that is not the current running one).

You can find the info in the documentation here: https://esm-tools.readthedocs.io/en/latest/esm_runscripts.html#arguments , at the end of the table, the inspect flag

Maybe is a good idea to add this answer as a recipe to the cookbook? @dbarbi

**Comment by chrisdane** [comment]
Thanks a lot!

**Comment by chrisdane** [comment]
Are all of the paths and files written in the result of the `--inspect config`-call checked for existance and reading rights?

**Comment by mandresm** [comment]
They are checked for existence but not for reading rights. However, if you have not reading rights and it's to be copied, `esm_runscripts` will complain about not being able to copy the file.

**Comment by chrisdane** [comment]
A follow-up feature request: Currently, links are not dereferenced. For example, the finished config entry
```
oasis3mct 
    restart_in_sources 
        a2o_flux: /work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/esm-piControl_wout_talk_rest2/restart/oasis3mct/a2o_flux
```
does not help since its a link that may have changed in the meantime. Thus, I cannot verify which a2o_flux file was used for that specific run.

My request is to dereference all links (if any) in the finished config file.

Thx and cheers,
Chris

**Comment by mandresm** [comment]
That's a very good point! We are currently half way on redesigning the `filedict` syntax and making it more reliable and understandable. Therefore, I think it's better to only apply this idea for the new implementation of the `filedict`, instead of spending time on it now and also later. I will add this to our FileDict project on GitHub so it doesn't go forgotten.
