### ISSUE TITLE
gitclone not successful

### ISSUE THREAD

**Issue by clhinrichs** [esm-tools/esm_tools#359]
Hi, 

I just updated to the new tools and tried to install a model with those for the first time. The gitclone did not work, see message below. Any advice?

Best Claudia

esm_master get-fesom-recom-1.4
    Executing commands in this order:
         mkdir -p fesom-recom-1.4
         cd fesom-recom-1.4
         git clone -b oxygen https://a270109@gitlab.dkrz.de/modular_esm/recom.git recom
         git clone -b fesom-recom-mocsy-slp https://a270109@gitlab.dkrz.de/modular_esm/fesom-1.4.git fesom-1.4
         sed -i '/set(FESOM_COUPLED/s/ON/OFF/g' fesom-1.4/CMakeLists.txt
         sed -i '/FESOM_RECOM/s/OFF/ON/g' fesom-1.4/CMakeLists.txt
         sed -i '/RECOM_LIBRARY/s/OFF/ON/g' fesom-1.4/CMakeLists.txt
         cd ..
Cloning into 'recom'...

(gnome-ssh-askpass:48779): Gtk-WARNING **: cannot open display:
error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
Password for 'https://a270109@gitlab.dkrz.de':
remote: The project you were looking for could not be found.
fatal: repository 'https://gitlab.dkrz.de/modular_esm/recom.git/' not found
Traceback (most recent call last):
  File "/pf/a/a270109/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 84, in main_flow
    user_task.execute(ignore_errors) #env)
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/task.py", line 492, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/work/ab0995/a270109/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', '-b', 'oxygen', 'https://a270109@gitlab.dkrz.de/modular_esm/recom.git', 'recom']' returned non-zero exit status 128.

**Comment by dbarbi** [comment]
You don't have access to recom repository. Please contact Judith Hauck or someone else from the Resom developers to be added as user to the repo.

**Comment by clhinrichs** [comment]
Thanks, that was it.
