### ISSUE TITLE
Comp-fesom-recom-2.0

### ISSUE THREAD

**Issue by clhinrichs** [esm-tools/esm_tools#361]
I am trying to use esm_master comp-fesom-recom-2.0 to compile on mistral but the compilation does not finish.

in fesom-recom-2.0 is a fesom folder and a recom folder, I noticed that the offending file recom_extra.F90 shows up in the fesom folder, maybe that is supposed to do this, I don't know. I assumed recom files stay in recom. 

Can somebody test comp-fesom-recom-2.0 on mistral please?

Best Claudia

![image](https://user-images.githubusercontent.com/85611963/121381480-0c870100-c946-11eb-98f1-b2e6bcf5bc87.png)

**System (please complete the following information):**
 - Supercomputer: Mistral
 -  esm-tools release  | v5.1.7 |

**Additional context** Screen output
[ 33%] Building Fortran object CMakeFiles/recom.dir/recom_modular.F90.o
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(7): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
  USE o_MESH
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(22): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CLOCK]
  use g_clock
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CLOCK]
    use g_clock
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(23): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_PARAM]
  use o_PARAM
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(8): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_PARAM]
  USE o_PARAM
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(8): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CLOCK]
  use g_clock
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(24): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_PARSUP]
  use g_PARSUP
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(17): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_ARRAYS]
    use o_ARRAYS
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(9): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_ARRAYS]
  USE o_ARRAYS
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(9): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_PARAM]
  use o_PARAM
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(25): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_ROTATE_GRID]
  use g_rotate_grid
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_PARSUP]
    use g_PARSUP
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(10): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_PARSUP]
  USE g_PARSUP
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(10): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_PARSUP]
  use g_PARSUP
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(26): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CONFIG]
  use g_config
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_ROTATE_GRID]
  use g_rotate_grid
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(11): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CONFIG]
  USE g_CONFIG
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(27): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
  use o_MESH
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(19): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
    use o_MESH
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(40): error #6404: This name does not have a type, and must have an explicit type.   [MYDIM_ELEM2D]
    elem_size=myDim_elem2D+eDim_elem2D
--------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(40): error #6404: This name does not have a type, and must have an explicit type.   [EDIM_ELEM2D]
    elem_size=myDim_elem2D+eDim_elem2D
---------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(12): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CONFIG]
  use g_config
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(41): error #6404: This name does not have a type, and must have an explicit type.   [MYDIM_NOD2D]
    node_size=myDim_nod2D+eDim_nod2D
--------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(41): error #6404: This name does not have a type, and must have an explicit type.   [EDIM_NOD2D]
    node_size=myDim_nod2D+eDim_nod2D
--------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(65): error #6404: This name does not have a type, and must have an explicit type.   [NL]
    allocate(PAR3D(nl-1,node_size))
-------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(113): error #6404: This name does not have a type, and must have an explicit type.   [MYPE]
    if(mype==0) write(*,*) 'Benthic layers are set'
-------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(121): error #6911: The syntax of this substring is invalid.   [TR_ARR]
    tr_arr(:,:,6)  = tiny                  ! tracer 6  = PhyN   -> Intracellular conc of Nitrogen in small phytoplankton
----^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(13): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
  use o_MESH
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(12): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_FORCING_ARRAYS]
  use g_forcing_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(28): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_ARRAYS]
  use i_arrays          ! a_ice, m_ice
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(14): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_ARRAYS]
  use i_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(13): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM_AUTO]
  use g_comm_auto
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(30): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_PARAM]
  use i_param
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(16): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_PARAM]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(14): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_PARAM]
  use i_param
------^
  use i_param
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(15): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_ARRAYS]
  use i_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(17): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_ARRAYS]
  use o_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(31): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_ARRAYS]
  use o_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_FORCING_ARRAYS]
  use g_forcing_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(32): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_FORCING_ARRAYS]
  use g_forcing_arrays
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(16): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_THERM_PARAM]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(164): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_ROTATE_GRID]
  use i_therm_param
------^
  use g_rotate_grid
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(33): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM_AUTO]
  use g_comm_auto
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(19): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM_AUTO]
------^
  use g_comm_auto
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(34): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_THERM_PARAM]
  use i_therm_param
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(20): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [I_THERM_PARAM]
  use i_therm_param
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(17): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CLOCK]
  use g_clock
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(18): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_ROTATE_GRID]
  use g_rotate_grid
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(167): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_PARSUP]
  use g_PARSUP
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(35): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(19): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM]
  use g_comm
------^
  use g_comm
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(21): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM]
  use g_comm
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(81): error #6404: This name does not have a type, and must have an explicit type.   [NL]
  allocate(Temp(nl-1), zr(nl-1) , PAR(nl-1))
----------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(168): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CONFIG]
  use g_config
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(73): error #6404: This name does not have a type, and must have an explicit type.   [WP]
    thick   =0.0_WP
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(98): error #6404: This name does not have a type, and must have an explicit type.   [MYPE]
----------------^
if (recom_debug .and. mype==0) print *, achar(27)//'[36m'//'     --> Atm_input'//achar(27)//'[0m'
----------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(73): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [WP]
    thick   =0.0_WP
----------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(74): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [WP]
    recipthick=0.0_WP
------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(114): error #6404: This name does not have a type, and must have an explicit type.   [MYDIM_NOD2D]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(75): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [WP]
  do n=1, myDim_nod2D  ! needs exchange_nod in the end
    zF=0.0_WP
----------^
----------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(116): error #6404: This name does not have a type, and must have an explicit type.   [NLEVELS_NOD2D]
     nzmax=nlevels_nod2D(n)-1
-----------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(79): error #6404: This name does not have a type, and must have an explicit type.   [HNODE]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(119): error #6404: This name does not have a type, and must have an explicit type.   [A_ICE]
      thick(k)=hnode(k,n)
---------------^
     Loc_ice_conc      = a_ice(n)
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(80): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [WP]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(121): error #6404: This name does not have a type, and must have an explicit type.   [PAIR]
      if (hnode(k,n) > 0._WP) then
     Loc_slp           = Pair(n)
-------------------------^
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(83): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [WP]
         recipthick(k)=0._WP
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(129): error #6404: This name does not have a type, and must have an explicit type.   [U_WIND]
     ULoc              = sqrt(u_wind(n)**2+v_wind(n)**2)
------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(92): error #6404: This name does not have a type, and must have an explicit type.   [ZBAR_3D_N]
      zF(k)=zbar_3d_n(k,n)
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(129): error #6404: This name does not have a type, and must have an explicit type.   [V_WIND]
------------^
     ULoc              = sqrt(u_wind(n)**2+v_wind(n)**2)
-------------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(129): warning #7319: This argument's data type is incompatible with this intrinsic procedure; procedure assumed EXTERNAL.   [SQRT]
     ULoc              = sqrt(u_wind(n)**2+v_wind(n)**2)
------------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(25): error #6279: A specification expression object must be a dummy argument, a COMMON block object, or an object accessible through host or use association.   [NL]
  real(kind=8),dimension(nl),intent(out)      :: zF             ! [m] Depth of vertical fluxes
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(129): error #6404: This name does not have a type, and must have an explicit type.   [SQRT]
     ULoc              = sqrt(u_wind(n)**2+v_wind(n)**2)
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(25): error #6404: This name does not have a type, and must have an explicit type.   [NL]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(131): error #6404: This name does not have a type, and must have an explicit type.   [MONTH]
  real(kind=8),dimension(nl),intent(out)      :: zF             ! [m] Depth of vertical fluxes
     LocAtmCO2         = AtmCO2(month)
-------------------------^
--------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(91): error #6404: This name does not have a type, and must have an explicit type.   [DT]
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(133): error #6404: This name does not have a type, and must have an explicit type.   [SHORTWAVE]
  dt_d   =      dt/SecondsPerDay     ! Size of FESOM time step [day]
     SW                = parFrac * shortwave(n)
----------------^
-----------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(136): error #6404: This name does not have a type, and must have an explicit type.   [ROTATED_GRID]
     if (rotated_grid) then
---------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(136): error #6341: A logical data type is required in this context.   [ROTATED_GRID]
     if (rotated_grid) then
---------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(137): error #6404: This name does not have a type, and must have an explicit type.   [COORD_NOD2D]
        call r2g(lon, lat, coord_nod2d(1, n), coord_nod2d(2, n))
---------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(143): error #6911: The syntax of this substring is invalid.   [TR_ARR]
     Temp(1:nzmax)     = tr_arr(1:nzmax,n,1)      ! Temp(1:nn,1)      = tracer(inds(1:nn),1)
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(169): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
-------------------------^
  use o_MESH
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(170): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_COMM]
  use g_comm
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(264): error #6404: This name does not have a type, and must have an explicit type.   [MYDIM_NOD2D]
    allocate(lon_fesom(mydim_nod2D))
-----------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(264): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [MYDIM_NOD2D]
    allocate(lon_fesom(mydim_nod2D))
-----------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(265): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [MYDIM_NOD2D]
    allocate(lat_fesom(mydim_nod2D))
-----------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(266): error #6404: This name does not have a type, and must have an explicit type.   [ROTATED_GRID]
    if (rotated_grid) then
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(266): error #6341: A logical data type is required in this context.   [ROTATED_GRID]
    if (rotated_grid) then
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(268): error #6404: This name does not have a type, and must have an explicit type.   [COORD_NOD2D]
        call r2g(lon_fesom_loc, lat_fesom_loc, coord_nod2d(1, i), coord_nod2d(2, i)) !
-----------------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(269): error #6404: This name does not have a type, and must have an explicit type.   [RAD]
        lon_fesom(i) = lon_fesom_loc/rad
-------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(282): error #6404: This name does not have a type, and must have an explicit type.   [MYPE]
      in = (/MinDist(i),real(mype, 8)/)
-----------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(282): warning #7319: This argument's data type is incompatible with this intrinsic procedure; procedure assumed EXTERNAL.   [REAL]
      in = (/MinDist(i),real(mype, 8)/)
-----------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(282): error #6404: This name does not have a type, and must have an explicit type.   [REAL]
      in = (/MinDist(i),real(mype, 8)/)
------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(282): error #8209: If type specification is omitted, each element in an array-constructor must have the same type and kind type parameters.   [REAL]
      in = (/MinDist(i),real(mype, 8)/)
------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(284): error #6404: This name does not have a type, and must have an explicit type.   [MPI_COMM_FESOM]
      call MPI_Barrier(MPI_COMM_FESOM,MPIerr)
-----------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(284): error #6404: This name does not have a type, and must have an explicit type.   [MPIERR]
      call MPI_Barrier(MPI_COMM_FESOM,MPIerr)
--------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(285): error #6404: This name does not have a type, and must have an explicit type.   [MPI_DOUBLE_PRECISION]
      call MPI_AllREDUCE(in, out, 1, MPI_DOUBLE_PRECISION, MPI_MINLOC, &
-------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90(285): error #6404: This name does not have a type, and must have an explicit type.   [MPI_MINLOC]
      call MPI_AllREDUCE(in, out, 1, MPI_DOUBLE_PRECISION, MPI_MINLOC, &
-----------------------------------------------------------^
/tmp/ifortpJfikn.i90(3803): catastrophic error: Too many errors, exiting
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(27): error #6279: A specification expression object must be a dummy argument, a COMMON block object, or an object accessible through host or use association.   [NL]
  Real(kind=8),dimension(nl-1,bgc_num),intent(inout) :: state                ! ChlA conc in phytoplankton [mg/m3]
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(110): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CLOCK]
  use g_clock
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(27): error #6404: This name does not have a type, and must have an explicit type.   [NL]
  Real(kind=8),dimension(nl-1,bgc_num),intent(inout) :: state                ! ChlA conc in phytoplankton [mg/m3]
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(111): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_PARAM]
  use o_PARAM
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(112): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_PARSUP]
  use g_PARSUP
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(113): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
  use o_MESH
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(133): error #6404: This name does not have a type, and must have an explicit type.   [DAYNEW]
  yearfrac    = mod(real(daynew),real(ndpyr))/real(ndpyr)
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(133): warning #7319: This argument's data type is incompatible with this intrinsic procedure; procedure assumed EXTERNAL.   [REAL]
  yearfrac    = mod(real(daynew),real(ndpyr))/real(ndpyr)
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(133): error #6404: This name does not have a type, and must have an explicit type.   [REAL]
  yearfrac    = mod(real(daynew),real(ndpyr))/real(ndpyr)
--------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90(133): error #6404: This name does not have a type, and must have an explicit type.   [NDPYR]
  yearfrac    = mod(real(daynew),real(ndpyr))/real(ndpyr)
--------------------------------------^
/tmp/ifortJfvNhn.i90(169): catastrophic error: Too many errors, exiting
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(251): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [G_CONFIG]
  USE g_CONFIG
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90(252): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_ARRAYS]
  use o_ARRAYS
------^
/tmp/ifortG6HLdn.i90(329): catastrophic error: Too many errors, exiting
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(1006): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [O_MESH]
  use o_MESH
------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(1015): error #6279: A specification expression object must be a dummy argument, a COMMON block object, or an object accessible through host or use association.   [NL]
  Real(kind=8),dimension(nl-1) :: C
-------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90(1015): error #6404: This name does not have a type, and must have an explicit type.   [NL]
  Real(kind=8),dimension(nl-1) :: C
-------------------------^
compilation aborted for /mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_extra.F90 (code 1)
compilation aborted for /mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_main.F90 (code 1)
make[2]: *** [CMakeFiles/recom.dir/recom_extra.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/recom.dir/recom_main.F90.o] Error 1
compilation aborted for /mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_sms.F90 (code 1)
make[2]: *** [CMakeFiles/recom.dir/recom_sms.F90.o] Error 1
compilation aborted for /mnt/lustre01/pf/a/a270109/esm_tools/fesom-recom-2.0/recom/recom_init.F90 (code 1)
make[2]: *** [CMakeFiles/recom.dir/recom_init.F90.o] Error 1
make[1]: *** [CMakeFiles/recom.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/pf/a/a270109/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 84, in main_flow
    user_task.execute(ignore_errors) #env)
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/task.py", line 492, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/work/ab0995/a270109/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-recom-2.0-r_script.sh']' returned non-zero exit status 2.

**Comment by mandresm** [comment]
Hi @clhinrichs ,

I am not sure that fesom-recom-2.0 is supported right now (FESOM-2.0 + RECOM-2.0). The branches for that version are probably not the correct ones, as this implementation was not finished (and to my knowledge, never used). I think what is available right now and working, it's the following (@denizural and @mbutzin , please correct me if I'm wrong):

- fesom-recom-1.4 (FESOM-1.4 + RECOM-2.0)
- awicm-1.4-recom (FESOM-1.4 + RECOM-2.0 + ECHAM-6.3.5, WIP by @denizural )
- awiesm-2.1-recom (FESOM-2.1 + RECOM-2.0 @mbutzin's version + ECHAM-6.3.5)

If you need FESOM-2.0 + RECOM-2.0, we can work on it and it should be relatively easy to get it compiling and running, but to start with, we need to know which branches do we want to use for FESOM-2.0 and RECOM-2.0.

**Comment by clhinrichs** [comment]
Hi @mandresm, 

ok thanks. As of now I am not sure which fesom-recom-2.0 I need or if I need this at all or rather any of the other versions. So, I guess I can put this request on hold for know. 

I tried fesom-recom-1.4, that worked fine. And I'll try with both awicm versions later. 

Thanks for now.

**Comment by JanStreffing** [comment]
This issue seem be have been about a particular model run on mistral a year ago. It is likely no longer relevant for esm_tools development. Closing here.
