### ISSUE TITLE
Comp-awicm-1.0-recom

### ISSUE THREAD

**Issue by clhinrichs** [esm-tools/esm_tools#362]
Does not compile completely

------

[ 79%] Building Fortran object fesom_cpl/CMakeFiles/fesom.dir/gen_calcmeans.F90.o
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(10): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [RECOM_CONFIG]
  use recom_config
------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(74): error #6404: This name does not have a type, and must have an explicit type.   [USE_RECOM]
  if(use_REcoM) then
-----^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(74): error #6341: A logical data type is required in this context.   [USE_RECOM]
  if(use_REcoM) then
-----^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(75): error #6404: This name does not have a type, and must have an explicit type.   [BGC_NUM]
    allocate(recom_tracers_mean(bgc_num))
--------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(75): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [BGC_NUM]
    allocate(recom_tracers_mean(bgc_num))
--------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(80): error #6404: This name does not have a type, and must have an explicit type.   [DIAGS3D_NUM]
    allocate(Diags3D_mean(diags3d_num))
--------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(80): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [DIAGS3D_NUM]
    allocate(Diags3D_mean(diags3d_num))
--------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(269): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [RECOM_CONFIG]
  use recom_config
------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(302): error #6404: This name does not have a type, and must have an explicit type.   [USE_RECOM]
  if (use_recom) then
------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(302): error #6341: A logical data type is required in this context.   [USE_RECOM]
  if (use_recom) then
------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(341): error #6341: A logical data type is required in this context.   [USE_RECOM]
    if(use_REcoM) then
-------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(415): error #6341: A logical data type is required in this context.   [USE_RECOM]
     if(use_REcoM) then
--------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(429): error #6404: This name does not have a type, and must have an explicit type.   [PISTONVELOCITY]
      PistonVel_mean%local_values(row)       = PistonVel_mean%local_values(row)       + PistonVelocity(row)
----------------------------------------------------------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(430): error #6404: This name does not have a type, and must have an explicit type.   [ALPHACO2]
      alphaCO2_mean%local_values(row)        = alphaCO2_mean%local_values(row)        + alphaCO2(row)
----------------------------------------------------------------------------------------^
/mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90(431): error #6404: This name does not have a type, and must have an explicit type.   [GLOO2FLUX_SEAICEMASK]
      O2flux_mean%local_values(row)          = O2flux_mean%local_values(row)          + GloO2flux_seaicemask(row)
----------------------------------------------------------------------------------------^
compilation aborted for /mnt/lustre01/pf/a/a270109/esm_tools/awicm-1.0-recom/fesom-1.4/fesom_cpl/gen_calcmeans.F90 (code 1)
make[2]: *** [fesom_cpl/CMakeFiles/fesom.dir/gen_calcmeans.F90.o] Error 1
make[1]: *** [fesom_cpl/CMakeFiles/fesom.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/pf/a/a270109/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/esm_master.py", line 84, in main_flow
    user_task.execute(ignore_errors) #env)
  File "/pf/a/a270109/.local/lib/python3.6/site-packages/esm_master/task.py", line 492, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/work/ab0995/a270109/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-fesom-1.4-recom-awicm_script.sh']' returned non-zero exit status 2.

**System (please complete the following information):**
 - Mistral
 - release  | v5.1.7

**Comment by clhinrichs** [comment]
+---------------------+-----------+---------------------------------------------------------------+----------+--------+
| package_name        | version   | file                                                          | branch   | tags   |
|---------------------+-----------+---------------------------------------------------------------+----------+--------|
| esm_calendar        | 5.0.0     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_database        | 5.0.0     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_environment     | 5.1.0     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_master          | 5.1.3     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_motd            | 5.0.2     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_parser          | 5.1.6     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_plugin_manager  | 5.0.1     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_profile         | 5.0.0     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_rcfile          | 5.1.0     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_runscripts      | 5.1.12    | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
| esm_tools           | 5.1.7     | /mnt/lustre01/pf/a/a270109/esm_tools                          | release  | v5.1.7 |
| esm_version_checker | 5.1.4     | /mnt/lustre01/pf/a/a270109/.local/lib/python3.6/site-packages |          |        |
+---------------------+-----------+---------------------------------------------------------------+----------+--------+

**Comment by denizural** [comment]
Dear @clhinrichs, we looked at your problem with @mandresm. There is currently a compiling awicm-recom but you need to checkout to a different branch:
in `esm_tools` directory type `git checkout awicm_recom`

This will allow you to install the awicm with `oxygen` branch on Recom and `co2_coupling` in all others. The setup that Özgür has been using. 

Would that help or do you need a different setup? Please note that awicm-recom requires a special branch setting. The setup I mentioned above is still in progress. We are working together with Chris Danek.

**Comment by clhinrichs** [comment]
The compilation worked this time, thank you. I will test the model with these branches and afterwards will stay in touch with Özgür and Christopher about the current branches
