### ISSUE TITLE
OASIS produces "Model Runs Backwards"

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#363]
Hello,

@ackerlar ran into a problem with an LGM simulation with coupled ice-bergs. He is trying to restart the model. However, oasis complains with `1385423262792820437` which translates into:

```
ERROR model seems to be running backwards
```

The relevant folder is here:
`/work/ollie/lackerma/egu_2021/experiments/lgm/test_no-icb_SPINUP`

**Comment by dbarbi** [comment]
there seems to be a problem with the virtual environment, one of the first lines of the model output is that the venv-folder doesn't exist, and that is true. I don't think it is related to the backward running model though

**Comment by pgierz** [comment]
hmmm that should be created automatically if you want to be using it. @ackerlar, do you have `use_venv` set to true in your run?

**Comment by ackerlar** [comment]
I started a run without the virtual environment. I did not care too much about this as other runs worked fine even though this message occurred `/work/ollie/lackerma/egu_2021/experiments/lgm//test_no-icb_SPINUP/.venv_esmtools/bin/activate: No such file or directory`

**Comment by pgierz** [comment]
What happens if you have?
```
general:
    use_venv: False
```

**Comment by ackerlar** [comment]
The experiment is still running. I will report about what happened. But the broken run `/work/ollie/lackerma/egu_2021/experiments/lgm/test_no-icb_SPINUP` did also run well until the end. But I just realized that the model tried to start with 1st of January after it ran through the whole year (in the same job!): 
`line 11513221   0:  Stop model, last prognostic date/time is:  1. Jan     2001 00:00:00` in this file `/work/ollie/lackerma/egu_2021/experiments/lgm/test_no-icb_SPINUP/scripts/test_no-icb_SPINUP_compute_20000101-20001231_11438775.log`

So maybe related to leap year?

**Comment by dbarbi** [comment]
As I said, I don't think it is related to the issue, it just raised my interest.
All models seem to agree that it is a leapyear. Actually, everything is ending fine. fesom.clock is already written, echam restarts too. The "Stop model" line is fine.
The error is thrown by a fesom process, trying to work on sst_feom

**Comment by dbarbi** [comment]
In icb_step it looks as if you are trying to writte something to file icbID_ISM, which is never opened. again, not the cause of this bug.

**Comment by dbarbi** [comment]
it looks like fesom is trying another coupling, after writing restarts, fesom.clock and everything, without increasing the time step. that's where the "backwards" comes from. I don't see why it is trying that though.

**Comment by pgierz** [comment]
@ackerlar, can you try the same run config using a Fesom version without your ice bergs? That might give us some hints...

**Comment by dbarbi** [comment]
Bug in the code of fesom-2, branch icb_wiso (probably happened while merging). @ackerlar needs to correct what is broken, this issue is not an ESM-Tools problem
