### ISSUE TITLE
FESOM2 output files added to the namelist templates are not copied to outdata/fesom

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#371]
When I add additional output fields to the namelist.io under `/home/ollie/jstreffi/esm_tools/namelists/fesom2/namelist.io` they are ignored when moving the output to `outdata/fesom` at the end of a run.

To reproduce, just add for example flice in namelist.io. Run a month of FESOM2. The output file flice.fesom.[year].nc is written in the workfolder:

```
/work/ollie/jstreffi/runtime/awicm-3.1/with_snowmelt_cutoff/run_19900101-19941231/work$ ls *flice*
flice.fesom.1990.nc  flice.fesom.1991.nc  flice.fesom.1992.nc  flice.fesom.1993.nc  flice.fesom.1994.nc
```
None of the files make it into the outdata/fesom folder.
```
/work/ollie/jstreffi/runtime/awicm-3.1/with_snowmelt_cutoff/outdata/fesom$ ls *flice*
ls: cannot access *flice*: No such file or directory
```

I suggest using wildcards since the fesom2 output files strictly follow an easy patter that is not matched by any other files in the workfolder: `*.fesom.*.nc`

**Comment by mandresm** [comment]
I have just cherry-picked the changes of #372 into `feature/awicm3_prep_merge_geomar`. This should solve both this issue and #370 (I have actually tested it)
