### ISSUE TITLE
Calendar Ranges

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#374]
Hello,

sometimes when building scripts or tools that depend on esm-tools simulations, it is useful to have some sort of thing that allows you create a list of output files for a specific range of dates. For instance, it would be very nice if I could do something like:

```python
class ESMSimulation:
    ... some basic methods, e.g. still running, current date, current progress, etc...

class AWIESMSimulation(ESMSimulation):
    def get_temp2_files(start_date, stop_date):
        # some logic here that creates either a list of files containing temp2, or a dictionary of lists with keys being filetags, and values being lists of file paths
        return list_or_dict_of_temp2_files
```

In the background, we would need something like:
```python
def date_range(start_date, stop_date, delta_date):
    # Something builds a generator or list of dates
    return list_of_dates
```

Maybe common analyses could be gathered in these classes.

What do you guys think?

Note that this feature request very much does not belong here, but maybe rather in esm-utilities.

**Comment by denizural** [comment]
For me it looks nice. I actually implemented a similar data_range and simulation automatizer for another project. I can say that it definitely makes your life easier.

**Comment by pgierz** [comment]
Closing, see the newest commit in esm calendar from late last week
