### ISSUE TITLE
esm_runscripts should check for model binary update after recompile

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#375]
**Is your feature request related to a problem? Please describe.**
The `esm_runscripts` -call should check if any of the used model binaries were updated since the last model run. I submitted new jobs and was wondering why my changes in the model code do not appear in the logfile. The `--update` argument of esm_runscripts does not help. I assumed the model bins are also checked for updates.

**Describe the solution you'd like**
If esm_runscripts detect a newer model binary in `model_dir` from the runscript compared to the one in `run_YYYY/work`, the new binary should be used or the user should be asked or something like this. 

**Describe alternatives you've considered**
Start a new experiment.
EDIT: Copy the new binary to the `/work/expid/bin` directory by hand.

Thanks for consideration and sorry if there is already a solution to this; I couldn't find it.
Kind regards,  
Chris

**Comment by pgierz** [comment]
I am only 50% happy with this. In principle, it is not a very good idea to update the model binary during a production simulation, as that might induce novice users to have unexpected jumps in their runs (in the worst case) or different formats/contents to their log files (in a more harmless case). There should be clearly stated intent from the user side for this to actually happen.

Default should be, in my opinion, Chris' option B: ask what should happen unless a flag is provided. Standard should be to not modify binaries during a running simulation. This might also incur problems in already running jobs if the user changes the binary between various jobs, so it might be a good idea to also double check where the job was launched from (user command line, or auto-resubmit from the sad file). I would always use the same binary in the case of a resubmit, and, in the case of a user new start (or continuation from the login node after a crash), check if there are binary differences, and ask what should be done.

**Comment by denizural** [comment]
I was going to say the same thing. I am just formulating a flag like `--update-model`. Of course people should be using it considerably

**Comment by chrisdane** [comment]
Making production runs and testing new code follow different workflows. For the first you are right. For the latter such an argument for the esm_runscript -call would be very useful!

**Comment by pgierz** [comment]
`--update-model` sounds good to me! I'd also suggest not making a short option for that one. If someone wants to do this, they should really write it out (for safety) ;-)

**Comment by denizural** [comment]
> `--update-model` sounds good to me! I'd also suggest not making a short option for that one. If someone wants to do this, they should really write it out (for safety) ;-)

Actually, I was also thinking about adding it into the runscripts like
```yaml
fesom:
    update_model: True
```
But, then I gave up because I am 100% sure that someone may forget that open

**Comment by pgierz** [comment]
@denizural I would actually not allow this at all through the runscript. That needs to be a user flag, and only a flag.

Imagine the following: you put this option in your runscript, and hack away at your model. You already have a few runs online, which are doing "useful" things with an old model programming. Suddenly, you keep running, and without any sort of information, your model binary is changing! It does different things! The physics are weird (imagine changing the numerical solution to some equation, for instance), the logs are different, who knows.... Even if, in @chrisdane's  case, he is probably only updating logs for new info, it opens the door for dangerous stuff.

To me, that sounds like a disaster waiting to happen, and one that will be extremely tricky to actually track down after the fact.

**Comment by denizural** [comment]
Exactly Paul, and I will also implement a print message in capital (with or without verbose open) saying that updated model is used. Also comparing the `MD5 checksums` would also be a good idea. Eg.
```python
hash_from_model_dir = hashlib.md5("model_in_model_dir.exe").hexdigest()
hash_from_work_dir = hashlib.md5("model_in_work_dir.exe").hexdigest()

if hash_from_model_dir  != hash_from_work_dir:
    print("Something like: model binaries changed")
```
I just made a trial with that. When I add another statement and compile the code the MD5 changes.

**Comment by JanStreffing** [comment]
We talked about this during the retreat again. My suggestion is to make the -U flag update not only the runscript but also the binarys. In addition the namelist templates from $HOME/esm_tools/namelist should only overwrite what's in the run folder when -U is used too.

**Comment by mandresm** [comment]
This is already possible with `esm_runscripts --update-filetypes bin`. Is that a satisfactory solution or should we make `-U` update everything? The downside of doing it through `-U` is that it's not very tunable, while the `--update-filetypes` is very specific and documented in `esm_runscripts -h` help menu.

**Comment by JanStreffing** [comment]
I think this might be enough as is.

**Comment by mandresm** [comment]
Then I'll close it. Please, open it again if you'd like further discussion.
