### ISSUE TITLE
Installing esm_runscripts package on juwels with python3.6 after uninstalling from python3.8

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#382]
Since this issue turned out to be harder to solve than I first imaged I will make an issue out of it. Here is a copy of my chat with Deniz:

Jan Streffing  4:00 PM
Hey everyone, I just switched python versions from 3.8 to 3.6 on juwels, since the intel 2020 compiler was installed with a faulty gcc versions from their side. I have to use intel 2019.
I did an uninstall following https://esm-tools.readthedocs.io/en/latest/installation.html#uninstall-esm-tools and reinstalled esm_tools following: https://esm-tools.readthedocs.io/en/latest/installation.html#installing. Now I want to get my esm_runscripts branch back, following: https://esm-tools.readthedocs.io/en/latest/contributing.html#contribution-to-other-packages
upon pip install -e . I get:
```
Installing collected packages: esm-runscripts
  Found existing installation: esm-runscripts 5.1.20
    Uninstalling esm-runscripts-5.1.20:
      Successfully uninstalled esm-runscripts-5.1.20
  Running setup.py develop for esm-runscripts
    Complete output from command /gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/bin/python -c "import setuptools, tokenize;__file__='/p/project/chhb19/jstreffi/esm_runscripts/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    error: can't create or remove files in install directory
    The following error occurred while trying to add or remove files in the
    installation directory:
        [Errno 13] Permission denied: '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/test-easy-install-4015.write-test'
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
        /gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    For information on other options, you may wish to consult the
    documentation at:
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    Please make the appropriate changes for your system and try again.
    ----------------------------------------
  Rolling back uninstall of esm-runscripts
  Moving to /p/home/jusers/streffing1/juwels/.local/bin/esm_runscripts
   from /p/scratch/chhb19/jstreffi/tmp/pip-uninstall-ikrcv0of/esm_runscripts
  Moving to /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_runscripts-5.1.20.dist-info/
   from /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/~sm_runscripts-5.1.20.dist-info
  Moving to /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_runscripts/
   from /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/~sm_runscripts
Command "/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/bin/python -c "import setuptools, tokenize;__file__='/p/project/chhb19/jstreffi/esm_runscripts/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /p/project/chhb19/jstreffi/esm_runscripts/
what is the correct install dir / prefix that i should give here? or does the error message hide a different problem?
```

Deniz Ural  4:01 PM
what does sys.path give? (edited) 

Jan Streffing  4:02 PM
what do you mean give?

Deniz Ural  4:03 PM
The output in python. import sys; print(sys.path) this is the installation path. It looks like there is a problem with the installation path

Jan Streffing  4:04 PM
`['', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python36.zip', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/lib-dynload', '/p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages', '/p/project/chhb19/jstreffi/esm_tools/esm_tools', '/p/project/chhb19/jstreffi/esm_tools', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/six-1.12.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pyparsing-2.3.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/packaging-19.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/appdirs-1.4.3-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/certifi-2019.3.9-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pip-19.0.3-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/blist-1.3.6-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/argparse-1.4.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Cython-0.29.6-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/python_dateutil-2.8.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/deap-1.2.2-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/decorator-4.4.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/liac_arff-2.4.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/ecdsa-0.13-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pyasn1-0.4.5-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/cffi-1.12.2-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/enum34-1.1.6-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/ipaddress-1.0.22-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/asn1crypto-0.24.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/idna-2.8-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/cryptography-2.6.1-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/PyNaCl-1.3.0-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/bcrypt-3.1.6-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/paramiko-2.4.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/netifaces-0.10.9-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/netaddr-0.7.19-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/funcsigs-1.0.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pytz-2018.9-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/lxml-4.3.3-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/XlsxWriter-1.1.5-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Pygments-2.3.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/backports.shutil_get_terminal_size-1.0.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/wcwidth-0.1.7-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/prompt_toolkit-2.0.9-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/psycopg2-2.7.7-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/protobuf-3.7.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Click-7.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/itsdangerous-1.1.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Werkzeug-0.15.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/MarkupSafe-1.1.1-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Jinja2-2.10-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Mako-1.0.8-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/py-1.8.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/setuptools_scm-3.2.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/attrs-19.1.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/more_itertools-7.0.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pluggy-0.9.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/atomicwrites-1.3.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/scandir-1.10.0-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pathlib2-2.3.3-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pytest-4.4.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pytest_runner-4.4-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/ply-3.11-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pickleshare-0.7.5-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/simplegeneric-0.8.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/parso-0.3.4-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/jedi-0.13.3-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/typing-3.6.6-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/urllib3-1.24.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/chardet-3.0.4-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/requests-2.21.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/SQLAlchemy-1.3.1-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/python_editor-1.0.4-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/alembic-1.0.8-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/vcversioner-2.16.0.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pyrsistent-0.14.11-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/jsonschema-3.0.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/python_oauth2-1.1.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/wheel-0.33.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Rtree-0.8.3-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/ClusterShell-1.8-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/cloudpickle-0.8.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/Pillow-6.0.0-py3.6-linux-x86_64.egg', `
4:04
it goes on like that for longer still
4:04
more than i can fit in slack
4:04
`oftware/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/xvfbwrapper-0.2.9-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/traits-5.0.0-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/webencodings-0.5.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/html5lib-1.0.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/isodate-0.6.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/rdflib-4.2.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/SPARQLWrapper-1.8.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/networkx-2.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/prov-1.5.3-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/simplejson-3.16.0-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/configparser-3.7.4-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pydot-1.4.1-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pydotplus-2.0.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/olefile-0.46-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/argcomplete-1.9.5-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/grako-3.99.9-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pytest_forked-1.0.2-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/apipkg-1.5-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/execnet-1.6.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/pytest_xdist-1.27.0-py3.6.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/TatSu-4.2.6-py3.6-linux-x86_64.egg', '/gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/psutil-5.6.1-py3.6-linux-x86_64.egg']
`
Deniz Ural  4:04 PM
I am in a meeting but I will have a look

Jan Streffing  4:05 PM
ty
4:06
`'/p/project/chhb19/jstreffi/esm_tools/esm_tools', '/p/project/chhb19/jstreffi/esm_tools',`
4:06
the probably relevant parts
4:07
i moved the tools from the former path to the latter recently. maybe that trips something up?

Deniz Ural  4:09 PM
I think I get it. Think of /gpfs/software/juwels/stages/2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/site-packages/  as /usr/lib . You don't have write access in that directory. You install 'your' Python libraries into ${HOME}/.local/lib/python-blah-blah . It is trying to delete some stuff from the system-wide directories.

Jan Streffing  4:10 PM
correct

Jan Streffing  4:17 PM
so instead if -e i used:
pip install --install-option="--prefix=/p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages" .

Deniz Ural  4:17 PM
Did that one work?

Jan Streffing  4:17 PM
not complains by pip but esm_versions check does not recognize it
4:18
```
+---------------------+-----------+---------------------------------------------------------------------+----------------------------------+----------------------+
| package_name        | version   | file                                                                | branch                           | tags                 |
|---------------------+-----------+---------------------------------------------------------------------+----------------------------------+----------------------|
| esm_calendar        | 5.0.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_database        | 5.0.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_environment     | 5.1.1     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_master          | 5.1.3     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_motd            | 5.0.2     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_parser          | 5.1.7     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_plugin_manager  | 5.0.1     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_profile         | 5.0.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_rcfile          | 5.1.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
| esm_tools           | 5.0.12    | /p/project/chhb19/jstreffi/esm_tools                                | feature/awicm3_prep_merge_geomar | v5.0.12-301-g8526c25 |
| esm_version_checker | 5.1.4     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                                  |                      |
+---------------------+-----------+---------------------------------------------------------------------+----------------------------------+----------------------+
```
4:18
i think i may just be installing the release package again thats already at /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages

Deniz Ural  4:19 PM
In order to delete manually, You can also delete the esm-tools related egg files and binaries from /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages and /p/home/jusers/streffing1/juwels/.local/bin

Jan Streffing  4:20 PM
you mean like in: https://esm-tools.readthedocs.io/en/latest/installation.html#uninstall-esm-tools?

Deniz Ural  4:21 PM
Yes but ls first before rm or at least use rm -i?

Jan Streffing  4:22 PM
they were not there
4:22
```
esm_versions clean
You're pushing the red button. Duck and cover!
----------------------------------------------
Will remove the following
  Python packages:
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm-tools.egg-link
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_rcfile
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_database
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_calendar-5.0.0.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_rcfile-5.1.0.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_motd-5.0.2.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_profile
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_environment-5.1.1.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_motd
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_environment
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_master-5.1.3.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_plugin_manager
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_version_checker-5.1.4.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_database-5.0.0.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_parser-5.1.7.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_plugin_manager-5.0.1.dist-info
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_version_checker
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_calendar
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_master
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_parser
    /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_profile-5.0.0.dist-info
  Binary programs:
    /p/home/jusers/streffing1/juwels/.local/bin/esm_database
    /p/home/jusers/streffing1/juwels/.local/bin/esm_plugins
    /p/home/jusers/streffing1/juwels/.local/bin/esm_versions
    /p/home/jusers/streffing1/juwels/.local/bin/esm_master
    /p/home/jusers/streffing1/juwels/.local/bin/esm_database
    /p/home/jusers/streffing1/juwels/.local/bin/esm_plugins
    /p/home/jusers/streffing1/juwels/.local/bin/esm_versions
    /p/home/jusers/streffing1/juwels/.local/bin/esm_master
    /p/home/jusers/streffing1/juwels/.local/bin/esm_database
    /p/home/jusers/streffing1/juwels/.local/bin/esm_plugins
    /p/home/jusers/streffing1/juwels/.local/bin/esm_versions
    /p/home/jusers/streffing1/juwels/.local/bin/esm_master
Do you want to continue? [y/N]: y
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm-tools.egg-link
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_rcfile
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_database
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_calendar-5.0.0.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_rcfile-5.1.0.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_motd-5.0.2.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_profile
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_environment-5.1.1.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_motd
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_environment
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_master-5.1.3.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_plugin_manager
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_version_checker-5.1.4.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_database-5.0.0.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_parser-5.1.7.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_plugin_manager-5.0.1.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_version_checker
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_calendar
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_master
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_parser
* Removing /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm_profile-5.0.0.dist-info
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_database
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_plugins
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_versions
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_master
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_database
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_plugins
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_versions
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_master
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_database
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_plugins
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_versions
* Removing /p/home/jusers/streffing1/juwels/.local/bin/esm_master
streffing1@jwlogin01:/p/project/chhb19/jstreffi/esm_runscripts:rm ~/.local/bin/esm*
rm: cannot remove '/p/home/jusers/streffing1/juwels/.local/bin/esm*': No such file or directory
streffing1@jwlogin01:/p/project/chhb19/jstreffi/esm_runscripts:rm ~/.local/lib/python3.6/site-packages/esm*
rm: cannot remove '/p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages/esm*': No such file or directory
```
4:22
New

Deniz Ural  4:23 PM
Then that should be fine. I think mixing Python versions 3.6 and 3.8 created the issue

Jan Streffing  4:24 PM
i still get the same error when i try to install the branch of esm_runscripts

Deniz Ural  4:25 PM
which Python version are you using?

Jan Streffing  4:25 PM
makes sense cause i already did these steps before
4:25
Python/3.6.8

**Comment by pgierz** [comment]
I shouldn't have renamed it from `esm_versions clean` to `esm_versions nuke`, that was clearly better

**Comment by pgierz** [comment]
Magical trick: use the `--user` flag. I do not yet know why, exactly, but that worked.
