### ISSUE TITLE
Invalid hostfile_srun during AWI-ESM-2.1 run

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#383]
**Describe the bug**
Starting a job with awi-esm-2.1, the model immediately stops with this error:
```
srun: error: Invalid task range specification
srun: error: Line 1 of configuration file hostfile_srun invalid
```

The `hostfile_srun` looks like this:
```
0--1  ./echam6                                                                                                                                                                                                     
1-288  ./fesom
```

The `namelist.echam` parctl like this:
```
&parctl
    nproca = 24
    nprocb = 24
    nprocar = 0 
    nprocbr = 0                                                                                                                                                                                                    
/
```

The run can be found here: `/work/ollie/lackerma/processor-partitioning/experiments/awicm_test01`

**Expected behavior**
The `hostfile_srun` should contain a valid proc range for ECHAM according to `nproca` and `nprocb` from `namelist.echam`.

**System (please complete the following information):**
 - Supercomputer: Ollie
 - Model versions: ECHAM branch `ice`; FESOM detached from e990e2e
 - Version:
 ```
+---------------------+-----------+----------------------------------------------------------------------------------------------+--------------+---------------------------+
| package_name        | version   | file                                                                                         | branch       | tags                      |
|---------------------+-----------+----------------------------------------------------------------------------------------------+--------------+---------------------------|
| esm_calendar        | 5.0.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_database        | 5.0.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_environment     | 5.1.1     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_master          | 5.1.3     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_motd            | 5.0.2     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_parser          | 5.1.7     | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_parser         | prep_release | v5.1.7-17-g333f8ec        |
| esm_plugin_manager  | 5.0.0     | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_plugin_manager | vilma        | v5.0.0-1-gc6cb2f7         |
| esm_profile         | 5.0.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_rcfile          | 5.1.0     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
| esm_runscripts      | 5.0.14    | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_runscripts     | prep_release | v5.0.14-47-g712b892-dirty |
| esm_tools           | 5.1.9     | /work/ollie/lackerma/processor-partitioning/software/github.com/esm-tools/esm_tools          | prep_release | v5.1.9-36-g919aa2c        |
| esm_version_checker | 5.1.4     | /work/ollie/lackerma/processor-partitioning/.direnv/python-3.7.4/lib/python3.7/site-packages |              |                           |
+---------------------+-----------+----------------------------------------------------------------------------------------------+--------------+---------------------------+
```

**Additional context**
I am trying to run AWI-ESM coupled with PISM. That is why I use the `prep_release` branches.

**Comment by mandresm** [comment]
Can you do `git diff` in the `esm_runscripts` package and post here the results of that?

**Comment by ackerlar** [comment]
Here is the output:

```
diff --git a/esm_runscripts/workflow.py b/esm_runscripts/workflow.py
index d1ecb1d..b610049 100644
--- a/esm_runscripts/workflow.py
+++ b/esm_runscripts/workflow.py
@@ -134,6 +134,9 @@ def order_clusters(config):
 
         if "run_before" in gw_config["subjob_clusters"][subjob_cluster]:
             if not gw_config["subjob_clusters"][subjob_cluster]["run_before"] in gw_config["subjob_clusters"]:
+                print('gw_config["subjob_clusters"][subjob_cluster]["run_before"] = ', gw_config["subjob_clusters"][subjob_cluster]["run_before"])
+                print('gw_config["subjob_clusters"][subjob_cluster] = ', gw_config["subjob_clusters"][subjob_cluster])
+                print('gw_config["subjob_clusters"] = ', gw_config["subjob_clusters"])
                 print(f"Unknown cluster {subjob_cluster['run_before']}.")
                 sys.exit(-1)
 
@@ -250,6 +253,7 @@ def init_total_workflow(config):
 
     tasks = 0
     for model in config["general"]["valid_model_names"]:
+        print("LA DEBUG: model = ", model)
         if "nproc" in config[model]:
             tasks += config[model]["nproc"]
         elif "nproca" in config[model] and "nprocb" in config[model]:
@@ -260,6 +264,7 @@ def init_total_workflow(config):
                     and config[model]["nprocbr"] != "remove_from_namelist"
                 ):
                     tasks += config[model]["nprocar"] * config[model]["nprocbr"]
+        print("LA DEBUG: tasks = ", tasks)
         
    
     prepcompute = {"prepcompute": {
```

**Comment by denizural** [comment]
@ackerlar, maybe it would be better to use `remove_from_namelist` for the `nprocar` and `nprocbr`. I have a feeling that they initialize the hostfile with 0. What do you think @mandresm?

**Comment by ackerlar** [comment]
@denizural , I tried to remove it from the namelist via:
```
    namelist_changes:
            namelist.echam:
                    parctl:
                            nprocar: "remove_from_namelist"
                            nprocbr: "remove_from_namelist"
``` 

(`/work/ollie/lackerma/processor-partitioning/experiments/awicm_test02/run_20000101-20001231/scripts/awicm-ollie-initial-yearly.yaml`)

but it is still in `namelist.echam` 
(`/work/ollie/lackerma/processor-partitioning/experiments/awicm_test02/run_20000101-20001231/work/namelist.echam`)

**Comment by denizural** [comment]
Ah well, this is a bug I found previously. Could you please use `add_namelist_changes` instead of `namelist_changes` and try again with a check run?

**Comment by mandresm** [comment]
Okay, I think I see what's going on. ESM-Tools doesn't read the `namelists` and uses the information there to create the hostfile. Instead, ESM-Tools reads the yaml files provided. Inside that, `nproca` and `nprocb` variables and also `nprocar` and `nprocbr` in the yaml files have a very specific use in the generation of the hostfile (implemented by @khimstedt ). For that to work correctly you need to `"remove_from_namelist"` `nprocar` and `nprocbr` in your runscript if you want that it generates the correct hostfile:

```
echam:
    nprocar: "remove_from_namelist" 
    nprocbr: "remove_from_namelist"
```

**Comment by ackerlar** [comment]
I removed `nprocar` and `nprocbr` from the namelist and set `nproca` and `nprocb` within the runscript. Unfortunately, `hostfile_srun` does still not look okay.

`/work/ollie/lackerma/processor-partitioning/experiments/awicm_test06`

**Comment by mandresm** [comment]
`nproc` vars are all handled inside the `echam.yaml` and set there to go into the namelist_changes already:

https://github.com/esm-tools/esm_tools/blob/e284ce32e3b4e1d37a6f7f4b0a65a35b78c937f8/configs/components/echam/echam.yaml#L595-L622

Can you please try the following in your runscript:
```
echam:
    version: "6.3.05p2-concurrent_radiation-paleodyn"
    restart_unit: "months"
    restart_rate: 12
    nproca: 24
    nprocb: 24
    lresume: false
    nprocar: "remove_from_namelist"
    nprocbr: "remove_from_namelist"
```

In this case there is no need for namelist_changes

**Comment by ackerlar** [comment]
The ECHAM setting looks fine now but the FESOM line is still not okay:
```
0-575  ./echam6                                                                                                                                                                                                    
1-288  ./fesom
```

`/work/ollie/lackerma/processor-partitioning/experiments/awicm_test07`

Do I have to include anything in the FESOM section?

**Comment by mandresm** [comment]
I don't think so, that really looks like a bug. I solved something similar for `awicm2` (no workflow manager) last week. I think the bug might be in a conflict between my bug fix and the workflow implementation. What do you think @dbarbi ?

**Comment by ackerlar** [comment]
I fixed the issue in `batch_system.py`:
```
238                 start_proc = config[model]["end_proc"] + 1 
```

instead of:
```
238                 start_proc = end_proc + 1 
```

I cannot push my commit. Do I need to create a new branch in order to be able to push my changes?

**Comment by denizural** [comment]
Since you are not a developer, you don't have any write access to the repo. What we usually to is make a pull request, review it and then merge it (either as a `hotfix` or `feature`). You can still make a pull request over the fork.

**Comment by ackerlar** [comment]
Apparently, there already has been a fix for this in one of latest commits. I close this issue now.
