### ISSUE TITLE
0: Warning (gribZip) : Compression disabled, szlib or libaec not available!

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#386]
**Describe the bug**
When I run echam with the runscript lines
```
echam:
    namelist_changes:
        namelist.echam:
            runctl:
                OUT_FILETYPE: 1 # 1: grib, 2: nc
                OUT_ZTYPE: 1 # 0: no compression, 1: szip compression for grib output
```
echam complains with
```
0: Warning (gribZip) : Compression disabled, szlib or libaec not available!
```

**To Reproduce**
Run a default echam experiment with the lines above in the runscript.

**Expected behavior**
Compression should be applied.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]
<details>
<summary>esm_versions check</summary>

```
esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 0.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.2
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_master
├─ branch: release
└─ tags: v5.1.2-1-gf5196ac

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.20
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts
├─ branch: release
└─ tags: v5.1.20-1-gb3a115d

esm_tools
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: awicm_recom
└─ tags: v5.0.17-64-g2e1b74d

esm_version_checker
├─ version: 5.1.4
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_version_checker
├─ branch: release
└─ tags: v5.1.4
```
</details>

Thanks a lot for help and kind regards,
Chris

**Comment by pgierz** [comment]
Maybe this is something that needs to be told at compiletime?

**Comment by chrisdane** [comment]
Adding `libaec` to mistral.yaml
```
 module_actions:
         - "purge"
         - "unload netcdf_c"
         - "unload intel intelmpi"
         - "load python/3.5.2"
         - "load cmake/3.13.3"
         - "load autoconf/2.69"
         - "load nco"
         - "load cdo"
         - "load libaec"
```
does not help.

Can you find where in the model code this warning is generated? I cannot find it :(
```
modelcode: /pf/a/a270073/esm/awicm-1.0-recom
```

**Comment by denizural** [comment]
The warning message probably comes from the library, not from Echam source code. Add `VERBOSE=1` to `comp script` will turn verbosity on and give more diagnostic messages. Does this make the simulation crash anyways? Warning should not be catastrophic but tells you that the performance might not be optimal.

To @pgierz : I use verbose compilation quite a lot when debugging. I think we might consider adding this to esm-tools.

**Comment by chrisdane** [comment]
Ah it comes from one of
```
/pf/a/a270073/esm/awicm-1.0-recom/echam-6.3.04p1/cdi/src/cdilib.c
#if ! (defined (HAVE_LIBSZ) || defined (HAVE_LIBAEC))
  static int libszwarn = 1;
  if ( libszwarn )
    {
      Warning("Compression disabled, szlib or libaec not available!");
      libszwarn = 0;
    }
```
or
```
/pf/a/a270073/esm/awicm-1.0-recom/echam-6.3.04p1/cdi/src/cgribexlib.c
#if ! (defined (HAVE_LIBSZ) || defined (HAVE_LIBAEC))
  static int libszwarn = 1;
  if ( libszwarn )
    {
      Warning("Compression disabled, szlib or libaec not available!");
      libszwarn = 0;
    }
```

<br>

Do you know how to enable either `HAVE_LIBSZ` or `HAVE_LIBAEC`?

**Comment by denizural** [comment]
On the compilation line having `-DHAVE_LIBSZ` and `-DHAVE_LIBAEC` should turn these flags on.

Compilation of Echam in AWICM is handled by CMake that Jan Hegewald implemented, I guess (confirmation needed). Then, you need to modify CMakelists.txt file. 

Maybe setting `SZLIB_LIBS` and `SZLIB_INCLUDE` environment variables could help but I am not sure. 

Also look at this:

```
(in /pf/a/a270073/esm/awicm-1.0-recom/echam-6.3.04p1/cdi)
$ ./configure --help

--with-szlib=<yes|no|directory> (default=no)
    location of szlib library, optional for GRIB1 and NETCDF4 compression
```

So, when you ./configure CDI code (this command generates Makefile) with `--with-szlib=path-to-szlib` should work. I checked my previous compilation logs and see that my Echam used CDI-Yaxt and there are no warnings

**Comment by pgierz** [comment]
Not all ECHAM is built with CMake. The concurrent radiation variant still uses the older configure/make/make install pattern. We were never able to CMake to work with that version.

Chris, if you can figure out how much space this saves, and if it's considerable, I can look into adding those options to the ConcRad version too.

**Comment by chrisdane** [comment]
Great Deniz. Where exactly do I need to put this information so that `esm_master recomp-<model>` takes it into account?

**Comment by denizural** [comment]
Maybe it is better to ask Jan Hegewald first about that. Meanwhile you can add VERBOSE to your `comp-script`, (I hope this file is still there). Eg.
```
mkdir -p build; cd build; cmake ..;   make VERBOSE=1 install -j `nproc --all`
```
So that we have a verbose output of the Echam compilation and what it does to CDI.

Don't forget to redirect the output of the compilation. Eg. 
`./comp-echam-6.3.04p1_script.sh &>comp_echam.log`

**Comment by hegish** [comment]
> Maybe it is better to ask Jan Hegewald first about that.

Hi there, I am not sure what the actual question is?

**Comment by pgierz** [comment]
I believe the short question is "how do we add options that would get passed to configure to the cmakelist", but Chris and Deniz may have more precise formulations

**Comment by chrisdane** [comment]
Exactly Paul. The question is where to put which command in https://gitlab.dkrz.de/modular_esm/echam6/-/tree/master so that echam and/or cdi is compiled with `--with-szlib=path-to-szlib` so that if I run echam with the namelist.echam entries
```yaml
            runctl:
                OUT_FILETYPE: 1 # 1: grib, 2: nc
                OUT_ZTYPE: 1 # 0: no compression, 1: szip compression for grib output
```
the model does not complain with 
```
0: Warning (gribZip) : Compression disabled, szlib or libaec not available!
```
but just applies the compression.

**Comment by denizural** [comment]
Hi Chris,
you can add `--with-szlib=path-to-szlib` of similar configuration and compilation lines to the `conf_command` or `comp_command` sections in the `echam.yaml`

**Comment by pgierz** [comment]
No Deniz, it uses CMake, not Autotools. There is no conf command

**Comment by hegish** [comment]
Hi all, I still do not understand. You want to add compiler options? Or cmake options?

**Comment by denizural** [comment]
I think Chris wants to add an option that would turn on szlib compression. Should that go into CMakelist file?

**Comment by hegish** [comment]
You could do that in CMakeLists.txt with e.g.
```
option(szlib_compression "toogle szlib compression" OFF)
```

and then:

```
if(${szlib_compression})
   # whatever you have to do to enable zlib compression
endif()

```

Then set it ON via _ccmake_ or before calling cmake the first time with _cmake -Dszlib_compression=ON ../src_

**Comment by pgierz** [comment]
@chrisdane: any progress here? Can I close this one?

**Comment by JanStreffing** [comment]
It seems we have a good idea of how to solve this, and how to avoid such error on Levante. If it does reappear there I would suggest opening a new issue for that. Closing here.
