### ISSUE TITLE
general nyear and echam restart_unit must fit together

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#389]
**Describe the bug**
When I run a default echam experiment with
```yaml
general: 
    nyear: 1
echam: 
    restart_unit="months"
```
in the runscript, the logfile shows after one successfull modeled month 
```
- source: <expname>/run_19500101-19501231/work/restart_somefile_19501231235230
- target: <expnam>/run_19500101-19501231/restart/echam/restart_somefile_19501231.nc
WARNING: File not found
```
since the esmtools look for the end of December (`19501231235230`) instead of the end of January: the `restart_somefile_19500131235230` is in work.

Hence, `nyear` and `restart_unit` depend on each other and there are invalid combinations. 

**To Reproduce**
Run a default echam experiment with the runscript entries above.

**Expected behavior**
The `esm_runscripts` should check this during the `-c` process. Also, this should be written in the documentation.

**Comment by dbarbi** [comment]
They don't have to, that can be done by setting the nocycles var in namelist.echam. I wrote a first try for it, it is in branch echam_nocycles. No test done so far.

**Comment by JanStreffing** [comment]
echam_nocycles was never merged. Have you tried the solution proposed @chrisdane. Did it work? Is there still interest in this feature?

**Comment by pgierz** [comment]
Closing as this appears to be a stake issue and there is no more interest. Please re-open this and add appropriate labels if this should be pursued further.
