### ISSUE TITLE
different namelist.echam &runctl nproma why 

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#409]
**Describe the bug**
The namelist.echam entry `nproma` equals either 8 or 72, depending on the used scenario:
```
git checkout release
grep -ir nproma namelists/echam/
namelists/echam/6.3.02p4/1990/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.02p4/1950/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.02p4/RCP45/namelist.echam:    nproma = 8
namelists/echam/6.3.02p4/SCEN/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.02p4/RCP85/namelist.echam:    nproma = 8
namelists/echam/6.3.02p4/PALEO/namelist.echam:    nproma = 8
namelists/echam/6.3.02p4/PI-CTRL/namelist.echam:    nproma = 8
namelists/echam/6.3.02p4/1850/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.02p4/RCP26/namelist.echam:    nproma = 8
namelists/echam/6.3.04p1/HIST/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.04p1/1950/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.04p1/PALEO/namelist.echam:    nproma = 8
namelists/echam/6.3.04p1/PI-CTRL/namelist.echam:    nproma = 8
namelists/echam/6.3.04p1/1percCO2/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.04p1/4CO2/namelist.echam:  NPROMA         = 72
namelists/echam/6.3.05p2-foci/PI-CTRL/namelist.echam:    nproma = 32
namelists/echam/6.3.05p2-concurrent_radiation/PI-CTRL/namelist.echam:    nproma = 8
namelists/echam/6.3.05p2-concurrent_radiation/PI-CTRL/namelist.echam:    npromar = 8
namelists/echam/6.3.05p2-concurrent_radiation-paleodyn/PI-CTRL/namelist.echam:    nproma = 8
namelists/echam/6.3.05p2-concurrent_radiation-paleodyn/PI-CTRL/namelist.echam:    npromar = 8
```  
The echam docu says

> variable: nproma
type: integer
explanation: vector length of calculations in grid point space 
default: number of longitudes

**Expected behavior**
If its not clear for the esm tools which value nproma should take, it should not be set as it is very confusing (and potentially wrong).

**Comment by pgierz** [comment]
This is a holdover from when ECHAM was being run primarily on vector based machines. I remember in discussions with Martin Werner that it might not even be clear if this parameter has any meaning in the current ECHAM. I would, however, recommend unifying everything to use `nproma = 8`. I can do two test runs for 3 years to check if there is any sort of climate dependence if you change that number.... I'll post some graphics once those runs are done.

**Comment by pgierz** [comment]
Please see the PR #436 and re-open if needed.
