### ISSUE TITLE
Add simple installation/run tests with GitHub actions

### ISSUE THREAD

**Issue by koldunovn** [esm-tools/esm_tools#422]
I have added two versions of the tests in #421 :

`esm_tools_actions.yml` - uses the precreated Docker image. The advantage is one can use this Docker image to experiment locally and it's very stable, so you can make sure your model runs, if you decide to add them, will be binary identical. The disadvantage is - it is maybe too stable, and it's only one version of python you can check against.

`esm_tools_actions_novm.yml` - one can run different python versions and the containers are more lightweight, so things run a bit faster. The description of the `setup-python V2` action options: https://github.com/marketplace/actions/setup-python

I think it make sense to create your own organisation on Docker Hub for containers, if you decide to go this way, so here is the Docker file for `koldunovn/esm_test:latest` image, you can use it as a starting point to create your own.

```Dockerfile

FROM ubuntu:20.04
LABEL maintainer="koldunovn@gmail.com"

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-add-repository -y universe
RUN apt-get update

RUN apt-get -y install make gfortran gcc g++ libblas-dev libopenmpi-dev
RUN apt-get -y install cmake vim git git-lfs libnetcdf-dev libnetcdff-dev libpmi2-pmix
RUN apt-get -y install wget pip

WORKDIR /esm/
```

Looking forward for your thoughts and ideas! :)

**Comment by pgierz** [comment]
> The disadvantage is - it is maybe too stable, and it's only one version of python you can check against.

Yes, true. but we also aren't doing too many Python-version-specific things. If the docker image is based on Python 3.6, we should be on the safe side.

> I think it make sense to create your own organisation on Docker Hub for containers

I agree, and I'll look into that tomorrow. Does it maybe also make sense to store the Dockerfile directly along with the rest of esm-tools? Whenever I build docker/python web stuff, I just dump it in along with the rest of the code. I am unsure if that is best practice or not though....

**Comment by koldunovn** [comment]
@pgierz I use a separate repository for this for FESOM, but I see some people also include them in the repository. It's not a problem to merge or split afterwards, I guess :)

**Comment by koldunovn** [comment]
> Yes, true. but we also aren't doing too many Python-version-specific things. If the docker image is based on Python 3.6, we should be on the safe side.

It's actually `3.8.10`

**Comment by pgierz** [comment]
OK, so, a few things I discovered already:

* There is a GitHub action to automatically build containers. I had actually hacked together something that might have done this as well, but I would prefer to trust the pros. https://github.com/marketplace/actions/build-and-push-docker-images. So, @koldunovn, if you ever want to automatically have dockerized FESOM, that seems to be do-able. I'm not sure what the use case really would be for actual production simulations, though. 
* I will attempt to configure the CI to build a container with everything one would need for Python 3.6 through 3.9 on tag pushes, along with a weekly cron-build that just does whatever is currently in release and in develop. This doesn't look too difficult. We can add "we use docker" to the selling point list then 😁 
* Dockerhub has organisations, but they cost money. I can invent a dummy email account and share the login info with everyone, and then we can trick Dockerhub into thinking it is a personal version. I didn't really see the advantage of having organisations

**Comment by koldunovn** [comment]
@pgierz 

Thanks for the tip! Currently I also hardly see the use case for FESOM, but post processing tasks is a different story, the first candidate would be https://github.com/FESOM/fdiag . Singularity allows to just expose, for example `fdiag` command, that would be running fdiag in the container (well, you create an `fdiag` alias), but will look like a normal command for the user. In general having singularity container with pyfesom2 properly installed is not such a bad idea - both ollie and mistral have support for singularity containers. 

For the esm-tools containers I also don't see too much use without turning it into a service, that will be running in a container (and have extensive access to file system, which can be achieved through Singularity). Not sure how easy it would be to make everything work from the conternerised environment.

I would do just a personal account, and not many people need access to it as I don't see things are changing in the Docker images frequently. You might also thing of having registry on AWI GitLab https://docs.gitlab.com/ee/user/packages/container_registry/

**Comment by pgierz** [comment]
Please see also #435: I added style and syntax checks.

I recommend we go over this at our internal retreat, and then after agreeing on a strategy, we should put Nikolay's stuff in and close the issue.

**Comment by JanStreffing** [comment]
Any update on this issue after the last retreat?

**Comment by pgierz** [comment]
This can be closed. The standard CI currently does an install test on ubuntu and checks if `esm_master` works. There are ideas to expand it to include style checks, listing, and maybe run actual mini jobs on Ollie. I didn't get a chance to talk about that at the retreat, but I would rather do that in a new post.
