### ISSUE TITLE
OASIS3mct vs OASIS3-mct

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#45]
During the FOCI merge, I ended up with two spellings of oasis. Which one is correct?

`oasis3mct` or `oasis3-mct`???

**Comment by pgierz** [comment]
Corrected everything to `oasis3-mct`, and removed `oasis3mct`. @seb-wahl can you please do a pull of the `paul_prep` branch before you test the Kiel stuff and make sure your stuff still compiles?

**Comment by seb-wahl** [comment]
@pgierz done, see https://github.com/esm-tools/esm_tools/pull/46 it also covers the renaming of oasis3-mct impact on FOCI
