### ISSUE TITLE
Model cannot be compiled if a folder is assigned under .bash_profile

### ISSUE THREAD

**Issue by fernandadialzira** [esm-tools/esm_tools#453]
Machine: mistral
Version: 5.1.6

Steps to reproduce
1. under ~/.bash_profile I added a line to open my work folder directory ("cd /work/...)
2. tried to compile AWI-ESM2.1 under a direnv from git lfs (tutorial from: https://www.youtube.com/watch?v=tz0_tL04c9I&ab_channel=PaulGierz)

Model does not compile giving me the message that the component for oasis is missing. It happens because it is running in .bash_profile. When doing the same in ollie it works, probably because it runs under .bashrc

I deleted the line I added on bash_profile and it worked. 
@pgierz @mandresm

**Comment by pgierz** [comment]
So, the quick solution is to temporarily modify the bash login, which we did

I would recommend that we wait until I get the automatic test up and then we try to remove the -l part. Hopefully I will finish that tomorrow.

If everything still works for all the models, we put it in.

**Comment by JanStreffing** [comment]
Is this issue still open?

**Comment by fernandadialzira** [comment]
@JanStreffing I am not sure whether it is still open, but I have to modify my bash profile whenever I want to compile any model still (either on ollie or mistral).

Normally, at the end of my `.bash_profile` I have: 

```
conda init --all
. ~/.bashrc
cd ${WORK}
conda activate fernanda_base
module load git
module load python3
``` 
and in order to compile any model I have to comment the 4 first lines...

**Comment by mandresm** [comment]
What about deactivating conda before running `esm_master` (or any ESM-Tools command)?
`conda deactivate`. Does that get the job done?

**Comment by pgierz** [comment]
I think this can safely be closed, it was a rather old problem Fernands had when initially starting out.

**Comment by denizural** [comment]
As @fernandadialzira mentioned that again in today's workshop, I am reopening it again. @pgierz, it looks like Fernanda is still having this issue.

**Comment by denizural** [comment]
We worked with @fernandadialzira and replaced all executable commands (eg. `cd`, `conda activate`, ...) with Linux aliases. We are having these commands in the `.bash_profile` instead of `.bashrc` because `.bash_profile` is the script that is executed when someone logs in for the first time.
Now we can close the issue safely 😃
