### ISSUE TITLE
gitstatus of .venv_esmtools

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#471]
**Is your feature request related to a problem? Please describe.**
Without a gitstatus or similar in an arbitrary `.venv_esmtools` directory, its hard to see which branches/tags/versions were used.

**Describe the solution you'd like**
A gitstatus or similar of every bin in a `.venv_esmtools` dir.

**Comment by JanStreffing** [comment]
This issue was not picked up. Is there any interest? @pgierz @mandresm @denizural ?

**Comment by pgierz** [comment]
This looks simple enough to implement. I'll have a look.
