### ISSUE TITLE
copy model source code to experiment directory

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#472]
**Is your feature request related to a problem? Please describe.**
By using branches instead of directories, the model code used for an experiment might change although its path stays constant. This may cause confusion when comparing model simulations with different model code but the same path to the model code (at least it happened to me). 

**Describe the solution you'd like**
One solution would be a clever workflow of the modeling person.
To help that person, another option may be copying all source code files to the experiment directory when initializing the experiment.

**Comment by JanStreffing** [comment]
I'm not sure the safety we gain is worth copying a few hundred to a few thousand files into every run dir. We seem to be running in full disks (in terms of file count) on some machines already, and we are actually trying to reduce the number of files produced by esm_tools. 

I agree pointing to the same source code folder that you compared different branches in can be confusing. But I would also say that good descriptive experiment naming can overcome most of the ambiguity. 

At the moment we are not very interested in adding this functionality.

**Comment by chrisdane** [comment]
Ok but information about the used model(s), at least `git status`, could be included here: https://github.com/esm-tools/esm_tools/issues/471.

**Comment by JanStreffing** [comment]
yes git status and perhaps a git diff too would be much less extra data. @pgierz @denizural @mandresm
