### ISSUE TITLE
esm_runscript long run issue

### ISSUE THREAD

**Issue by EnricoDeg** [esm-tools/esm_tools#474]
Hello,

I'm trying to set up a **2 years** run of AWI-CM with the ESM-tools but when the second year starts, the simulation crashes because some input files are missing. I think that the problem is with the ```esm_runscript``` command or with my ```yaml``` file.

The experiment is based on this Gitlab project:

https://gitlab.awi.de/paleodyn/Projects/technical/processor-partitioning

You can find my folder on Mistral here:

```/work/bk0993/k202136/processor-partitioning```

I'm currently using this yaml file to set up the experiment:

```/work/bk0993/k202136/processor-partitioning/run_part_2424_ori.yaml```

**Comment by denizural** [comment]
Hi @EnricoDeg could you also paste the output of the `esm_versions check` command so that we can see which version you are using.

**Comment by EnricoDeg** [comment]
Here is the result of ```esm_version check```

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_environment
├─ version: 5.1.1
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_master
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_parser
├─ version: 5.1.8
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:


esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_runscripts
├─ version: 5.1.28
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

esm_tools
├─ version: 5.1.16
├─ path: /mnt/lustre01/work/bk0993/k202136/processor-partitioning/software/github.com/esm-tools/esm_tools
├─ branch: DETACHED at 2d61dd4
└─ tags: v5.1.16-4-g2d61dd4-dirty

esm_version_checker
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/k/k202136/.local/lib/python3.6/site-packages
├─ branch:
└─ tags:

**Comment by EnricoDeg** [comment]
You can have a look at the log file. Here you can find the error at line 65044:

```/work/bk0993/k202136/processor-partitioning/experiments/2y/scripts/2y_compute_20000101-20011231_32709913.log ```

The problem is that at the beginning of a new year, the file ```aero_coarse``` is read at the previous, current and next year. In the work folder, you can see that only the files for 1999, 2000 and 2001 are included, thus the file for 2002, which is read for the first time at the beginning of year 2001, is not included. This same problem applies also to other files.

I'm currently using ```echam-6.3.05p2```, the original release. You can find a version here: 

```/work/bk0993/k202136/processor-partitioning/model_codes/awiesm-2.1/echam```

In file

```/work/bk0993/k202136/processor-partitioning/model_codes/awiesm-2.1/echam/src/echam/mo_aero_kinne.f90```

at lines 128-165 you can see how the ```aero_coarse``` files are read every time a new year is started.

**Comment by JanStreffing** [comment]
This seems to have been a pool issue. 

```
  0: FATAL ERROR in aero_read_opt: file aero_coarse_2002.nc does not exist
  0:  FINISH called from PE: 0
```
There has been no movement on this issue for half a year. It seems the user has given up on trying to run a 2y awi-esm-2.1 simulation due to lack of support on pool issues from our side. I will internally raise the issue of who is responsible for pool dir support after the departure of the previous maintainer a while ago. I think this issue can not be solved here. 

I will thus close here.

**Comment by EnricoDeg** [comment]
From my understanding, this is not a pool issue but a lack of flexibility in the run script. It is sufficient to have a loop where for each simulated year, the correct files are copied to the work folder, and then everything should work.
