### ISSUE TITLE
More flexible name for loading data into pyfesom2 or adapting esm_tools to pyfesom2 nameing convention

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#499]
Currently esm_tools move FESOM2 output files into an output folder and rename them from eg.
ist.fesom.1992.nc to ist.fesom.199201.01.nc. The reason is that FESOM2 normally keeps everything in the work folder in between runs. Thus if a run is less than one year long, FESOM2 just keeps adding timesteps to the output files. Esm_tools on the other hand moves all files into outdata/fesom/. Therefore it would overwrite the existing file. The solution was to give an this additional string.

pyfesom2 does not find these files when operating e.g. inside fdiag. At the moment users that produce FESOM2 data with esm_tools that read the data via pyfesom2 handle this case with bash scrips that rename the files. We can do better. Which side should be changed, esm_tools or pyfesom2?

See also: https://github.com/FESOM/pyfesom2/issues/162

**Comment by mandresm** [comment]
This is already taken care in `monorepo` branch:

https://github.com/esm-tools/esm_tools/blob/c5a4acb038e1f4cc48d9d56c2278f47d23fef935/configs/components/fesom/fesom-2.0.yaml#L154-L157

If you need it now for AWICM3 branches you can go ahead and change it there too.

**Comment by JanStreffing** [comment]
That's great to hear. 
@tsemmler05 Maybe you can try this out for your next simulation. This would save us the script usage.
