### ISSUE TITLE
Error in installing of awiesm-2.1-wiso

### ISSUE THREAD

**Issue by AhmadrezaMasoum** [esm-tools/esm_tools#529]
I was installing 'awiesm-2.1-wiso' on my Ollie, but the below errors came up:
............................................................................................................................
echam/control.o: In function `control_':
control.f90:(.text+0x4d9): undefined reference to `readtagmap_'
make[2]: *** [echam6] Error 1
make[2]: Leaving directory `/work/ollie/amasoum/esm_tools/awiesm-2.1-wiso/echam-6.3.05p2-wiso/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/work/ollie/amasoum/esm_tools/awiesm-2.1-wiso/echam-6.3.05p2-wiso/src'
make: *** [all-recursive] Error 1
Traceback (most recent call last):
  File "/home/ollie/amasoum/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/home/ollie/amasoum/.local/lib/python3.7/site-packages/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/home/ollie/amasoum/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 84, in main_flow
    user_task.execute(ignore_errors) #env)
  File "/home/ollie/amasoum/.local/lib/python3.7/site-packages/esm_master/task.py", line 492, in execute
    shell=(command.startswith("./") and command.endswith(".sh")),
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./comp-echam-6.3.05p2-wiso_script.sh']' returned non-zero exit status 2.
.....................................................................................................................................
How can I fix this problem?

Thanks,
Ahmadreza

**Comment by mandresm** [comment]
Hi @AhmadrezaMasoum, I got also this problem doing some testing yesterday. I think this is not a problem with ESM-Tools but with the last change that happened in this branch of ECHAM: I tried getting the previous commit to the last and I could compile it, with the last commit I get the same error as you did.

@xshi-awi , do you know what's the problem?

**Comment by mandresm** [comment]
Hi again, I think @xshi-awi has already fix it. I recommend that you delete the `awiesm-2.1-wiso` folder and try the compilation again. Please, close the issue if it works now.

**Comment by AhmadrezaMasoum** [comment]
> Hi again, I think @xshi-awi has already fix it. I recommend that you delete the `awiesm-2.1-wiso` folder and try the compilation again. Please, close the issue if it works now.

Hi,
Thank you. I have installed it successfully.
Best
