### ISSUE TITLE
esm_tools 6: Problem to start PISM "Invalid numeric value 0 for --ntasks"

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#543]
**Describe the bug**
I get this error message when I want to submit a PISM job:

```
resubmit tasks: 0
Submitting jobscript to batch system...

Output written by slurm:
sbatch: error: Invalid numeric value "0" for --ntasks.
```

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version: esm_tools version 6

**Additional context**
Here is a path to an experiment: `/work/ba0989/a270124/PalModII/experiments/pism_test03`

**Comment by mandresm** [comment]
Hi @ackerlar ,

Could you please let me know in which branch are you currently trying this? Then I'll try to debug it, basically the problem is for some reason it is calculating the wrong number of tasks (0 tasks in total).

**Comment by ackerlar** [comment]
It is on the `release` branch.

**Comment by mandresm** [comment]
`ackerlar:release` after you merged `ackerlar:release` <- `ackerlar:prep_release_wiso`?

**Comment by ackerlar** [comment]
I tried with both: `release` and `feature/awiesm-pism` where I merge `ackerlar:prep_release_wiso` into.

**Comment by mandresm** [comment]
okay, thanks

**Comment by mandresm** [comment]
I think commit acffcfa should fix the problem: choices inside a choose should be strings. I guess this is not a nice behavior as many users will fall (and are already falling) into this trap. So I am working on a more permanent fix for this.

**Comment by ackerlar** [comment]
Thanks, it works!
