### ISSUE TITLE
Logfiles of crashed runs are overwritten in release 6

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#548]
With release 6 the stdout stderr  logfiles produced by the queueing system no longer end up in scripts/ but in log/, and their names changed. They used to have the queueing systems jobid in the name, now they dont.

Old: `paleo_speedtest_8_compute_19900101-19901231_11778301.log`
New: `defuse_sea_alb_005_awicm3_observe_compute_20100101-20191231.log`

If a job crashes, and I restart it via e.g. `sbatch my_run_script.run`, the old system would make a second logfile. The new system overwrites the old logfile. This is hazardous if the run crashes again, as we can not show to HPC support that an error is reproducible. 

We need to store logfiles with jobids.

**Comment by JanStreffing** [comment]
I just tested this. It does not actually overwrite. But it wont start up either:

```
===============================================================================
::: Executing the step:  init_monitor_file    (step [1/3] of the job:  observe)
===============================================================================
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 30, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/ollie/jstreffi/esm_tools/src/esm_runscripts/cli.py", line 268, in main
    Setup()
  File "/home/ollie/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 79, in __call__
    self.observe()
  File "/home/ollie/jstreffi/esm_tools/src/esm_runscripts/sim_objects.py", line 111, in observe
    self.config = observe.run_job(self.config)
  File "/home/ollie/jstreffi/esm_tools/src/esm_runscripts/observe.py", line 12, in run_job
    helpers.evaluate(config, "observe", "observe_recipe")
  File "/home/ollie/jstreffi/esm_tools/src/esm_runscripts/helpers.py", line 62, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/jstreffi/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/ollie/jstreffi/esm_tools/src/esm_runscripts/observe.py", line 53, in init_monitor_file
    os.symlink(exp_log_path, log_in_run)
FileExistsError: [Errno 17] File exists: '/work/ollie/jstreffi/runtime/awicm3-frontiers//defuse_sea_alb_005/log/defuse_sea_alb_005_awicm3_compute_20100101-20191231.log' -> '/work/ollie/jstreffi/runtime/awicm3-frontiers//defuse_sea_alb_005/run_20100101-20191231/log/defuse_sea_alb_005_awicm3_compute.log'
```

**Comment by pgierz** [comment]
Seems like the relevant lines to append the PID/Slurm ID were commented:

https://github.com/esm-tools/esm_tools/blob/64834b0a23b84cc9604857e0fdb5bf7b8145127f/src/esm_runscripts/observe.py#L47-L48

git blame says I did that, but that was also probably happening at some point via the `black` code formatting, so I am unsure if that was actually me or me just cleaning up...

**Comment by mandresm** [comment]
Yeah, I think that was part of the workflow rework done by Dirk. I'm wondering if it got commented out because it was giving problems with the workflow manager... In any case, I will try bringing those lines back.

**Comment by mandresm** [comment]
This is solved now, so I'll proceed to close it.
