### ISSUE TITLE
automatic test for model instability (high windspeed) produces wrong positive results

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#57]
**Description of the problem:**
The esm-tools come with functionality that detects potential instability of the atmosphere simulation. To this end atmout is parsed for messages of the form:
```
WARNING! high wind speed: 236. m/s
Level:    5 NSTEP=    32019
```
Unfortunately, occurrence of these messages is not a sufficient condition for model instability, which apparently the current implementation of the functionality wrongly assumes to be the case. 

Occasionally, such warnings may occur for a short period of time after which the model stabilizes again without a blowup. Still, in the current implementation the esm-tools will interpret any detection of such warnings in atmout as a sign of model instability and kill the run regardless of its potential ability to stabilize again. Due to issue #56 the restart attempt will not work and hence the functionality of detecting and fixing model instability automatically contains currently a severe bug that actually leads to a crash and the inability to continue a simulation (as issue #58 is present) in cases where the model by itself would have worked without any problem.

The issue is illustrated at the example of the following simulation:

- During the day of the 15th of June there is a limited number of high wind speed warnings (see [atmout](https://1drv.ms/u/s!AnZSDMNwdkDMgbcsRoNBjy9sso1BIQ)
- after that the simulation contains sanely for another 15 days until 1st of June (see again [atmout](https://1drv.ms/u/s!AnZSDMNwdkDMgbcsRoNBjy9sso1BIQ))
- at 1st of July the esm-tools kill the simulation (see [PI_ctrl_AWI-ESM-2-1_compute_20080101-20081231_6235809.log](https://1drv.ms/u/s!AnZSDMNwdkDMgbctkf2MYZhioXsFpA?e=ymVy8D)):
```
ERROR: high wind speed was found during your run, applying wind speed fix and resubmitting...
Will kill the run now...
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
432:  Fluxes have been modified.
srun: got SIGCONT
  0: slurmstepd: error: *** STEP 6235809.0 ON prod-0090 CANCELLED AT 2020-06-18T21:15:12 ***
slurmstepd: error: *** JOB 6235809 ON prod-0090 CANCELLED AT 2020-06-18T21:15:12 ***
srun: forcing job termination
srun: error: prod-0103: tasks 396-431: Exited with exit code 1
srun: Terminating job step 6235809.0
```
**Suggested solution**
Find a robust way for detection of model instability and update the esm-tools functions accordingly. Until then, disable the method per default in order to not obstruct usability of the esm tools. Disabling the method by default can be done by editing ~/esm-tools_v4/esm_tools/configs/echam/echam.yaml and commenting out the following lines:
```
         "wind speed":
                 method: "kill"
                 message: "high wind speed was found during your run, applying wind speed fix and resubmitting..."
                 file: "${general.work_dir}/atmout"
                 frequency: 90

```

**employed run script (on Ollie):**
[PI_ctrl_AWI-ESM-2-1.yaml](https://1drv.ms/u/s!AnZSDMNwdkDMgbcuBKwMqMkFf6b2gg?e=Nht5FU)

**employed esm_tools versions:**
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.1
esm_database : 4.0.0
esm_environment : 4.0.1
esm_master : 4.0.2
esm_parser : 4.0.2
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.0.3
esm_tools : 4.0.9
esm_plugin_manager : 4.0.1
esm_version_checker : 4.0.2

**Comment by pgierz** [comment]
This is actually just looking for the wrong string. We should instead look for "lookup table overflow" in the log file. The following python script may be used as a template for wind speed checks:

https://gitlab.awi.de/paleodyn/Utilities/technical_model_utils/-/blob/master/check_for_windspeed.py
