### ISSUE TITLE
Add documentation to alternative method of esm-tools installation devised by @pgierz

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#585]
**Request/contribution description**
Paul Gierz devised an alternative way of downloading and installing esm-tools that may be particularly appropriate if one is focused on using the tools and not so much focused on working under the hood. As far as I understand, a lot of the configuration is compiled and cannot be easily modified (which has advantages and disadvantages, but the advantage is certainly the fact that there are no more "local modifications" that my make error searching difficult - maybe @pgierz can comment on that). Yet, the biggest advantage is that direnv is part of the installation method, which enables encapsulation and peaceful coexistence of various versions of esm-tools. A topic that is per standard not given, as each esm-tools version always wants to reside in ~/.local as per preconfiguration.

Here are the installation commands that could be presented in the documentation (for example at the "Ten steps to a working model" section):
```
$ curl -sfL https://direnv.net/install.sh | bash # install direnv if not yet done - this enables encapsulation and parallel use of different esm-tools versions
$ mkdir esm_tools_v6.1.10 #adjust version number as appropriate
$ cd esm_tools_v6.1.10/
  #create .envrc (e.g. via direnv edit .) and add information matching the result of the cat command below
$ cat .envrc
  module load python3
  layout python
  module load gcc
$ pip install -U pip wheel
$ pip install esm-tools
```

**Suggested chapter/section in the documents**
Ten steps to a running model setup, alternative locations where the installation of the tools is explained.

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
Applies to ESM-tools in general.

**Contribution**
Maybe @pgierz can comment on the suggested documentation text provided below.

Based on an alternative installation procedure, that provides an esm-tools installation employing direnv (https://direnv.net/), you can now install various encapsulated versions of esm-tools alongside each other. These different installations do not impact each others' configuration. Consequently, they can coexist in peaceful harmony. In the suggested alternative installation method all configurations will reside within the base folder of a specific esm-tools version that you install. There is no dependency on configurations outside the installation directory of a specific esm-tools version, mitigating the potential for side effects if another version of esm tools is installed in parallel. To install esm-tools as suggested here, just follow the procedure outlined below. The steps to create the installation involve preparation of direnv, including setting up an environment that encapsulates potentially version-specific settings, creating a dedicated directory to which a specific version of esm-tools will be installed, and installing the the esm-tools via pip.
The commands to be executed are (note comments for further explanation):
```
$ curl -sfL https://direnv.net/install.sh | bash # install direnv if not yet done - this enables encapsulation and parallel use of different esm-tools versions
$ mkdir esm_tools_v6.1.10 #adjust version number as appropriate
$ cd esm_tools_v6.1.10/
  #create .envrc (e.g. via direnv edit .) and add information matching the result of the cat command below
$ cat .envrc
  module load python3
  layout python
  module load gcc
$ pip install -U pip wheel
$ pip install esm-tools
```

**Comment by pgierz** [comment]
Alright I tried to reply directly to the bot in Webex with the hope that my comment would appear here, but I guess not, so:

“compiled” is perhaps a misnomer here. It’s just a pip install and rather than pointing to a local folder, you point to the PyPI repository online. The source is still there in plain text, it is just hidden in Python’s library of site-packages This is typically well enough hidden that an average user will not know to look there, and thus reasonably safe.

I agree that this should be documented, but I am unsure when there shall be time for this.
As to the direnv part: this we should certainly expand upon. I am considering creating a tutorial video for that, as it has many more use cases beyond just esm-tools.

**Comment by pgierz** [comment]
I particularly enjoy:

> Consequently, they can coexist in peaceful harmony.

😁

**Comment by christian-stepanek** [comment]
@pgierz  " agree that this should be documented, but I am unsure when there shall be time for this." - Do you mean this should be further tested before being documented? Or do you think there is no time for writing the documentation? If the latter, then maybe my few lines can be added to the docu as a start, and one can elaborate when there is time.

@pgierz To your remark to "Consequently, they can coexist in peaceful harmony." To my understanding this is the biggest asset. I have always been annoyed by the fact that new versions of esm-tools try to get rid of old versions of esm-tools. There may be specific cases when I explicitly want to maintain an old version. And sometimes that has discouraged me from frequently updating esm-tools, I just want to be sure that a new installation does not break anything of the old installation.

**Comment by pgierz** [comment]
>  If the latter, then maybe my few lines can be added to the docu as a start, and one can elaborate when there is time.

That's a good start. See #586

**Comment by mandresm** [comment]
> I have always been annoyed by the fact that new versions of esm-tools try to get rid of old versions of esm-tools. There may be specific cases when I explicitly want to maintain an old version. And sometimes that has discouraged me from frequently updating esm-tools, I just want to be sure that a new installation does not break anything of the old installation.

Just a note to that, we are aware of this problem, and the first step for solving it was to put all the packages in the same repository for version 6, so if you decide to go for example, for using esm_tools 6.1.0, then all the packages are the ones for that version. The next step is to have a better strategy for virtual environments or `direnv`. For that we still need some time to think about the best strategy, but I agree that having a "how to do it manually" is a good start, so thanks for your contribution :) I'll have a look at the docs in #586 and test that the instructions work for me too.
