### ISSUE TITLE
Input_dir in runscript does not overwrite what is in oifs.yaml

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#6]
Hi all
I've put together a runscript for OpenIFS 40r1 standalone. From what I can see it sets the proper bin_dir and copies the binary to the work dir, but all other directories fail. 
The problem is that even though I've written 
input_dir=/work/bb0519/foci_input2/OPENIFS40R1-TL159/
in the runscript, the input_dir that is used is still what is in the oifs.yaml which is
input_dir: ${pool_dir}

But shouldn't settings in the runscript overwrite what is in configs/oifs/oifs.yaml? 
In the old bash version we had things like "INPUT_DIR=${INPUT_DIR:-/work/bb0519/oifspool}" so that it would use INPUT_DIR from the runscript if it existed, otherwise default to the standard data pool. 
But now it seems to always default to what is in oifs.yaml. 

The runscript is in 
runscripts/tested_runs/oifs-40r1-mistral-initial-daily.run
and I've tested this on Mistral. It's all in the "foci2" branch. 

Many thanks for any help!
/Joakim

**Comment by dbarbi** [comment]
Hi Joakim,
is this still a problem? If so, can you please send me the output of 'esm_versions check', so that I can use the same packages? I think it might be solved already...

**Comment by joakimkjellsson** [comment]
Hi Dirk

I think this has been solved somehow. Probably some update of esm_runscripts or so.
Feel free to close the issue. 

Cheers
Joakim
