### ISSUE TITLE
default fesom and recom *_outputs not combined if no further_reading

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#614]
**Describe the bug**
When I run the setup `awicm-1.0-recom` I must provide  
```
fesom:
    further_reading: "fesom_recom_outputs.yaml"
```
in the runscript to specify both fesom and recom output variables. 

If I do not provide this further reading file, fesom crashes in the first time step since the recom variable bgc01 (and all other recom variables) is not defined in the default variable list of fesoms OutputSchedulerManager.cpp:
```
795: terminate called after throwing an instance of 'std::runtime_error'
795:   what():  /mnt/lustre01/pf/a/a270073/esm/awicm-1.0-recom/fesom-1.4/fesom_cpl/output_scheduler/OutputSchedulerManager.cpp:98 unknown output schedule: bgc01
```

**To Reproduce**
Start a default `awicm-1.0-recom` experiment without the runscript entry
```
fesom:
    further_reading: "fesom_recom_outputs.yaml"
```

**Expected behavior**
The union of all default `*_outputs`-entries, e.g.
```
fesom.yaml
monthly_outputs: [evs,fsitherm,hfds,opottemptend,pbo,prlq,prsn,rsdo,siarean,siareas,sidmassevapsubl,sidmasssi,sidmassth,sidmasstranx,sidmasstrany,siextentn,siextents,sifllatstop,sisnconc,sisnmass,sisnthick,sispeed,sivol,sivoln,sivols,soga,thetaoga,u2o,uo,uso,uto,v2o,vo,volo,vso,vto,w2o,wfo,wo,wso,wto,zossq,rho,uhice,uhsnow,urho,uv,vhice,vhsnow,virtual_salt,vrho]

recom.yaml
monthly_outputs: [diags3d01,diags3d02,CO2y,aCO2,rDIN,rDON,rDOC,rDSi,PAR,NPPn,NPPd,GPPn,GPPd,NNAn,NNAd,GNAn,GNAd,benCalc,benSi,benC,benN,denb,aN,aFe,Hp,CO2f,dpCO2s,pCO2s,bgc01,bgc02,bgc03,bgc04,bgc05,bgc06,bgc07,bgc08,bgc09,bgc10,bgc11,bgc12,bgc13,bgc14,bgc15,bgc16,bgc17,bgc18,bgc19,bgc20,bgc21,bgc22,slp,age01,Kw,alphaCO2,O2f]
```
should be used if no further reading file is provided.

**System (please complete the following information):**
 - Supercomputer: mistral
 - esm_tools:
```
version = esm_tools, version 6.1.3
branch  = feat/ssp585_awicm-recom_v6
hash    = 9c076e66
src     = /mnt/lustre01/pf/a/a270073/esm/esm_tools
```

ps: fesom makes it additionally difficult since all default fesom variables defined in OutputSchedulerManager.cpp MUST be included once in any of the *_outputs. If e.g.
```
cat fesom_recom_output_test.yaml
daily_outputs: []
12_step_outputs: []
monthly_outputs:
    # fesom:
    - tos
    # recom:
    - bgc01
yearly_outputs: []
```
fesom also crashes since not all default variables are covered.

**Comment by denizural** [comment]
Hi @chrisdane,

Fesom requires the list of output variables along with the output frequency (eg. daily, hourly, ...). Fesom is very strict with that.

We separete the main runscript and the output list into two yaml files and link the output yaml file into the main one via `further_reading`. The advantage is your runscript is shorter and less cluttered.

If you want to drop the output yaml file then you need to add the information provided there into your main runscript. 
Does this solve your solution?

**Comment by chrisdane** [comment]
No. 

The problem is that the default is not working: if the user does not provide the output at all, neither via runscript, nor via further_reading, the defaults from the fesom.yaml and recom.yaml should be used. Both of them. The union. I wrote exactly that in "expected behavior".

This does not happen. The recom defaults get lost.

**Comment by denizural** [comment]
The commit f7ebe98cf1d047139385d600378376e3563f01d2 should solve this issue. I added the required fields to `awicm_recom` configuration and tested them against previous runs.

**Comment by chrisdane** [comment]
Yep
