### ISSUE TITLE
AWI-ESM: Identify what is currently being used

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#630]
In the end, the `ECHAM` branch will be `echam-6.3.05p2-awiesm-2.1` and the `FESOM` branch will be `2.1-awiesm-2.1` (always written as `<model_number>-<setup_name>-<setup_number>`. To give correct update instructions, we need to see what people currently have and double check if all the merges went through correctly on the `FORTRAN` side.

Currently, the following is being used:

| User | ECHAM | FESOM | OASIS | Tools | Machine |
|------|-------|-------|-------|-------|---------|
| @fernandadialzira| [`wiso`](https://gitlab.awi.de/paleodyn/Models/echam6/-/tree/wiso) | [`wiso`](https://github.com/FESOM/fesom2/tree/wiso) | ?? | [`fix/awiesm_default_variant`](https://github.com/esm-tools/esm_tools/tree/fix/awiesm_default_variant) | `ollie` |
| @lackerma| [`ice-addhosing`](https://github.com/FESOM/fesom2/tree/ice-addhosing) | `paleodyn/awiesm-2.1-gamma` | ?? | [`feat/dual_hemisphere`](https://github.com/esm-tools/esm_tools/tree/feat/dual_hemisphere) | `ollie` |
|  @lackerma| [`ice-addhosing`](https://github.com/FESOM/fesom2/tree/ice-addhosing) | `paleodyn/awiesm-2.1-gamma` | ?? | [`fix/icb_fesom_namelist`](https://github.com/esm-tools/esm_tools/tree/fix/icb_fesom_namelist) | `ollie` |
|  @lackerma| [`ice-addhosing`](https://github.com/FESOM/fesom2/tree/ice-addhosing) | `paleodyn/awiesm-2.1-gamma` | ?? | [`feat/dual_hemisphere`](https://github.com/esm-tools/esm_tools/tree/feat/dual_hemisphere) | `mistral` |
|  @lackerma| [`ice-addhosing`](https://github.com/FESOM/fesom2/tree/ice-addhosing) | `paleodyn/awiesm-2.1-gamma` | ?? | [`fix/icb_fesom_namelist`](https://github.com/esm-tools/esm_tools/tree/fix/icb_fesom_namelist) | `mistral` |
| @xshi-awi | [`wiso`](https://gitlab.awi.de/paleodyn/Models/echam6/-/tree/wiso) | `paleodyn/awiesm-2.1-gamma` | ?? | wiso_icb | `ollie` |
| @PengyangSong  | [`wiso`](https://gitlab.awi.de/paleodyn/Models/echam6/-/tree/wiso) | [`wiso-2.1`](https://github.com/FESOM/fesom2/tree/wiso-2.1) | ?? | [`release`](https://github.com/esm-tools/esm_tools/tree/release) | `ollie` |
| @niceniulu | [`ice-addhosing`](https://github.com/FESOM/fesom2/tree/ice-addhosing) | [`wiso`](https://github.com/FESOM/fesom2/tree/wiso)| ?? | `pre_release_wiso` | `ollie` |

| ECHAM Branch | Merge Status | FESOM Branch | Merge Status |
|--------------|--------------|--------------|--------------|
| [`ice-addhosing`](https://github.com/FESOM/fesom2/tree/ice-addhosing)| Already up-to-date | [`wiso`](https://github.com/FESOM/fesom2/tree/wiso) | Already up-to-date |
| [`wiso`](https://gitlab.awi.de/paleodyn/Models/echam6/-/tree/wiso)         | Automatic merge results in conflicts, these have been solved by hand | `paleodyn/awiesm-2.1-gamma` | Doesn't exist on [GitHub](https://github.com/FESOM/fesom2) Repo?? |
| | |[`wiso-2.1`](https://github.com/FESOM/fesom2/tree/wiso-2.1) | Able to merge automatically, but contains **many** changes. See https://github.com/FESOM/fesom2/pull/326 |

**Comment by fernandadialzira** [comment]
Oasis currently does not have a branch, I guess... And my tools is `fix/awiesm_default_variant` :)

**Comment by pgierz** [comment]
Thanks @fernandadialzira. We are almost done testing the unified AWIESM stuff (see #623), and the last stage will be to figure out who is using what so I can write adequate update instructions.

**Comment by mandresm** [comment]
Looking at the table, I'm a bit confused. Wasn't it the case that almost everything (except for REcoM) was merged into the `2.1-awiesm` branches?

**Comment by pgierz** [comment]
yes, that's where people should be going to. Here, I just want to find out what people are using right now before we show them how to switch.

**Comment by pgierz** [comment]
I updated the main description, hopefully it is now clearer.

**Comment by niceniulu** [comment]
For me, I use 
ECHAM: ice-addhosing,  FESOM: wiso , OASIS: ?? , Tools: pre_release_wiso from Lars, Machine: Ollie
Thanks!
Lu

**Comment by pgierz** [comment]
@xshi-awi or @lackerma could you let me know which remote you have for your FESOM version? It does not seem to be the GitHub repo.

**Comment by xshi-awi** [comment]
> @xshi-awi or @lackerma could you let me know which remote you have for your FESOM version? It does not seem to be the GitHub repo.

commit e53d57d42ab135db14790254f624360798c14a23 (HEAD -> paleodyn/awiesm-2.1-gamma, origin/paleodyn/awiesm-2.1-gamma)
Merge: adc6b79 c123277
Author: lackerma <lars.ackermann@awi.de>
Date:   Tue Mar 8 23:47:00 2022 +0100

    Merge branch 'paleodyn/awiesm-2.1-gamma' of https://gitlab.dkrz.de/FESOM/fesom2 into paleodyn/awiesm-2.1-gamma

**Comment by pgierz** [comment]
Thanks Xiaoxu! I am almost done with the ECHAM problem, too. I will solve that first and then see if the merge causes any difficulties. I might be in touch with you or with @ackerlar later in the afternoon.

**Comment by ackerlar** [comment]
Hi @pgierz 
Sorry, this is my version: `https://gitlab.dkrz.de/FESOM/fesom2/-/tree/paleodyn/awiesm-2.1-gamma`

**Comment by pgierz** [comment]
Hi @ackerlar,

thanks. Are there unstaged changes, or is everything pushed?

**Comment by ackerlar** [comment]
Now, everything is pushed. The last commit is some minutes ago, though.

**Comment by pgierz** [comment]
OK, I still have some echam things to work out at the moment, so I won't get to FESOM until after lunch break anyway. Thanks!

**Comment by pgierz** [comment]
I think we have everything in one place now; so I will close this. Please re-open if you are confused about which version you should use:

* ECHAM: Use gitlab.awi.de, with branch `6.3.05p2-awiesm-2.1`
* FESOM: Use GitHub.com, with branch `2.1-awiesm-2.1`
* OASIS: Use gitlab.awi.de, with branch `2.8mct-awiesm-2.1`
