### ISSUE TITLE
Combine Echam Versions

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#631]
A combined version of all the various `ECHAM-6.3.05p2` versions will be needed in order to ship one unified `AWIESM-2.1`.

This has been finished and the model may be found here:
https://gitlab.awi.de/paleodyn/Models/echam6

**Comment by pgierz** [comment]
Already finished.

**Comment by seb-wahl** [comment]
well but we still need to keep the GEOMAR version `ECHAM-6.3.05p2`!!! I'm sure it differs in various places from yours.

**Comment by pgierz** [comment]
Hi @seb-wahl: sorry, this was perhaps unclear: here I **only** mean ECHAM versions relevant for out AWI-ESM. If we start doing cross-setup one single ECHAM only I am sure all hell would break lose 😉
