### ISSUE TITLE
workaround for bug in f90nml package

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#633]
**Describe the bug**
The package f90nml (https://github.com/marshallward/f90nml) used by ESM-Tools has a bug (https://github.com/marshallward/f90nml/issues/110) which means it cannot handle certain types of namelists correctly. Unfortunately we have such namelists (which are valid fortran namelists) sometimes with NEMO in FOCI and
```fortran
   sn_tracer(1)   = 'DET'   , 'Detritus                   '  , 'mmole-N/m3' ,  .false.
   sn_tracer(2)   = 'ZOO'   , 'Zooplankton concentration  '  , 'mmole-N/m3' ,  .false.
   sn_tracer(3)   = 'PHY'   , 'Phytoplankton concentration'  , 'mmole-N/m3' ,  .false.
```
is turned into
```fortran
sn_tracer(1:3)   = 'DET', 'ZOO', 'PHY'
```
by f90nml together with warnings (see https://github.com/marshallward/f90nml/issues/110 for details)

**Workaround**
Since it seems to be difficult to fix this in f90nml (see discussion at https://github.com/marshallward/f90nml/issues/110) a workaround is to rewrite the problematic section by using named entries in the namelist. To do so, you need to look up the names in the source code. In the above test case I was able to produce a workaround with
```yaml
namelist_changes:
      namelist_top_cfg:
        namtrc:
           sn_tracer: "remove_from_namelist"
           sn_tracer(1)%clsname: DET
           sn_tracer(2)%clsname: ZOO
           sn_tracer(3)%clsname: PHY
           sn_tracer(1)%cllname: "Detritus"
           sn_tracer(2)%cllname: "Zooplankton concentration"
           sn_tracer(3)%cllname: "Phytoplankton concentration"
           sn_tracer(1:3)%clunit: "mmole-N/m3"
```
But maybe one of us is able to actually fix this in f90nml correctly, but I doubt that we have time to do this...

**Comment by seb-wahl** [comment]
FYI @pgierz @mandresm @JanStreffing in case you hit the same bug...

**Comment by pgierz** [comment]
Hi @seb-wahl, yeah I saw this. I don't think anything in ECHAM or FESOM currently uses this style of namelist. Out of curiosity, what does this translate to? A 3x4 array?
```
[
['DET'   , 'Detritus                   '  , 'mmole-N/m3' ,  .false.],
[ZOO'   , 'Zooplankton concentration  '  , 'mmole-N/m3' ,  .false.],
['PHY'   , 'Phytoplankton concentration'  , 'mmole-N/m3' ,  .false.],
]
```

The namelist parser should certainly be able to handle that somehow, but I do not have time to look into it (plus it is foreign code, so it would take me even longer 😞

**Comment by seb-wahl** [comment]
I even thought having a go at this myself, but reading the comments in https://github.com/marshallward/f90nml/issues/110 I realised that this might not be that easy.
