### ISSUE TITLE
Changing output frequency of accumulated variables via mvstreamctl

### ISSUE THREAD

**Issue by jannitzbon** [esm-tools/esm_tools#666]
**Describe the problem you are facing**
I have a question regarding the output handling of AWI-ESM. I would like to write some output at daily frequency instead of monthly. For
this, I added "mvstreamctl" entries via the runscript to namelist.echam. However, this seems to be working only for some (I think the "non-accumulated") variables, but not for all. In particular, I would like to have precipitation (aprc, aprl, aprs) and surface temperature (tsurf) at daily resolution, but I did not get this working using "mvstreamctl". 

Along these lines, I had a look into the echam output files ending on "_ma" which include some (accumulated) variables (e.g., aprc and aprl, but unfortunately not aprs) at hourly resolution. However, I was not able to locate where the "_ma" stream is configured and where it could be adopted.

So, does anybody know how to configure output streams for those variables (tsurf, aprc, ...) via mvstreamctl?

In addition, it would be good to know whether it is possible to remove some of the default output streams from the namelist via the runscript, in order to save diskspace. 

**Runscript and other relevant files**
I added the following entry to the echam namelist. However, daily output was only written for the variable "tslm1", not for the others.

```
&mvstreamctl
    interval = 1, 'days', 'last', 0
    target = 'cgforcid'
    source = 'g3b'
    variables = 'tsurf:mean', 'tslm1:mean', 'aprc:mean', 'aprl:mean', 'aprs:mean',
                'evap:mean', 'drain:mean', 'runoff:mean'
/
```

**System (please complete the following information):**
 - Supercomputer: ollie
 - Version: 6.0.6 
 - [Please run `esm_versions check`] --> should be changed to [Please run `esm_tools --version`]

**Comment by chrisdane** [comment]
Hi Jan

The echam mvstream definition is a science on its own. Maybe `/work/ab0246/a270073/out/awicm-test/CMIP6/CMIP_PMIP/dynveg_true/historical/config/echam/namelist.echam` can serve as a template for you. Search for e.g. "echamday".

Cheers,
Chris

btw: this is not really an esm_tools issue, it should rather go to https://code.mpimet.mpg.de

**Comment by jannitzbon** [comment]
Hi Chris,

Thanks a lot for your answer. I checked the file, and it indeed gives me a lot of examples how to approach this! I will check if it works as intended.

I agree, that this is not really an esm_tools issue. I guess it is rather a question I wanted to ask to AWI-CM/ESM users, but I was (and still am) not sure where to ask these kind of things without annoying individual persons ;-)

For the esm_tools side, however, it might be a nice feature to beings add and remove streams directly through the runscript, and maybe it could eventually take over some of the "mvstream science" behind the scenes...

Anyway, thanks again for your support!

**Comment by chrisdane** [comment]
I agree that feature would be awesome. But from experience you would need a full-time position for a year or so to implement this unbelievably impractical mvstream-method in a modular esm-tools way :|

**Comment by pgierz** [comment]
I at some point attempted to program the general solution to the `mvstream` business and ended up banging my head against the wall instead. There was an implementation where one could (probably) define the files to be moved based upon parsing the namelist and determining which files should then be produced. It was tested for a basic case, but we came to the conclusion that it was too "magical" to put in the tools as maintaining it would have ended up simply being a headache, owing mostly to the insufficient documentation from the ECHAM developer side, If there is strong interest, I can revive that effort.

Jan, what would you need right now to get your things to work? We can for example add a new section to the handbook

**Comment by jannitzbon** [comment]
Hi Paul,
thank you for your reply. I think I just need to used to the `mvstream` "business". It's definitely easier with examples / templates as the one Chris pointed me to. So it might be worth adding such an example to the "Cookbook" section of the documentation?

Btw, it was not possible for me to add multiple `mvstream` entries to the namelist via the runscript entries `add_namelist_changes`. esm_runscript then complained about multiple entries for the same tag `mvstreamctl`. So this case might need some special consideration.

Otherwise, I do not need support regarding this issue right now. Thanks!

**Comment by pgierz** [comment]
> Btw, it was not possible for me to add multiple mvstream entries to the namelist via the runscript entries add_namelist_changes. esm_runscript then complained about multiple entries for the same tag mvstreamctl. So this case might need some special consideration.

That is because the echam namelist is abusing some of the "rules" for a standard fortran namelist, and the namelist parser we have in esm-tools assumes a standard namelist is being used. Could you show me an example of what you were trying to do? There may be a workaround.

**Comment by pgierz** [comment]
I would say this is rather a discussion, and not an issue. Since our magical robot now marked it as stale, I would close this. If needed again, please re-open, and move to discussion. I can't see anything on our software side that would be causing this to break. Or, hopefully, it isn't broken at all anymore ;-)
