### ISSUE TITLE
flatten merged lists

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#667]
**Is your feature request related to a problem? Please describe.**
I would like to merge two lists li1 and li2 to a new list li3 that contains li1 and li2 in a flattened and not nested way.

**Describe the solution you'd like**
Paste this code in https://yaml-online-parser.appspot.com:
```
li1: &li1 [a, b]
li2: &li2 [c, d]
li3: 
  - *li1
  - *li2
```
the result is
```
  "li3": [
    [
      "a", 
      "b"
    ], 
    [
      "c", 
      "d"
    ]
```
i.e. the entries in li3 are nested and not on the same level. I need:
```
a
b
c
d
```

**Describe alternatives you've considered**
I tried many versions found on SO, e.g. https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays. It seems that feature is somewhat not implemented in base python: https://softwareengineering.stackexchange.com/questions/254279/why-doesnt-python-have-a-flatten-function-for-lists

Thanks for consideration.

**Comment by chrisdane** [comment]
can we use this somehow: https://pyyaml.docsforge.com/master/api/yaml/constructor/SafeConstructor/flatten_mapping/ ?

**Comment by pgierz** [comment]
Hi Chris,

this may be possible with the special "math" syntax in the ESM-Tools extension for YAML, which effectively tricks Python into do an evaluation of code disguised as a string. It is not something I would recommend leaning on heavily, as it may be error-prone.

```yaml
general:
   list_1:
     - "a"
     - "b"
     - "c"
   list_2:
     - "d"
     - "e"
     - "f"
   list_merge: $(( ${list_1} + ${general.list_2} ))
``` 
In Python, that translates to:
```python
list_1 = ["a", "b", "c"]
list_2 = ["d", "e", "f"]
list_merge = eval("list_1 + list_2")
print(list_merge)
["a", "b", "c", "d", "e", "f"]
```
Take special notice of where I have quotes, especially in the `eval` statement.

Again, this **may** work, or maybe not. I have not tested it yet.

**Comment by chrisdane** [comment]
No, the second list2 is ignored in the mergelist.

**Comment by denizural** [comment]
A solution is found. I willl make a PR later on.
Here: https://github.com/esm-tools/esm_tools/pull/672

**Comment by mandresm** [comment]
I'm taking over this one as @denizural is working on the cleanup of https://github.com/esm-tools/esm_tools/pull/665. This is needed for https://github.com/esm-tools/esm_tools/pull/665

**Comment by denizural** [comment]
Now, we have a new and better solution: https://github.com/esm-tools/esm_tools/tree/feat/merging_lists
More info will follow.

**Comment by denizural** [comment]
This issue should have been solved by now. A more detailed explanation can be found here: https://github.com/esm-tools/esm_tools/pull/716/
I will also update the documentation on the `add_` command.
