### ISSUE TITLE
ECHAM6-wiso in standalone mode: wrong file directories for wiso output and restart files

### ISSUE THREAD

**Issue by mwerner-awi** [esm-tools/esm_tools#670]
When I run ECHAM6-wiso in standalone mode (and not as part of AWIESM-wiso), all *wiso* output and restart files are stored in the directory <EXP>/unknown instead of the directories <EXP>/output/[..] and <EXP>/restart/[..]. Therefore a simulation stops after the first job cycle as ECHAM6-wiso can't find the required wiso restart files in the expected directories.

To reproduce the bug, simply run echam6-wiso with namelist entries:

    add_namelist_changes:
            namelist.echam:
                wisoctl:
                    lwiso: True
                    lwiso_rerun: ${lresume}
                    nwiso: 3

(lresume is the default ECHAM6 switch for a cold start or restart.)

In the "move output" phase, the following files should be moved from <EXP>/run_xxxx/work:

to ECHAM output files:
<EXP>_XXX.01_wiso and <EXP>_XXX.01_wiso.codes
<EXP>_XXX.01_accw_wiso and <EXP>_XXX.01_accw_wiso.codes

to JSBACH output files:
<EXP>_XXX.01_js_wiso and <EXP>_XXX.01_js_wiso.codes
<EXP>_XXX.01_la_wiso and <EXP>_XXX.01_la_wiso.codes

to ECHAM restart files:
restart_<EXP>_<XXX>_wiso.nc 
restart_<EXP>_<XXX>_accw_wiso.nc 

to JSBACH restart files:
restart_<EXP>_<XXX>_js_wiso.nc 
restart_<EXP>_<XXX>_sf_wiso.nc 

This bug occurred on ollie.awi.de using esm_tools version 6.6.8.

**Comment by pgierz** [comment]
Hi Martin,

thanks for reporting. It seems to be a relatively easy fix, the relevant output and restart files simply aren't known about:

https://github.com/esm-tools/esm_tools/blob/665ef93274c2efa41f27e5d5d901a585ad28ceb2/configs/components/echam/echam.yaml#L501-L505

Both the `wiso` and `accw_wiso` file tags are behind a switch which was introduced when we unified the AWIESM versions together.

Could you try to add the following in your runscript?
```yaml
echam:
   wiso_wiso: True
```

**Comment by pgierz** [comment]
@mandresm, @denizural: someone should put this on the todo list or make a separate issue.

I think that `rad` in the list up there belongs somewhere else. That has to do with concurrent radiation, and I am not 100% sure if any and all versions of echam floating around also include concurrent radiation. It doesn't hurt, you'll just end up with a warning about a missing file, but just to be clean we should think about separating that out.

edit: I meant: I am unsure if all echam versions including wiso also by default include concurrent radiation at the same time.

**Comment by mwerner-awi** [comment]
> Hi Martin,
> 
> Could you try to add the following in your runscript?
> 
> ```yaml
> echam:
>    wiso_wiso: True
> ```

Hi Paul,

I've tried your suggestion but it does not fix the problem.

Please note: (i) I already set the switch "with_wiso: True" in the general section of my yaml script. (ii) The files are moved correctly when I run ECHAM6-wiso as part of AWIESM-wiso.

**Comment by pgierz** [comment]
Hi Martin,

Ok then one of the esm tools team will need to take a deeper look. Can you post the path to your experiment?

**Comment by mwerner-awi** [comment]
The yaml file is: /home/ollie/mwerner/runscripts/echam6/PI_tag_2tr_1year.test.yaml

The experiment is stored in: /work/ollie/mwerner/echam6-wiso/TAG05

**Comment by pgierz** [comment]
Moin Martin,
cc @mandresm @denizural @seb-wahl 

So two apologies: Sorry for the typo above, that should obviously have been `with_wiso` in the `echam` part of the run configuration instead of `wiso_wiso`, and sorry for the delay, I had some difficulty reproducing this due to walltime timeouts.

@mandresm we should look into why both flags are needed. I think that's a logical error somewhere on the parser side.


Here are the full differences thus far to the configuration:
```diff
     setup_name: "echam"
     version: "6.3.05p2-wiso"
     with_wiso: True
+    wiso_code: True
+    compute_time: "06:00:00"
-    compute_time: "00:50:00"
     initial_date: "2000-01-01"
     final_date: "2001-01-01"
     model_dir: "/home/ollie/mwerner/codes/echam-6.3.05p2-wiso/"
+    base_dir: "/work/ollie/pgierz/SciComp/Model_Support/esm-tools/GH670/experiments"
-    base_dir: "/work/ollie/mwerner/echam6-wiso/"
     nmonth: 1
     nyear: 0
     use_venv: False
+    verbose: True
 
 echam:
+    with_wiso: True
+    wiso_code: True
     executable: echam6
-    wiso_wiso: True
```

In my test run, everything seems to be fine:
```
$ pwd
/work/ollie/pgierz/SciComp/Model_Support/esm-tools/GH670/experiments/Martin_GH670_006/outdata/echam
$ ls
Martin_GH670_006_200001.01_accw             Martin_GH670_006_200001.01_glim.codes
Martin_GH670_006_200001.01_accw.codes       Martin_GH670_006_200001.01_sp6h
Martin_GH670_006_200001.01_accw_wiso        Martin_GH670_006_200001.01_sp6h.codes
Martin_GH670_006_200001.01_accw_wiso.codes  Martin_GH670_006_200001.01_spim
Martin_GH670_006_200001.01_aclcim           Martin_GH670_006_200001.01_spim.codes
Martin_GH670_006_200001.01_aclcim.codes     Martin_GH670_006_200001.01_wiso
Martin_GH670_006_200001.01_co2              Martin_GH670_006_200001.01_wiso.codes
Martin_GH670_006_200001.01_co2.codes        Martin_GH670_006_200002.01_accw.codes
Martin_GH670_006_200001.01_echam            Martin_GH670_006_200002.01_accw_wiso.codes
Martin_GH670_006_200001.01_echam.codes      Martin_GH670_006_200002.01_aclcim.codes
Martin_GH670_006_200001.01_g3b1hi           Martin_GH670_006_200002.01_co2.codes
Martin_GH670_006_200001.01_g3b1hi.codes     Martin_GH670_006_200002.01_echam.codes
Martin_GH670_006_200001.01_g3bday           Martin_GH670_006_200002.01_g3b1hi.codes
Martin_GH670_006_200001.01_g3bday.codes     Martin_GH670_006_200002.01_g3bday.codes
Martin_GH670_006_200001.01_g3bid            Martin_GH670_006_200002.01_g3bid.codes
Martin_GH670_006_200001.01_g3bid.codes      Martin_GH670_006_200002.01_g3bim.codes
Martin_GH670_006_200001.01_g3bim            Martin_GH670_006_200002.01_glday.codes
Martin_GH670_006_200001.01_g3bim.codes      Martin_GH670_006_200002.01_glim.codes
Martin_GH670_006_200001.01_glday            Martin_GH670_006_200002.01_sp6h.codes
Martin_GH670_006_200001.01_glday.codes      Martin_GH670_006_200002.01_spim.codes
Martin_GH670_006_200001.01_glim             Martin_GH670_006_200002.01_wiso.codes
```
and in restart as well:
```
$ pwd
/work/ollie/pgierz/SciComp/Model_Support/esm-tools/GH670/experiments/Martin_GH670_006/restart/echam
$ ls
restart_Martin_GH670_006_accw_20000131.nc       restart_Martin_GH670_006_g3bim_20000131.nc
restart_Martin_GH670_006_accw_wiso_20000131.nc  restart_Martin_GH670_006_glday_20000131.nc
restart_Martin_GH670_006_aclcim_20000131.nc     restart_Martin_GH670_006_glim_20000131.nc
restart_Martin_GH670_006_co2_20000131.nc        restart_Martin_GH670_006_sf_wiso_20000131.nc
restart_Martin_GH670_006_echam_20000131.nc      restart_Martin_GH670_006_sp6h_20000131.nc
restart_Martin_GH670_006_g3b1hi_20000131.nc     restart_Martin_GH670_006_spim_20000131.nc
restart_Martin_GH670_006_g3bday_20000131.nc     restart_Martin_GH670_006_wiso_20000131.nc
restart_Martin_GH670_006_g3bid_20000131.nc  
```

There are still some files in `unknown` though; so, we should fix the streams that are known about when `wiso_code` and `with_wiso` is turned on:
```
$ pwd
/work/ollie/pgierz/SciComp/Model_Support/esm-tools/GH670/experiments/Martin_GH670_006/unknown
$ ls
echam6.log                                Martin_GH670_006_200001.01_ma.codes
Martin_GH670_006_200001.01_js_wiso        Martin_GH670_006_200002.01_js_wiso.codes
Martin_GH670_006_200001.01_js_wiso.codes  Martin_GH670_006_200002.01_la_wiso.codes
Martin_GH670_006_200001.01_la_wiso        Martin_GH670_006_200002.01_ma
Martin_GH670_006_200001.01_la_wiso.codes  Martin_GH670_006_200002.01_ma.codes
Martin_GH670_006_200001.01_ma             restart_Martin_GH670_006_20000131235230_js_wiso.nc
```

@mwerner-awi in the interim, you can try:
```yaml
echam:
   with_wiso: True
   wiso_code: True
jsbach:
   add_streams:
      - js_wiso
      - la_wiso
      - ma
```

For the missing streams `js_wiso`, `la_wiso`, and `ma`, unfortunately that will require a version bump if you do not want to pollute your runscript too much. 

Regarding walltime, the run finishes computationally in 27 minutes on the first year, and then takes a rather long time to clean up. My tests were (as normally for me) done behind a virtual environment, so perhaps we should look into this. It seems to induce considerable overhead for something as simple as copying files (hence the absurd wall time of 6 hours for my reproducibility tests). However, I have heard from users as well that turning on virtual encapsulated runs induces walltime over heads, and I do not know (yet) why... 

Regarding streams in general: I had a solution a while ago that parsed `namelist.echam`, figured out which filenames would be written by echam based upon the contents of the various `mvstreamctl` and amended the `streams` variable appropriately. @seb-wahl deemed this "too magical" (I agree, it is a very domain-specific breaking point), but perhaps we can revisit this. Maybe as an "opt-in" option in the echam section? Something like:
```yaml
echam:
   detect_streams_from_namelist: True
``` 

Have a nice weekend,
Paul

**Comment by mwerner-awi** [comment]
Hi Paul,
cc @mandresm @denizural @seb-wahl

The problem is partly solved when I add the following entries to my yaml file:

echam:
    with_wiso: True
    wiso_code: True
    add_streams:
        - jsbach
        - land
        - js_wiso
        - la_wiso
        - ma

Open issues are the following:

(i) The output files *_js_wiso and *la_wiso are stored in <EXP>/outdata/echam. These are JSBACH-related files and they should be stored in <EXP>/outdata/jsbach.

(ii) The restart files restart_<EXP>_js_wiso_YYYYMMDD.nc are stored <EXP>/restart/echam. They belong into <EXP>/restart/jsbach.

(iii) No output files for the streams *jsbach* and *land* are written out. The missing files are caused by the following entries in the default ECHAM6 PI-CTRL namelist (esm_tools/namelists/echam/6.3.05p2-wiso/PI-CTRL/namelist.echam):

&set_stream
    stream = 'jsbach'
    lpost = 0
/
&set_stream
    stream = 'land'
    lpost = 0
/

Is there a possibility to set lpost=1 for these streams via my own yaml-file?

Best, Martin

**Comment by pgierz** [comment]
Hi Martin,

If you move the add streams into your jsbach section, they will be correctly moved. Make sure to then also include the two streams jsbach and land to the list, as they will active if the next step below works:

Unfortunately setting the lpost via the runscript is not possible.  The echam namelist repeats chapter headings, and thus the standard change mechanism does not work, as we do not yet have a way to uniquely specify where you want the change. That might be implemented in the future. 

Instead: You will need to change the template from which the namelist is copied. For that you would need to copy the template namelist you wish to have to a different location, change lpost to 1, and under the echam section, specify `namelist_dir` accordingly. 

Let me know how it goes,
Paul

**Comment by mwerner-awi** [comment]
Hi Paul,

just to confirm that your suggested solution works.

The restart files restart__js_wiso_YYYYMMDD.nc is still stored erroneously in /restart/echam (and a copy is now saved in  /restart/jsbach if I add the stream to the jsbach section), but as the model is running, we can leave it like this for the moment.

Best, Martin

**Comment by pgierz** [comment]
Hi Martin,

Excellent! 

I will still leave the issue open so that @mandresm or @denizural can make sure it gets cleaned up and goes into the defaults.

Best
Paul

**Comment by mandresm** [comment]
Hi all, 

I've completely miss this issue as I was on holidays and the notifications got lost in the long list of emails as I came back. It seems that there is the need for some generalization in the `yaml` files, so I'll be having a look at that guided by the list @mwerner-awi provided.

> (i) The output files *_js_wiso and *la_wiso are stored in /outdata/echam. These are JSBACH-related files and they should be stored in /outdata/jsbach.
> 
> (ii) The restart files restart__js_wiso_YYYYMMDD.nc are stored /restart/echam. They belong into /restart/jsbach.
> 
> (iii) No output files for the streams _jsbach_ and _land_ are written out. The missing files are caused by the following entries in the default ECHAM6 PI-CTRL namelist (esm_tools/namelists/echam/6.3.05p2-wiso/PI-CTRL/namelist.echam):

@mwerner-awi can you provide a path with your latest "more correct" experiment folder? Can you also keep the old experiment folder (`/work/ollie/mwerner/echam6-wiso/TAG05`) so that I can also look at it?

One note is that the `wiso_code` variable was concieved to **not** be used from the runscript. This variable is automatically chosen for you from the `echam.version` (`wiso_code` means the code you are using has WISO in the source, and therefore it's strictly linked to the ECHAM version used). Having the `wiso_code` in the runscripts might lead to quite some confusion.

**Comment by mandresm** [comment]
> (iii) No output files for the streams _jsbach_ and _land_ are written out. The missing files are caused by the following entries in the default ECHAM6 PI-CTRL namelist (esm_tools/namelists/echam/6.3.05p2-wiso/PI-CTRL/namelist.echam):

@mwerner-awi, about this, should we include those streams by default in the namelists provided by ESM-Tools by default?

**Comment by mandresm** [comment]
Hi @mwerner-awi,

The branch `fix/echam_switches_and_version_bug` should have all the fixes a simplified version of your runscript (`/home/ollie/mwerner/runscripts/echam6/PI_tag_2tr_1year.yaml`) to run successfully. Please, see below the simplications you can make, and let me know if that branch solves all the problems of the issue (I tested already and I think it does):
```diff
general:
    setup_name: "echam"
    version: "6.3.05p2-wiso"
    compute_time: "00:50:00"
    initial_date: "2000-01-01"
    final_date: "2001-01-01"
    model_dir: "/home/ollie/mwerner/codes/echam-6.3.05p2-wiso/"
    base_dir: "/work/ollie/mwerner/echam6-wiso/"
    nmonth: 1
    nyear: 0
    use_venv: False
+    with_wiso: true       # fixed problems with this switch, now it can be defined either in general or in echam

echam:
-    executable: echam6        # not needed, defined automatically
-    with_wiso: True       # fixed problems with this switch, now it can be defined either in general or in echam
-    wiso_code: True        # not needed, defined automatically
-    bin_sources:        # not needed, defined automatically
-            echam_bin: "${bin_dir}/${executable}"        # not needed, defined automatically
-    bin_in_work:        # not needed, defined automatically
-            echam_bin: "${executable}"        # not needed, defined automatically
    scenario: "PI-CTRL"
    res: T63 
    lresume: False
    restart_rate: 1
    restart_unit: "months"
    nproca: 6
    nprocb:  6
+  nwiso: 5
-    nprocar: 0        # not needed, defined by default 0
-    nprocbr: 0        # not needed, defined by default 0
    namelist_dir: "/home/ollie/mwerner/runscripts/echam6"
    add_namelist_changes:
            namelist.echam:
-                parctl:
-                    nproca: 6         # not needed, automatically taken directly from what you defined in echam.nproca
-                    nprocb: 6         # not needed, automatically taken directly from what you defined in echam.nprocb
-                    nprocar: 0        # not needed, automatically taken directly from what is defined by default for echam.nprocar
-                    nprocbr: 0        # not needed, automatically taken directly from what is defined by default for echam.nprocbr
                runctl:
                    default_output: True
                    # putdata: [ 450, 'seconds', 'first', 0 ]
                    # putdata: [ 6, 'hours', 'last', 0 ]
                    putdata: [ 1, 'days', 'last', 0 ] 
                    # dt_stop: [ 2000, 1, 2 ]
                radctl:
                    lrad_async: False
                wisoctl:
-                    lwiso: True        # not needed, automatically set when with_wiso is true
-                    lwiso_rerun: ${lresume}        # not needed, automatically set when with_wiso is true
-                    nwiso: 5        # not needed, automatically taken directly from what you defined in echam.nwiso
                    ntag: 2
    file_movements:
        forcing:
            all_directions: "link"
        input:
            all_directions: "link"
    forcing_sources:
        wiso_sw_observed: "/home/ollie/mwerner/model_input/ECHAM6-wiso/PI_ctrl/T63/T63_wisosw_d.nc"
        wiso_tagmap_1: "/work/ollie/mwerner/echam6-wiso/tagmap_NH_SH.nc"
    add_forcing_files:
        wiso_sw: wiso_sw_observed
        wiso_tagmap: wiso_tagmap_1
    forcing_in_work:
        wiso_sw: "unit.25"
        wiso_tagmap: "unit.26"

jsbach:
    file_movements:
        forcing:
            all_directions: "link"
        input:
            all_directions: "link"
    add_namelist_changes:
        namelist.jsbach:
            jsbach_ctl:
                with_hd: False
-    add_streams:        # not needed, automatically set when with_wiso is true
-        - jsbach
-        - js_wiso
-        - land
-        - la_wiso
-        - surf
-        - sf_wiso
```

**Comment by mandresm** [comment]
I found a last minute problem. I'll solve it for monday and then you can see if it works

**Comment by mandresm** [comment]
Hi @mwerner-awi, all the problems should be solved now. You can now follow [this post](https://github.com/esm-tools/esm_tools/issues/670#issuecomment-1152516610) to test it and let us know whether all works as it should.

**Comment by mandresm** [comment]
@mwerner-awi  mentioned the following via email:

> I have checked your changes and confirm that everything works as expected. The only open issue that I found is that the main JSBACH output streams „jsbach“ and „land“ are not written out as files. The related entry is in namelist.echam:
> 
> &set_stream
>     stream = 'jsbach'
>     lpost = 0
> /
> 
> &set_stream
>     stream = 'land'
>     lpost = 0
> /
> 
> 
> Here, I would suggest to set lpost = 1 for both streams. Of course, this means that the files are also created if someone runs the ECHAM+JSBACH model without isotopes, but I guess this is not a problem. If the outputs files are not needed, they can be easily deleted afterwards.

My reply:

I have added the `lpost` changes to the `namelist.echam` in `esm_tools/namelists/echam/6.3.05p2-wiso/` (8bc2ed1) so now the default namelist for the wiso development branch has those file included. I'll discuss with @pgierz about a better strategy for the general AWIESM version, but that won't be done in this PR... It will be probably addressed during the cleaning up of `esm_runscripts` where the namelists are handled.
