### ISSUE TITLE
ECHAM Rad issue

### ISSUE THREAD

**Issue by denizural** [esm-tools/esm_tools#671]
https://github.com/esm-tools/esm_tools/blob/665ef93274c2efa41f27e5d5d901a585ad28ceb2/configs/components/echam/echam.yaml#L501-L505

I think that `rad` in the list up there belongs somewhere else. That has to do with concurrent radiation, and I am not 100% sure if any and all versions of echam floating around also include concurrent radiation. It doesn't hurt, you'll just end up with a warning about a missing file, but just to be clean we should think about separating that out.

edit: I meant: I am unsure if all echam versions including wiso also by default include concurrent radiation at the same time. 

_Originally posted by @pgierz in https://github.com/esm-tools/esm_tools/issues/670#issuecomment-1131887336_

**Comment by mandresm** [comment]
Hey @pgierz , is the `rad` stream depending on whether we are running with concurrent radiation code on or not? because we have already a switch for concurrent radiation radiation that this stream could be behing

**Comment by pgierz** [comment]
Yes, the `rad` stream only exists if `with_concrad` is on (not sure exactly what the switch is called off the top of my head)

**Comment by mandresm** [comment]
fixed in #692
