### ISSUE TITLE
Problem with esm_master

### ISSUE THREAD

**Issue by vkolatschek** [esm-tools/esm_tools#674]
**Describe the problem you are facing**
After installing the esm_tools on levante, I get an error when trying esm_master:
`Something else went wrong
Serious issue with /home/a/a270147/esm_tools/configs//components/fesom/fesom-2.1.yaml, goodbye...`

**System (please complete the following information):**
 - Supercomputer: Levante
 - Version: I'm not sure (there is no esm_versions anymore?) But I downloaded from 'origin/release' on May 30 15:07 if that helps.

**Comment by vkolatschek** [comment]
``>> esm_tools --version``
``esm_tools, version 6.7.0``

**Comment by mandresm** [comment]
Thanks for reporting that. The solution is now available in `release`. Simply `git pull` and it should start working again. I'll close the issue now, please reopen it if the fix does not work for you.
