### ISSUE TITLE
Trigger warnings from yamls

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#696]
**Is your feature request related to a problem? Please describe.**
Useful to report warnings to users under certain configurations. For example in the case of #695, if in the future, a new `LU_trans_1850` is set as default for PI simulations, the user needs to be notified about it, so that she/he can decide whether that's okay, or wants to continue an older run with the old file.

**Describe the solution you'd like**
One could use the following syntax (or something similar) in yaml files to trigger a user warning:
```yaml
warning:
    <warning_name>: # Name for the specific warning
        message: "the message of the warning"
        esm_tools_version: ">/</=/!=/version_number" # trigger it under certain ESM-Tools version conditions
        ask_user_to_continue: True/False # Ask user about continuing or stopping the process
```

This could be included inside `choose_` blocks, which means it can be triggered under certain conditions/configurations.

The warning would be displayed when submitting the simulation (and the conditions are met) and would look something like this:
```
Warning: <warning_name>:
---------------------------
<message>

[optional] Do you want to continue (set general.ignore_yaml_warnings: False to avoid quesitoning)? (y/n): 
```

**Additional context**
I'd like to take into account the feedback from the advance users for this feature before jumping into coding, so please reply to this issue with your ideas and feel free to tag users I forgot about (@pgierz, @denizural, @JanStreffing, @joakimkjellsson, @christian-stepanek, @chrisdane, @fernandadialzira, @tsemmler05)

**Comment by mandresm** [comment]
It should also be possible to ignore the yaml warnings by defining `general.ignore_config_warnings: True`.

**Comment by mandresm** [comment]
also add a similar option for `error`.

**Comment by joakimkjellsson** [comment]
I think this would be nice. 
For example, it is possible to change O3 in OpenIFS 43r3v2 but not v1. Would be nice to have warnings about this.

**Comment by mandresm** [comment]
So the feature is now on `release`, you can read on how to use it here: https://esm-tools.readthedocs.io/en/latest/yaml.html#error-handling-and-warning-syntax
