### ISSUE TITLE
DSO missing from command line

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#698]
Hi

**Describe the bug**
I am trying to install the setup `awicm-1.0-recom` on levante. Installing the echam component stops with this error:
```
esm_master comp-awicm-1.0-recom
...
support/libsupport.a(util_file.c.o): In function `util_tmpnam':
util_file.c:(.text+0xa8): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
ld: cdi/libcdi.a(pio_posixasynch.c.o): undefined reference to symbol 'aio_write@@GLIBC_2.2.5'
//usr/lib64/librt.so.1: error adding symbols: DSO missing from command line
make[2]: *** [src/echam/CMakeFiles/echam6.dir/build.make:5355: src/echam/echam6] Error 1
make[1]: *** [CMakeFiles/Makefile2:226: src/echam/CMakeFiles/echam6.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**To Reproduce**
```
esm_master comp-awicm-1.0-recom
```

**Expected behavior**
Successful compile.

**System (please complete the following information):**
 - Supercomputer: levante
 - Version
 ```
version = esm_tools, version 6.8.0
branch  = release
hash    = b6455a74
src     = /home/a/a270073/esm/esm_tools
```

Thanks!
Chris

**Comment by denizural** [comment]
Hi @chrisdane , I solved that problem. This requires a change in the awicm CMake file. We are currently on the Climate Dynamics retreat but I will show you the solution when I have a stable internet.

**Comment by pgierz** [comment]
I'm not sure if recom support on levante is in release yet. Deniz can you check and please put that in very soon if not?

**Comment by pgierz** [comment]
@chrisdane  if you have a small script who spits out your branch, hash, etc info I would be very interested in recycling this.

**Comment by mandresm** [comment]
No is not released yet, @denizural is taking care of it, but there is no PR yet. Neither is AWICM-REcoM in release (not supported in `release` for any of the HPCs).

**Comment by chrisdane** [comment]
Eeh sorry I should have added this: the error occurs in the echam compiling step, so independent on recom? But if Deniz already has a solution its ok anyway.

@pgierz:
```bash
    esm_tools_info() {
        if command -v esm_tools > /dev/null 2>&1; then
            #echo "run 'esm_tools --version' ..."
            esm_tools_version=$(esm_tools --version) # e.g. "esm_tools, 6.1.3"
            esm_master_bin=$(which esm_master) # e.g. ~/.local/bin/esm_master
            esm_master_py_bin=$(head -1 $esm_master_bin) # "#!/path"
            esm_master_py_bin=${esm_master_py_bin:2} # "/path"
            esm_tools_src_path=$($esm_master_py_bin -c "import site; print(site.getusersitepackages())") # e.g. ~/.local/lib/python3.8/site-packages
            esm_tools_src_path=$(head -1 $esm_tools_src_path/esm-tools.egg-link) # /path/to/esm_tools/src/
            esm_tools_src_path=$(dirname $esm_tools_src_path) # without /src
            owd=$(pwd); cd $esm_tools_src_path
            esm_tools_src_path=$(pwd) # normalize path; better than readlink -f
            esm_tools_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
            esm_tools_hash=$(git rev-parse --short HEAD)
            cd $owd
            echo "version = $esm_tools_version"
            echo "branch  = $esm_tools_branch"
            echo "hash    = $esm_tools_hash"
            echo "src     = $esm_tools_src_path"
        else
            echo "could not find esm-tools"
            return 1
        fi
    } # esm_tools_info
```

**Comment by pgierz** [comment]
Thanks. It's shell. Merp. 

Which echam are you using? We will have some time this evening to get back to you

**Comment by chrisdane** [comment]
> Thanks. It's shell. Merp.

If the esm_tools are not shipped with a needed functionality the users need to help themselves :P 

> Which echam are you using?

co2_coupling

**Comment by pgierz** [comment]
> If the esm_tools are not shipped with a needed functionality the users need to help themselves :P

Already in progress ;-) https://github.com/esm-tools/esm_tools/pull/690

**Comment by pgierz** [comment]
> `co2_coupling`

Which remote host is that? There are some changes required to the compilation of ECHAM, and that needs to happen on the ECHAM side, not the esm-tools side.

**Comment by chrisdane** [comment]
Dont know if this answers your question: https://gitlab.dkrz.de/modular_esm/echam6/-/commits/co2_coupling

**Comment by chrisdane** [comment]
Aaaaaah sorry my mistake: I should have just cherry picked [2334507d](https://gitlab.dkrz.de/modular_esm/echam6/-/commit/2334507dd520cd5ba0acd8f18265b7a1fca200de) into my echam branch *facepalm*

**Comment by denizural** [comment]
I am reopening this issue again. The fixes to corresponding ECHAM, FESOM, Recom branches are implemented. I will make a PR on the DKRZ GitLab from my forks. The issue will be closed after esm_master successfully installs everything (currently does on my branch) in the release branch.
All related PRs will be mentioned here.

**Comment by pgierz** [comment]
Closing, this is no longer relevant. I was just able to run on levante with no compile-time issues:

```console
$ esm_master install-awicm-1.0-recom
```
