### ISSUE TITLE
Error in Mistral trying to load anaconda3

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#7]
I a getting the following error when I execute `module load anaconda3` in Mistral:

```
anaconda3/bleeding_edge(12):ERROR:150: Module 'anaconda3/bleeding_edge' conflicts with the currently loaded module(s) 'netcdf_c/4.3.2-gcc48'
anaconda3/bleeding_edge(12):ERROR:102: Tcl command execution failed: conflict netcdf_c
```

I solve the issue provisionally unloading the conflicting package:

`$> module unload netcdf_c/4.3.2-gcc48`

Is that the correct solution to the problem or is the `netcdf_c/4.3.2-gcc48` module needed for something when using the esm_tools?

**Comment by pgierz** [comment]
that's the correct solution. You can also do:

```
$ module swap netcdf_c anaconda3
```

**Comment by mandresm** [comment]
Should I add this to the installation instructions and or in the FAQ?
