### ISSUE TITLE
invalid change in namelist_dir of xios in awicm3-v3.1

### ISSUE THREAD

**Issue by shijian0702** [esm-tools/esm_tools#710]
**Describe the bug**

Though changing the xios namelist_dir in the yaml file (awicm3-v3.1), it doesn't work, and the model still reads the original xios namelist_dir in the esm_tools directory: ~/esm_tools/namelists/oifs/43r3/xios/. esm_tools seems to overwrite the xios namelist change.

xios:
    with_model: oifs
    nproc: 8
    omp_num_threads: 16
    namelist_dir: "/home/a/a270196/scripts/namelist/xios/"

**Comment by mandresm** [comment]
Can you please provide the ESM-Tools version? (`esm_tools --version`)

**Comment by mandresm** [comment]
I've had a look at the latest `xios.yaml` and there are no `namelist_dir`, as it is expected, because `xios` does not use namelists for the configuration, but instead `xml` files. Therefore, what you probably want to change is the `xml_dir`.

Please let me know if that solves the problem for you.

**Comment by shijian0702** [comment]
> I've had a look at the latest `xios.yaml` and there are no `namelist_dir`, as it is expected, because `xios` does not use namelists for the configuration, but instead `xml` files. Therefore, what you probably want to change is the `xml_dir`.
> 
> Please let me know if that solves the problem for you.

Yes it works now. Thanks Miguel!

**Comment by mandresm** [comment]
Then I'll close the issue :)
