### ISSUE TITLE
adding more information to add_ feature

### ISSUE THREAD

**Issue by denizural** [esm-tools/esm_tools#717]
**Request/contribution description**
https://esm-tools.readthedocs.io/en/latest/yaml.html#append-to-an-existing-list-add

after the PR https://github.com/esm-tools/esm_tools/pull/716 that solves the issue https://github.com/esm-tools/esm_tools/issues/667

**Suggested chapter/section in the documents**
Explain the merging feature

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
Include the runscript and/or other relevant files that you modified (indicate file paths if necessary).

**Contribution**
In case this is a contribution, please include here the text to be added to the documentation.

**Comment by pgierz** [comment]
I find the documentation in its current form sufficient. We can open a new issue with a better description of what should actually be added if anyone asks for that. This issue doesn't really provide any useful information about what could be expanded upon, closing...
