### ISSUE TITLE
cmorization missing echam6 streams

### ISSUE THREAD

**Issue by fernandadialzira** [esm-tools/esm_tools#731]
Some of our AWI-ESM2.1 simulations need to have a standard netcdf output file. When I select the `out_filetype=2` switch on the echam section of my run config I still get `accw` streams in grib format, and `echam` and `co2` streams are not written at all.

looking at `esm_tools/configs/components/echam/echam.yaml`, there is the part where the streams are set up:

```
streams:
        - echam
        - accw
        - co2
        - g3bid
        - g3bim
        - g3bday
        - g3b1hi
        - glday
        - aclcim
        - sp6h
        - glim
        - spim

streamsnc:
        - aclcim
        - g3b1hi
        - g3bday
        - g3bid
        - g3bim
        - glday
        - glim
        - jsbid
        - sp6h
        - spim

```

I tried including these three in `streamsnc` and ran my simulation, but it would still not write those.

machine: `ollie`
esm_tools version: `release` - I do not remember which specific version it was, but it is definitely more than version 6.1

**Comment by pgierz** [comment]
Hi @fernandadialzira, do you have the experiment path? I would need to look at your `namelist.echam`

**Comment by chrisdane** [comment]
Hi Fernanda

To save variables from echams `co2` stream, I made added sth like this to the namelist.echam (on levante):
```
/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/piControl/config/echam/namelist.echam
&mvstreamctl
    filetag = 'co2mon'
    source = 'co2'
    target = '*mon'
    interval = 1, 'months', 'last', 0
    variables = 'co2_burden:mean>co2_burden=8', 'co2_flx_anthro:mean>co2_flx_anthro=20',
                'co2_flx_land:mean>co2_flx_land=6', 'co2_flx_lcc:mean>co2_flx_lcc=24',
                'co2_flx_harvest:mean>co2_flx_harvest=25', 'co2_flux:mean>co2_flux=5',
                'co2_flx_ocean:mean>co2_flx_ocean=7'
/
```
Feel free to use and adapt.

The `streams` and `streamsnc` definitions in echam.yaml are only needed to move the model output files from `run_yyyymmdd/work` to `outdata/echam/` (ongoing issue: https://github.com/esm-tools/esm_tools/issues/384).

Cheers,
Chris

**Comment by fernandadialzira** [comment]
> Hi @fernandadialzira, do you have the experiment path? I would need to look at your `namelist.echam`

Hi @pgierz: the path is `/work/ollie/fmatos/mis3/experiments_testing/GT21G21O21_003_gm2000/`
I did not assign a path for echam namelists, so it was probably the default from esm_tools

**Comment by pgierz** [comment]
Info also for @christian-stepanek: Before I change the defaults, I need to know what you have discussed with the DKRZ colleagues regarding CMORization

**Comment by christian-stepanek** [comment]
> Info also for @christian-stepanek: Before I change the defaults, I need to know what you have discussed with the DKRZ colleagues regarding CMORization

Discussion is still ongoing, I suggest to leave this issue open until we have fixed that.

**Comment by nwieters** [comment]
Hi @christian-stepanek, @pgierz , has anything been decided on this yet? 

Is it still planned to change the default Echam namelist? Or is the solution by @chrisdane sufficient and we can close the issue?
