### ISSUE TITLE
Oasis restarts

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#743]
**Describe the bug**
For a restart, Oasis flux files (`a2o` and `o2a` for `AWICM` for example) are always copied from a file which path has no date-stamp, and this is hardcoded in the `src/esm_runscripts/oasis.py`. This is okay for restarts in ongoing simulations as the file without a time-stamp is a link to the latest time-stamped file. However, it's not correct when there is a need to branch-off from an already finished simulation, in some point earlier than the simulation's end. 

**Expected behavior**
Restarts of oasis are handled through the runscript in the same way the other components handle restarts.

**Additional context**
@denizural already started working on it and has a solution that will be pull-requested in a couple of weeks, after the end-of-July workshops.

@chrisdane reported this issue.

**Comment by nwieters** [comment]
This issue has been solved with version 6.21.23 (pull request #996).
