### ISSUE TITLE
year vs syear in echam.yaml

### ISSUE THREAD

**Issue by denizural** [esm-tools/esm_tools#752]
We just noticed during the workshop (thanks to @fernandadialzira ) that some variables have `!year` and some have `!syear`. It seems to be working but is this a typo?

https://github.com/esm-tools/esm_tools/blob/e4da879b68c3b48958a8ada2463c759b8009add7/configs/components/echam/echam.yaml#L710-L721

**Comment by pgierz** [comment]
Year is the integer, and syear is the string representation. Potentially 0 padding is missing in the first case. 

Since we generally always have 4 digit years, this should not matter.
