### ISSUE TITLE
AWIESM with icebergs issue

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#760]
We are  encountering problems with the iceberg test (it was working previous to the FESOM merge 2 weeks ago FESOM/fesom2#360 but now is not).

@pgierz  is having a look until 14:00, but if he doesn't figure it out by that time, we will require your help.

The branch of ESM-Tools we are testing is the latest release, with the AWIESM branches being the most up-to-date ones (for FESOM: `2.1-awiesm-2.1`).

Failed test in Ollie under this path: `/work/ollie/mandresm/testing/run/awiesm/awiesm-2.1_icebergs/`
Source code folder: `/work/ollie/mandresm/testing/comp/awiesm/awiesm-2.1`
Script: `/work/ollie/mandresm/testing/run/awiesm/awiesm-2.1_icebergs/scripts/awiesm-2.1_icebergs.yaml`

To reproduce this you'll need to modify the script by setting the `model_dir` and `base_dir` manually, and removing the `account` (manually change all the `!ENV` variables).

You can check the namelist used here: `/work/ollie/mandresm/testing/run/awiesm/awiesm-2.1_icebergs/run_20010101-20010101/work/namelist.config`

and as you can see it seems to have all the things necessary for activating icebergs, but maybe something has changed?

The problem is that the work folder does not generate any `iceberg.restart` (you can see that at the end of this log file: `/work/ollie/mandresm/testing/run/awiesm/awiesm-2.1_icebergs/log/awiesm-2.1_icebergs_awiesm_compute_20010101-20010101_16720007.log`)

**Comment by ackerlar** [comment]
Hi @mandresm FESOM doesn't seem to run with icebergs, e.g. it did not create the `buoys_track.nc` file. Díd you compile your FESOM with `ASYNC_ICEBERGS ON` ?
Maybe this got broken by the latest merge...

**Comment by mandresm** [comment]
I did not know that was a requirement, I'm pretty sure this was never in release. Why do we need ASYNC_ICEBERGS ON for the small tests and the general version of AWIESM-2.1? Isn't this just an option?

**Comment by ackerlar** [comment]
Ah okay, this wasn't clear to me. I fixed this here: [https://github.com/FESOM/fesom2/pull/363](url)
It works now for me also when compiled with async_icebergs set off

**Comment by nwieters** [comment]
Hi @mandresm,

does the PR by @ackerlar also solved the tests for awiesm?

**Comment by pgierz** [comment]
From as far as I know, @ackerlar is using a rather old version of the tools, which is totally fine as he needs something to finish his PhD. I would however keep this one open, since iceberg integration is a big issue for the paleo group, and I have been in contact with @gknorr a few times as to the future of AWI-ESM. Icebergs aren't going away, but I would like this to at some point become a thing that is hard-wired into the code at compile time, and turned on via a namelist switch.

The breaking tests for AWI-ESM need a separate place for discussion, in my view.
