### ISSUE TITLE
move function

### ISSUE THREAD

**Issue by SpontEIN** [esm-tools/esm_tools#77]
The basic `echam-mistral-restart-monthly.run` runscript crashes with the following error:

> $ esm_runscripts echam-mistral-restart-monthly.run -e python_test_esm
> Started from:  /mnt/lustre01/pf/a/a270119/esm_testing
> starting :  compute
> Traceback (most recent call last):
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1324, in recursive_get
>     result = config_to_search[this_config]
> KeyError: 'model_dir'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1438, in actually_find_variable
>     var_result = recursive_get(full_config, config_elements)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1331, in recursive_get
>     return recursive_get(result, my_config_elements)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1327, in recursive_get
>     "Exactly None! Couldn't find an answer for:", my_config_elements
> ValueError: ("Exactly None! Couldn't find an answer for:", [])
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1324, in recursive_get
>     result = config_to_search[this_config]
> KeyError: 'model_dir'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1446, in actually_find_variable
>     var_result = recursive_get(full_config, config_elements)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1331, in recursive_get
>     return recursive_get(result, my_config_elements)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1327, in recursive_get
>     "Exactly None! Couldn't find an answer for:", my_config_elements
> ValueError: ("Exactly None! Couldn't find an answer for:", [])
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/pf/a/a270119/.local/bin/esm_runscripts", line 8, in <module>
>     sys.exit(main())
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_runscripts/cli.py", line 167, in main
>     Setup = SimulationSetup(command_line_config)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_runscripts/esm_sim_objects.py", line 50, in __init__
>     self.get_total_config_from_user_config(user_config)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_runscripts/esm_sim_objects.py", line 249, in get_total_config_from_user_config
>     self.config.finalize()
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2163, in finalize
>     self.run_recursive_functions(self)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 2180, in run_recursive_functions
>     isblacklist=isblacklist,
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1287, in recursive_run_function
>     tree + [key], value, level, func, *args, **kwargs
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1287, in recursive_run_function
>     tree + [key], value, level, func, *args, **kwargs
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1279, in recursive_run_function
>     tree + [None], item, level, func, *args, **kwargs
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1272, in recursive_run_function
>     right = func(tree + [None], right, *args, **kwargs)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1366, in find_variable
>     var_result, var_attrs = actually_find_variable(tree, var, full_config)
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1449, in actually_find_variable
>     raise EsmParserError("Sorry, a variable was not resolved: %s not found" % (rhs))
>   esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: model_dir not found

I am using a freshly installed esm-tools version with all packages up-to-date. The account, model dir and work dir are set according to my setup.
`MODEL_DIR_echam=/pf/a/a270119/echam-6.3.04p1/`
`BASE_DIR=/work/aa0238/a270119/esm-experiments/`
Is it possible that the echam runscript has not yet been updated. E.g. this dir does not exist on mistral:
`INI_RESTART_DIR_echam=/work/ab0246/a270064/esm-experiments/lgm_anm/restart/echam`
However, replacing it with a existing (`.../lgm_anm20/restart/echam`) and similar dir does not solve the issue.

*edit: sorry there was a copy-paste error in the last line of the error msg - now corrected*

**Comment by mandresm** [comment]
By looking very fast into it (I might need to look more in detail into it), I have found that there are no bins in the folder `/pf/a/a270119/echam-6.3.04p1/bin`. Did echam compile correclty?

**Comment by SpontEIN** [comment]
I recompiled: `esm_master comp-echam-6.3.04p1`

and get the following error at the very end:
 
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /pf/a/a270119/echam-6.3.04p1/src/echam/bin/echam6
> Traceback (most recent call last):
>   File "/pf/a/a270119/.local/bin/esm_master", line 8, in <module>
>     sys.exit(main())
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_master/cli.py", line 131, in main
>     env.cleanup_dummy_script()
>   File "/pf/a/a270119/.local/lib/python3.6/site-packages/esm_environment/esm_environment.py", line 174, in cleanup_dummy_script
>     os.remove("dummy_script.sh")
> NameError: name 'os' is not defined

**Comment by pgierz** [comment]
That was a mistake I made cleaning up and writing docstrings; accidentally erased the `import os`, sorry.

If you update to esm_environment 4.1.1 it should work...

Try:
```
$ esm_versions upgrade esm_environment
$ esm_versions check # Important is that esm_env is at 4.1.1
$ rm -rf <whatever your compile directory is>
$ esm_master install-echam-6.3.04p1
```

**Comment by SpontEIN** [comment]
I followed your steps and reinstalled echam. esm_env version is at 4.1.1.. No error at end of compilation.
However there is still no executable in `/pf/a/a270119/echam-6.3.04p1/bin`
But there is a new `echam6` executable in `/pf/a/a270119/echam-6.3.04p1/src/echam/bin/`

**Comment by pgierz** [comment]
Ah, ok, then the "install" part of esm-master didn't work. Two possible solutions:

1) Copy the bin by hand (this is basically what esm_master does for you anyway)
2) We fix that (probably should be done anyway)

For 2...I'm not sure if the "install" e.g. copying the bins only works for setups. Since echam by itself is just a component, that might not happen. Could you post what esm_master spits out before it starts compiling? There should be something like "executing these commands" or something at the very top...

**Comment by SpontEIN** [comment]
Executing commands in this order:
         git clone -b 6.3.04p1 https://a270119@gitlab.dkrz.de/modular_esm/echam6.git echam-6.3.04p1
         cd echam-6.3.04p1
         mkdir -p build; cd build; cmake ..;   make install -j `nproc --all`
         cd ..
         mkdir -p echam-6.3.04p1/bin

**Comment by SpontEIN** [comment]
after copying exe to `/pf/a/a270119/echam-6.3.04p1/bin` I still get the same error as in my initial post.

**Comment by pgierz** [comment]
So, the error is during the run. Are you using a shell or yaml runscript? @MiguelAndresMartinez, do we have an example of how to translate an old shell runscript to a new yaml runscript? The shell ones should be supported but we should encourage people to switch...

**Comment by SpontEIN** [comment]
Yes, the error occurs, when launching `esm_runscripts echam-mistral-restart-monthly.run -e python_test_esm -c`.

Where `echam-mistral-restart-monthly.run` is the esm-tools default echam-mistral run script from the repository. I just want to run this script to figure out if my esm-tools setup is working properly.

an example of a shell script to YAML conversion would certainly be nice. Maybe this could be done with the deafult  `echam-mistral-restart-monthly.run` shell script.

**Comment by mandresm** [comment]
> 
> 
> So, the error is during the run. Are you using a shell or yaml runscript? @MiguelAndresMartinez, do we have an example of how to translate an old shell runscript to a new yaml runscript? The shell ones should be supported but we should encourage people to switch...

I don't think we have an example on the translation but I can work on that.

I think the first error is solved by substituting `MODEL_DIR_echam` by `MODEL_DIR`. Then, as @SpontEIN mentioned, the restart files in the default runscript do not exist in mistral. Also it complains about not being able to find the binaries inside the `echam-version/bin` folder:

```
========================================================
MISSING FILES:
--  /work/ab0995/a270152/esm_yaml_test//echam4spontein/run_20000101-20000131/bin/echam//echam6:
        --> /pf/a/a270152/model_codes/echam-6.3.04p1//bin/echam6
--  /work/ab0995/a270152/esm_yaml_test//echam4spontein/run_20000101-20000131/restart/echam//restart_echam4spontein_echam.nc:
        --> /work/ab0246/a270064/esm-experiments/lgm_anm20/restart/echam/restart_lgm_anm20_37991231_echam.nc
--  /work/ab0995/a270152/esm_yaml_test//echam4spontein/run_20000101-20000131/restart/echam//restart_echam4spontein_accw.nc:
        --> /work/ab0246/a270064/esm-experiments/lgm_anm20/restart/echam/restart_lgm_anm20_37991231_accw.nc
--  /work/ab0995/a270152/esm_yaml_test//echam4spontein/run_20000101-20000131/restart/echam//restart_echam4spontein_co2.nc:
```

**Comment by SpontEIN** [comment]
>  think the first error is solved by substituting `MODEL_DIR_echam` by `MODEL_DIR`

this helped!

now I am trying to solve the MISSING FILES problems:

looking into: `/work/ab0246/a270064/esm-experiments` I see a lot of echam runs from which to possibly restart. in the old esm-tools version, the default run scenario was `PI-CRTL`.

looking into the `pi` dir (`/work/ab0246/a270064/esm-experiments/pi/restart/echam`): The restarts file here are called e.g. `/work/ab0246/a270064/esm-experiments/pi/restart/echam/restart_pi_echam_32141231.nc` -> this file is linked via: `restart_pi_echam.nc` 

**Problem:** esm-tools look for `restart_pi_32141231_echam.nc` and not `restart_pi_echam_32141231.nc`:

How can we exchange `echam` with `32141231` or omit the numbers entirely.?

Tried the following. I set the the restart files in the run script `echam-mistral-restart-monthly.run` to :

    INI_RESTART_DIR_echam=/work/ab0246/a270064/esm-experiments/pi/restart/echam/
    #INI_PARENT_DATE_echam= **blank**
    INI_PARENT_EXP_ID_echam=pi

Then the `echam.yaml` file automatically assumes `ini_parent_date: 22941231`

**Comment by mandresm** [comment]
I was trying to solve the binary issue first (esm-tools/esm_master#9), still not merged but it will be merged by the end of the day).

> **Problem:** esm-tools look for `restart_pi_32141231_echam.nc` and not `restart_pi_echam_32141231.nc`:

I realised about that yesterday too. I'll be looking into that now.

**Comment by mandresm** [comment]
The binary copy issue was solved on Friday (esm-tools/esm_master#9) and now all the `.run` standalone runscripts have `MODEL_DIR` instead of `MODEL_DIR_<component>` (#82).

I'll be now addressing this:


> **Problem:** esm-tools look for `restart_pi_32141231_echam.nc` and not `restart_pi_echam_32141231.nc`

**Comment by mandresm** [comment]
The problem with the restarts is solved now in the default runscript [echam-mistral-restart-monthly.run inside the branch hotfix/echam_standalone_runscripts](https://github.com/esm-tools/esm_tools/blob/hotfix/echam_standalone_runscripts/runscripts/echam/echam-mistral-restart-monthly.run). It will be soon merged into release.

@SpontEIN, in order to get all done correctly I recommend you to follow these steps:

1. `esm_versions upgrade`
2. Checkout the `hotfix/echam_standalone_runscripts` from `esm_tools` (once is merged you will just need to pull from `release`)
3. Note that the relevant files for this fix are `echam-mistral-restart-monthly.run` and `echam-old-ini_restart.yaml` in `esm_tools/runscripts/echam/`.
4. Reinstall echam and check that the binaries are place where they should (`echam-<version>/bin`)
5. Add the modifications needed in `echam-mistral-restart-monthly.run`

**Note:**
1. I used the `lgm_anm20` restarts as a default and as `INI_PARENT_DATE` I used `38991231`, instead of `37991231`, because the last one does not exist.
2. The restart file for jsbach `/work/ab0246/a270064/esm-experiments/lgm_anm20/restart/jsbach/restart_lgm_anm20_land_38991231.nc` is the only file missing and it is not present in any of the `lgm_anm` or the `pi` restarts. So that might cause problems.

I will be working on yaml equivalent runscript and after that I'll proceed with merging into `release`. Please, let me know if you encounter more difficulties or if the fix worked.

**Comment by SpontEIN** [comment]
I followed your steps and got to the point at **Note 2.**
The only missing file is now:

    MISSING FILES:
    --  /work/aa0238/a270119/esm-experiments//python_esm_test/run_20000101-20000131/restart/jsbach//restart_python_esm_test_land.nc: 
        --> /work/ab0246/a270064/esm-experiments/lgm_anm20/restart/echam/../jsbach/restart_lgm_anm20_land_38991231.nc

I checked other files endings:   `*40951231.nc` seems to be available in echam and jsbach

```
a270119@mlogin103:restart$ find . -name "*40951231.nc"
./echam/restart_lgm_anm20_co2_40951231.nc
./echam/restart_lgm_anm20_echam_40951231.nc
./echam/restart_lgm_anm20_sp6h_40951231.nc
./echam/restart_lgm_anm20_g3bim_40951231.nc
./echam/restart_lgm_anm20_accw_40951231.nc
./echam/restart_lgm_anm20_spim_40951231.nc
./echam/restart_lgm_anm20_g3b1hi_40951231.nc
./echam/restart_lgm_anm20_g3bday_40951231.nc
./echam/restart_lgm_anm20_g3bid_40951231.nc
./echam/restart_lgm_anm20_aclcim_40951231.nc
./echam/restart_lgm_anm20_glday_40951231.nc
./echam/restart_lgm_anm20_glim_40951231.nc
./hdmodel/restart_lgm_anm20_hd_40951231.nc
./jsbach/restart_lgm_anm20_surf_40951231.nc
./jsbach/restart_lgm_anm20_jsbach_40951231.nc
./jsbach/restart_lgm_anm20_yasso_40951231.nc
./jsbach/restart_lgm_anm20_veg_40951231.nc
./jsbach/restart_lgm_anm20_nitro_40951231.nc
./jsbach/restart_lgm_anm20_jsbid_40951231.nc
```
Can I change this myself? ... setting `INI_PARENT_DATE_echam=40951231` in the runscript, does **not** do the trick

edit: the  `restart_lgm_anm20_land_40951231.nc` is also missing ... so that will not work ... but I still would like to know how to change the `INI_PARENT_DATE_echam=xyzxyz` ?

**Comment by pgierz** [comment]
Question from my side: are you using the LGM simply because it was in the default? That is probably one of paleo runs, and might even have come from a different version of echam/jsbach. Maybe you can use a Preindustrial run?

**Comment by mandresm** [comment]
> Question from my side: are you using the LGM simply because it was in the default? That is probably one of paleo runs, and might even have come from a different version of echam/jsbach. Maybe you can use a Preindustrial run?

Yes, I used LGM because it was the default on the runscript. I would gladly change that to a Preindustrial run. @pgierz, could you please provide a suggested run.



> Can I change this myself? ... setting `INI_PARENT_DATE_echam=40951231` in the runscript, does **not** do the trick

I just did it and it worked for me with the exception of the `land` file. Could you please provide a few more details on how that is not working?

**Comment by SpontEIN** [comment]
> I just did it and it worked for me with the exception of the `land` file. Could you please provide a few more details on how that is not working?

I set the following:

```
INI_RESTART_DIR_echam=/work/ab0246/a270064/esm-experiments/lgm_anm20/restart/echam
INI_PARENT_DATE_echam=40951231
INI_PARENT_EXP_ID_echam=lgm_anm20
```
When I execute the runscript (`esm_runscripts -U echam-mistral-restart-monthly.run -e python_esm_test -c`) it still complains that the file with the default `INI_PARENT_DATE_echam` is missing:

`MISSING FILES: --> /work/ab0246/a270064/esm-experiments/lgm_anm20/restart/echam/../jsbach/restart_lgm_anm20_land_38991231.nc`

**Comment by mandresm** [comment]
@SpontEIN, have you deleted the experiment directory before you run again `esm_runscripts -U echam-mistral-restart-monthly.run -e python_esm_test -c`?

If not, you'll get the old configuration. Please, let me know if that works. I am going to switch to a preindustrial restart, I have already the yaml script, and then I'll merge.

**Comment by SpontEIN** [comment]
Yes that worked. But I thought the `-U` option will do exactly this ... updating the files in the existing dir.

**Comment by mandresm** [comment]
ah okay, I'll look into that now

**Comment by mandresm** [comment]
@SpontEIN, I've been checking the code and the `-U` flag is meant to update ESM-Tools files into the experiment folder, in case ESM-Tools has been updated and you need those updates in your experiment.

Note that runscripts are what we expect for the average user to be modifying. Therefore, the runscripts inside `esm_tools/runscripts` are only defaults, and consequently, not considered to be updated with the `-U` flag. Also, I can see potential risks of an option for updating runscripts with new modifications...

I think that if updating an experiment with an updated runscript is required, it needs to at least use a different flag. I'll talk to my colleagues about this possibility next Monday. Of course, please feel free to provide your thoughts on it, or even open a new issue proposing this possible new feature.

For the mean time, I advice you to delete the previous experiment folder and rerun.

**Comment by SpontEIN** [comment]
Thanks for your explanation.

In general I think it is very important for the user to understand, that just relaunching the same experiment with the same call of a runscript, will **not** consider the changes that you just applied to your runscript (without deleting the experiment folder before). 

It feels very counter intuitive. I imagine, that this is a pit fall, that many user will stumble over. It is just the most common thing that will happen ... you launch a run ... have e.g. a small typo in the runscript ... you correct it ... you relaunch ... your correction has no effect ... you wonder why? There should be at least an info about this or the default should be, that the new/correcetd runscript is used.

**Comment by mandresm** [comment]
I totally agree with you, so I'll be working in documenting this inside the ESM-Runscripts chapter in [readthedocs](https://esm-tools.readthedocs.io/en/develop/). But we will also consider adding a warning, specifying that the original runscript and the new one are different and how user should proceed.

**Comment by SpontEIN** [comment]
Hi is there any progress in solving the missing file issue?

> MISSING FILES: --> /work/ab0246/a270064/esm-experiments/lgm_anm20/restart/echam/../jsbach/restart_lgm_anm20_land_38991231.nc

I could not locate any file named `restart_*_land_*.nc` in `/pool/data/` nor `/work/ab0246/a270064/esm-experiments/`

**Comment by mandresm** [comment]
Hi! Sorry for the absence of updates, but I was not able to resume using Mistral until yesterday. I'll be looking at it soon.

I talked to @pgierz and we got to the conclusion that we will change the default echam restart runscript to restart from one default experiment that I will prepare.

**Comment by pgierz** [comment]
Still a problem in 4.2? If not, I'd close this

**Comment by SpontEIN** [comment]
hmm ... I checked out the new version 4.2. (via `esm_versions upgrade`)

Did a check run: all the files missing (see further up) are missing **again**? 
Starting with the echam6 binary. esm-tools still tries to look for it at the wrong place.

just to be sure: 
```
~$ esm_versions check
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.0
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1 (development install, on branch: release, describe=v4.2.1-2-g4cac0ee)
esm_tools: 4.2.0 (development install, on branch: release, describe=v4.2.0-13-gd37307b)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.4.0
```

**Comment by mandresm** [comment]
With release 5 the enhancement for `-U` is added. Now `-U` really updates the runscript. See #175 for more details about it.

All the restart file issues for `ECHAM` should be also solved with release 5.

Therefore, I close this issue.
