### ISSUE TITLE
Missing ECHAM input files @Levante (?)

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#775]
> reported via email by @mbutzin 

I am trying a cold start of AWIESM-2.1 @Levante but ECHAM crashes because the following input files are not found:

WARNING: File not found: /pool/data/ECHAM6/FESOM2/MESHES_FESOM2.1/core2/tarfilesT63/input/echam6/T63CORE2_jan_surf.nc
2022-08-09 16:14:57.200646
WARNING: File not found: /pool/data/ECHAM6/FESOM2/MESHES_FESOM2.1/core2/tarfilesT63/input/echam6/T63CORE2_VGRATCLIM.nc
2022-08-09 16:14:57.539122
WARNING: File not found: /pool/data/ECHAM6/FESOM2/MESHES_FESOM2.1/core2/tarfilesT63/input/echam6/T63CORE2_VLTCLIM.nc
2022-08-09 16:14:57.539198

ls: cannot access '/pool/data/ECHAM6/FESOM2/MESHES_FESOM2.1': No such file or directory

Do you know where these files have gone?

P.S. You may find my runscript there:
/home/a/a270108/esm_runscripts/awiesm-2.1-transit_levante.yaml

**Comment by pgierz** [comment]
If the pools are indeed broken, I need to know (I made the mistake of taking on the task of being pool guru). I've gathered all the important people to contact in the case of incorrect or badly named files and normally email a batch worth of requests each Monday for systems I do not have privilege enough to fix on my own. For more urgent cases, just let me know and I'll make louder noises earlier with the appropriate people. 

At the moment I suspect a bad config though. Miguel and I are on support duty tomorrow (10 August) but one of us will look into it.

**Comment by mbutzin** [comment]
Update: The new pool directory for AWIESM2.1 at Levante seems to be 
/work/ab0246/pool
and the missing input files can be found there
/work/ab0246/pool/FESOM2/MESHES/mesh_CORE2_finaltopo_mean/tarfilesT63/input/

**Comment by pgierz** [comment]
@mbutzin: did you modify a global config or just your local runscript to fix that? In either case, it should wander into the defaults at some point. 

But, good that it is working for you now :-)

**Comment by mbutzin** [comment]
Am 09.08.22 um 18:16 schrieb Paul Gierz:
> @mbutzin: did you modify a global config or just your local runscript to fix that? In either case, it should wander into the defaults at some point.
>
> But, good that it working for you know :-)
>
I have only fixed my personal runscript because I am still in a testing 
phase.
