### ISSUE TITLE
Unknown Error on Levante 

### ISSUE THREAD

**Issue by StanleyAgu1** [esm-tools/esm_tools#808]
Hello.

I am trying to run some experiments on Levante, I started a historical run and a PI run, then a modified historical run, all starting from the year 1850-2015. After like 2 years, they all stops and I got this error on the log files. I don’t know what seem to be the problem.

**To Reproduce**
Below are my experiments 

/work/ab0246/a270162/esm-experiments

1. expA/
2. expA_perturbed_hist/
3. expA_perturbed_PI
4. expA_unperturbed_PI5. 

When I checked the log file, I saw this error

FileNotFoundError: [Errno 2] No such file or directory: "{'NONE_YET': {}}/expA_vcs_info.yaml"
                        

 - Supercomputer: [Levante]
 - Version [2.1]
 - 

I need some help on this. Thank you

**Comment by StanleyAgu1** [comment]
Hi @pgierz 

please can you help me here? I can provide more information if needed, or we can arrange a meeting so I can show you my scripts and runs.

thank you

**Comment by pgierz** [comment]
What esm Tools Version are you on?

**Comment by StanleyAgu1** [comment]
Version 2.1

**Comment by pgierz** [comment]
That's probably you awiesm version, I need to know which version of `esm-tools` you have. 

You triggered a bug which I thought I had fixed a few weeks ago, so I suggest updating.

**Comment by StanleyAgu1** [comment]
Ok how do I find out which version of esm-tools I have. Is their some way of checking? (Lars helped me set it up)

**Comment by pgierz** [comment]
Hi Stanley,

Sorry for the late response. You can check the version with:

```
$ esm_tools --version
```

The newest version is currently `6.14.0`. If you need to update, just go to your esm-tools folder, do `git pull`, and run `install.sh` again. Check the version after that, it should be newer.

**Comment by denizural** [comment]
@pgierz, I think the latest version is 6.13.10

**Comment by pgierz** [comment]
No: https://github.com/esm-tools/esm_tools/tree/v6.14.0

**Comment by denizural** [comment]
@pgierz 
Do we have a problem: https://github.com/esm-tools/esm_tools/tags
Latest bump is 6 days ago
https://github.com/esm-tools/esm_tools/commit/25a13b91ff3cf6045f474b312cfc40123dafd1fb
I think you bumped your branch rather than the release: https://github.com/esm-tools/esm_tools/commit/56d72b9675f1c62630240c52b22bccd7b714daa0

**Comment by pgierz** [comment]
Ok that's a separate problem. @StanleyAgu1, you should end up on 6.13.10

**Comment by StanleyAgu1** [comment]
@pgierz Thank you. I updated my esm_tools and ended up on version 6.8.0

**Comment by StanleyAgu1** [comment]
After updating it, I restarted my experiment and it started working. But it stopped again after 20 years
