### ISSUE TITLE
Fix Versions and Releases

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#814]
The version numbers have diverged. I'll take a day next week to correct everything and maybe also automate the release procedure.

**Comment by denizural** [comment]
I thought that the `bump` command would not trigger any version bump action on the branches other than `release`. I am sure GitHub actions have some workarounds for that.

**Comment by denizural** [comment]
I think I understood what happened 
- you wanted to merge the `feat` on to `release`: https://github.com/esm-tools/esm_tools/pull/756
- but you merged `release` on the `feat`
- then you hit `#bump` button
- the tag is pushed to the repo but it only marks the pull request not a commit on the release so when someone pulls the tools they always get the tag that is attached to `release`.

**Comment by pgierz** [comment]
Well: the reason the tags diverged is because the pull request sat around for so long.

**Comment by pgierz** [comment]
Out of date, closing.
