### ISSUE TITLE
esm_tools oasis restart (esm_master 6.12.8)

### ISSUE THREAD

**Issue by PengyangSong** [esm-tools/esm_tools#816]
Hi all,
I run into a problem that oasis cannot restart from another folder.
I wanted to re-run my last 10 years (2141-2150) with some diagnostic outputs.

What I did is below:
```
psong@ollie0:/work/ollie/psong/AWIESM-2.1-wiso$ esm_runscripts PI_CTRL_diag.yaml -e PI_CTRL_diag -c
```
Part of the warning says:
```
WARNING: File not found: /work/ollie/psong/paleo_work/AWIESM-2.1-wiso/PI_CTRL_prod/restart/echam/restart_PI_CTRL_prod_spim_21401231.nc
2022-09-02 09:47:21.796925
WARNING: File not found: /work/ollie/psong/paleo_work/AWIESM-2.1-wiso/PI_CTRL_prod/restart/echam/restart_PI_CTRL_prod_rad_21401231.nc
2022-09-02 09:47:21.797785
WARNING: File not found: /work/ollie/psong/AWIESM-2.1-wiso/PI_CTRL_prod/restart/oasis3mct/o2a_flux_21500101-21501231
2022-09-02 09:47:23.085641
WARNING: File not found: /work/ollie/psong/AWIESM-2.1-wiso/PI_CTRL_prod/restart/oasis3mct/a2o_flux_21500101-21501231
2022-09-02 09:47:23.087375
```
The former two are right because I do not have "spim" and "rad" streams in the ECHAM6 folder. But the latter two seem to search from the wrong folder and wrong file.  The folder should be /work/ollie/psong/paleo_work/AWIESM-2.1-wiso/... and the file should be 2140...

What I have in my yaml file is :
```
general:
    ini_parent_exp_id: "PI_CTRL_prod"
    ini_parent_dir: "/work/ollie/psong/paleo_work/AWIESM-2.1-wiso/${ini_parent_exp_id}/"
oasis3mct:
    lresume: 1
    ini_parent_date: "21401231"
    ini_parent_exp_id: "${general.ini_parent_exp_id}"
    ini_parent_dir: "${general.ini_parent_dir}/restart/oasis3mct/"
```
I think this might come from some bug in esm_tools, do you have any idea which file should be correct in esm_tools?
Pengyang

**Comment by pgierz** [comment]
Hi Pengyang,

I'll look into this. I'll give you an update in a bit. Either you uncovered a real bug, or your YAML file needs a small tweak.

**Comment by pgierz** [comment]
Hi Pengyang,

A follow up question: are you giving your experiment a new name?

Best,
Paul

**Comment by PengyangSong** [comment]
Hi Paul, I gave it a new name.

There seems to be two problems:
1. ini_parent_dir in oasis is not working
2. oasis cannot automatically find the correct file by ini_parent_date, we should change the name by hand first.

Best,
Pengyang

**Comment by mandresm** [comment]
Hi @PengyangSong Penyang, can you please paste your whole runscript here?

**Comment by PengyangSong** [comment]
> Hi @PengyangSong Penyang, can you please paste your whole runscript here?

I think this is because of the difference naming between the old and new esm_tools releases. Now I solve this by changing file names by hand.
Yesterday I post a wrong reply here because I thought this is the Discussion #673

**Comment by mandresm** [comment]
Is this problem solved? If that's the case the issue can be closed.
