### ISSUE TITLE
documentation for unistall is out of date

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#817]
`esm_versions upgrade esm_parser`

`esm_versions` no longer exists

**Comment by pgierz** [comment]
...correct. Who tried this? And which documentation page is referring to the old way of doing things?

**Comment by JanStreffing** [comment]
Me!
https://esm-tools.readthedocs.io/en/latest/installation.html#uninstall-esm-tools

**Comment by pgierz** [comment]
OK! Sorry for the delay. Here is a relevant PR: https://github.com/esm-tools/esm_tools/pull/822.
