### ISSUE TITLE
Run and Compile scripts start a login shell?

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#853]
Moin,

I am setting up the `albedo.yaml` file for the new computer, and it seems as if both the compile and run scripts always set `/bin/bash -l`. 

Just to open up for discussion: why is this? This is happening in:

```diff
diff --git a/src/esm_environment/esm_environment.py b/src/esm_environment/esm_environment.py
index 2c3d8cb3..37fa60c3 100644
--- a/src/esm_environment/esm_environment.py
+++ b/src/esm_environment/esm_environment.py
@@ -541,7 +541,7 @@ class EnvironmentInfos:
         with open("dummy_script.sh", "w") as script_file:
             # Write the file headings
             script_file.write(
-                f'#!{self.config.get("sh_interpreter", "/bin/bash")} -l\n'
+                f'#!{self.config.get("sh_interpreter", "/bin/bash")}\n'
             )
             script_file.write(
                 "# Dummy script generated by esm-tools, to be removed later: \n"
```

If there are no very good reasons to keep this, I would remove it. Both a compile and a run job are by definition not interactive and therefore don't need to explicitly trigger an interactive sub shell. Or am I mistaken?

**Comment by mandresm** [comment]
I think the best test one can do is to try to compile AWICM3 in Juwels. AWICM3 in Juwels uses environment variables such as `$USER` to overcome the fact that there is no pool in Juwels and the pools have to be duplicated through out the different projects. If AWICM3 works in Juwels I would expect there are no problems.

**Comment by pgierz** [comment]
I have not actively worked on Juwels for a long time, so maybe some else can check that much faster than I can?

**Comment by mandresm** [comment]
I can do that

**Comment by mandresm** [comment]
Is there a branch with those changes?

**Comment by pgierz** [comment]
Unfinished, but yes, you can use `feat/albedo` You might still need to click through the `pdb`, I am still debugging some things in `esm-master` (starting the sub shell seems to be causing strange behaviour)

**Comment by mandresm** [comment]
It can compile AWICM3 without problems in juwels :)

I see, go for it. For the merging of Albedo I will do real tests for every  models so we will have the chance to catch any weird thing in other computers.

**Comment by nwieters** [comment]
@pgierz @mandresm should the solution of this issue be merged to release by its own pull request or it is enough to wait for the merge of `feat/albedo_wip`?

**Comment by pgierz** [comment]
I would close this one without merging, explicitly generating a login shell is probably a bad idea: we then need to ensure that "whatever" the end user does in their login scripts does not bite us in the butt. We don't want that (or, well, I don't want that. "We" maybe also don't want that)
