### ISSUE TITLE
Provide a python installation on albedo that is supported (3.10 is not supported by esm-tools)

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#861]
**Describe the problem you are facing**
We probably need version 3.9

**To Reproduce**
just follow the ten-steps howto, loading standard git and python versions available on albedo, until reaching this error:

```
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: tqdm in /albedo/soft/sw/conda-sw/py-3.10/plotting/lib/python3.10/site-packages (from esm-tools==6.17.3) (4.64.1)
Requirement already satisfied: typing_extensions>=3.10.0.0 in /albedo/soft/sw/conda-sw/py-3.10/plotting/lib/python3.10/site-packages (from esm-tools==6.17.3) (4.4.0)
Collecting xdgenvpy
  Downloading xdgenvpy-2.3.5-py3-none-any.whl (13 kB)
ERROR: Package 'esm-tools' requires a different Python: 3.10.8 not in '<3.10,>=3.6'
stepanek@albedo0:~/esm_tools$ which python
/albedo/soft/sw/conda-sw/py-3.10/plotting/bin/python
stepanek@albedo0:~/esm_tools$ python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0] on linux

```

**Runscrip and other relevant files**
NA

**Screenshots**
NA

**System (please complete the following information):**
 - Supercomputer: albedo0.dmawi.de
 - Version: happens during installation of the current standard version provided by a git clone

**Comment by chrisdane** [comment]
Just adding information, with the python bin
```
/albedo/soft/sw/conda-sw/r-4.2/rstudio/bin/python # Python 3.8.15
```
the esm_tools installation works (this py bin is automatically loaded on `module load r`).

**Comment by christian-stepanek** [comment]
> 
Thanks @chrisdane 
So loading R before installing esm-tools helps. Probably it would still be good to have the proper python version available as an won module?

**Comment by mandresm** [comment]
@pgierz, are you on this? I have a fix for this I made a couple of days ago. I could PR.

**Comment by mandresm** [comment]
I mean, is obviously not only about changing the `setup.py` python version, but also solving the problems of `collections.Mapping` having changed to `collections.abc.Mapping`.

**Comment by pgierz** [comment]
The Python in R should **NOT** be used. 

You should now have python 3.7 until 3.9

**Comment by pgierz** [comment]
And no, I can't get rid of the Python in the R module. That's just how it is. I can maybe block it somehow...

**Comment by pgierz** [comment]
@mandresm, if that is already there to use and just needs a PR, I see no reason to avoid supporting Python 3.10

**Comment by pgierz** [comment]
@chrisdane and @christian-stepanek, you will not get past the `install.sh` (or whatever your preferred workflow for installing esm-tools is), but could you please clean up anything you currently might have and use the module `python/3.9.12`?

**Comment by mandresm** [comment]
@pgierz, there is a PR (#865) to also get passed python errors in `esm_master` and `esm_runscripts`, once you merge it, ESM-Tools commands should be usable in Albedo.

**Comment by pgierz** [comment]
Reported also by Christian Stepanek that with module 3.9.12 it works, so, this is now closed.
