### ISSUE TITLE
compilation error with albedo.yaml from feat/albedo

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#868]
Scanning dependencies of target psmile
[ 80%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_kinds.F90.o
[ 81%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_data.F90.o
[ 82%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_sys.F90.o
[ 83%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_mpi.F90.o
[ 84%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_parameters.F90.o
[ 85%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_string.F90.o
/albedo/home/stepanek/esm_tools/model_codes/awiesm-2.1/oasis/lib/psmile/src/mod_oasis_string.F90:1253:0:

      list = trim(l1)//":"//trim(list)
 
Warning: ‘__builtin_memset’ specified size between 9223372036854775808 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
[ 86%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_ioshr.F90.o
[ 87%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_io.F90.o
f951: Fatal Error: Reading module ‘netcdf’ at line 1 column 2: Unexpected EOF
compilation terminated.
make[2]: *** [lib/psmile/CMakeFiles/psmile.dir/build.make:153: lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis_io.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: lib/psmile/CMakeFiles/psmile.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
Traceback (most recent call last):
  File "/albedo/home/stepanek/.local/bin/esm_master", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_master')())
  File "/albedo/home/stepanek/esm_tools/src/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/albedo/home/stepanek/esm_tools/src/esm_master/esm_master.py", line 107, in main_flow
    user_task.execute(ignore_errors)  # env)
  File "/albedo/home/stepanek/esm_tools/src/esm_master/task.py", line 511, in execute
    subprocess.run(
  File "/albedo/soft/sw/spack-sw/python/3.9.12-aohn73j/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./comp-oasis3mct-2.8-paleodyn_script.sh']' returned non-zero exit status 2.
stepanek@albedo0:~/esm_tools/model_codes$

**Comment by pgierz** [comment]
This problem has been solved, the latest AWI-ESM compile challenge on Albedo is with the iceberg code, but oasis compiles without problems :-)
