### ISSUE TITLE
Compiling OASIS in an AWI-CM Version: mkdir: cannot create directory ‘../include’: File exists

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#87]
When I do 
`esm_master clean-awicm...`
and again
`esm_master comp_awicm...`
I get the following error:

```
[ 98%] Building Fortran object lib/psmile/CMakeFiles/psmile.dir/src/mod_oasis.F90.o
[100%] Linking Fortran static library libpsmile.a
[100%] Built target psmile
mkdir: cannot create directory ‘../include’: File exists
```

I guess in the `clean-...` function for oasis, the include folder is not deleted.

I use esm_tools in the version:
```
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.1
esm_database : 4.0.0
esm_environment : 4.1.1
esm_master : 4.1.2
esm_parser : 4.1.1
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.1.4
esm_tools : 4.1.6
esm_plugin_manager : 4.0.1
esm_version_checker : 4.3.1
```

**Comment by mandresm** [comment]
Hi @nwieters, could you please provide the path of the awicm installation?

I'll have a look at it.

**Comment by dbarbi** [comment]
I fixed this already, have a look at branch refac_master of esm_tools

Miguel <notifications@github.com> schrieb am Fr., 17. Juli 2020, 11:56:

**Comment by nwieters** [comment]
Thank you. I was able to fix this in my branch by hand. I will close the issue, because it is going to be fixed in release by the next merge.
