### ISSUE TITLE
AWI-CM3-master not finding orbital forcing namelists

### ISSUE THREAD

**Issue by fernandadialzira** [esm-tools/esm_tools#871]
With the implementation of the new ECE4 code for AWI-CM3, activating the orbital forcing code in the transcript leads to the model not being able to find such namelist.

When comparing `AWI-CM3-master` and `AWI-CM3-v3.1` `fort.4`, one sees that both miss the `NAMORB` section. So this should not be the main issue, as just by `add_namelist_changes` in the runscript, it worked for `AWI-CM3-v3.1`. 

Now when one looks at the location of the namelist and source code:

**AWI-CM3-master**
namorb.h:`oifs-43/src/ecearth/orbital/`
yomorb.F90:`oifs-43/src/ecearth/orbital/`

**AWI-CM3-v3.1**
namorb.h:`oifs-43r3/src/ifs/namelist/`
yomorb.F90:`oifs-43r3/ifs/module/`
**To Reproduce**

I tried to change the location of these files on `AWI-CM3-master` and recompiled the model to see whether the namelists would be found. However, it led to the same error.

 - Supercomputer: juwels
 - Version release - 6.18.0
 - Models' folder - `/p/project/chhb20/fmatos/runtime/awicm3-master/model_codes`
 - Runscript - `/p/project/chhb20/fmatos/runtime/awicm3-master/runscript_testing/pi_orb_forcing.yaml`
 - Log with error described: `/p/project/chhb20/fmatos/runtime/awicm3-master/runscript_testing/pi_orbforc_005_c.log`

**Additional context**
In the runscript, the section for NAERAD also led to the same error, but this module refers to the GHG concentrations, and the implementation of it is still being discussed for the future.

**Comment by mandresm** [comment]
The `namelist_changes` section of the runscript was missing one nesting level (the namelist name) and that's why it was not working. Better error handling is required here to catch this type of errors.
