### ISSUE TITLE
Error while recomp

### ISSUE THREAD

**Issue by nwieters** [esm-tools/esm_tools#88]
When doing 
`esm_master recomp-awicmmod-2.0-esm-interface-oasis`

I get the following error:

`Missing folder awicmmod-2.0-esm-interface-oasis/awicmmod-2.0-esm-interface-oasis detected. Please run 'make get-awicmmod-2.0-esm-interface-oasis' first.`

But the folder awicmmod-2.0-esm-interface-oasis exists.

Why is `recomp` looking for the model folder in the model folder?

I use esm_tools release version:
`esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.1
esm_database : 4.0.0
esm_environment : 4.1.1
esm_master : 4.1.2
esm_parser : 4.1.1
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.1.4
esm_tools : 4.1.6
esm_plugin_manager : 4.0.1
esm_version_checker : 4.3.1`

**Comment by pgierz** [comment]
What directory were you in?

**Comment by nwieters** [comment]
I think I was in the folder just above the model I wanted to recompile.
But I can try again.

**Comment by nwieters** [comment]
I tested it again and still get the error:
`Missing folder awicm-2.0/awicm-2.0 detected. Please run 'make get-awicm-2.0' first.`
I am in my work folder on ollie. And there is a version of awicm-2.0.
I if do

`esm_master recomp-awicm-2.0`

I get the following output:
```
    Executing commands in this order:
         mkdir -p awicm-2.0
         cd awicm-2.0
         sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
         sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.04p1/CMakeLists.txt
         cd oasis
         rm -rf build CMakeCache.txt include lib/libpsmile.a lib/libscrip.a lib/libmct.a lib/libmpeu.a
         cd ..
         rm ./lib/libpsmile.a
         rm ./lib/libmct.a
         rm ./lib/libmpeu.a
         rm ./lib/libscrip.a
         cd echam-6.3.04p1
         rm -rf build CMakeCache.txt
         cd ..
         rm ./bin/echam6
         cd fesom-2.0
         rm -rf build CMakeCache.txt
         cd ..
         rm ./bin/fesom.x
         cd oasis
         mkdir -p build; cd build; cmake ..;   make -j `nproc --all`
         cd ..
         mkdir -p ./lib
         cp oasis/build/lib/psmile/libpsmile.a ./lib
         cp oasis/build/lib/psmile/mct/libmct.a ./lib
         cp oasis/build/lib/psmile/mct/mpeu/libmpeu.a ./lib
         cp oasis/build/lib/psmile/scrip/libscrip.a ./lib
         cd echam-6.3.04p1
         mkdir -p build; cd build; cmake ..;   make install -j `nproc --all`
         cd ..
         mkdir -p ./bin
         cp echam-6.3.04p1/src/echam/bin/echam6 ./bin
         cd fesom-2.0
         mkdir -p build; cd build; cmake ..;   make install
         cd ..
         mkdir -p ./bin
         cp fesom-2.0/bin/fesom.x ./bin
         cd ..

Missing folder awicm-2.0/awicm-2.0 detected. Please run 'make get-awicm-2.0' first.
```

**Comment by nwieters** [comment]
This has been foxed already or will be fixed with next release.
