### ISSUE TITLE
Restart of AWI-CM1 is needed in Levante (should not be needed)

### ISSUE THREAD

**Issue by antoniofis10000** [esm-tools/esm_tools#881]
Dear all.
I am running several new AWI-CM1 experiments in Levante. 
However once a chunk is completed (I need several 6 months chunks), the following one does not start properly (the run folder or prepcomputed and runscripts logs are generated but not the compute log).
Nevertheless, if I manually restart the experiment it runs properly.
Should be some issue related to Levante or am I doing something wrong?

Thanks in advance.
Best wishes,
Antonio.

**Comment by antoniofis10000** [comment]
Some paths are:
/work/ba1264/a270148/esm-experiments/AWICM/PD_T127e1E1
/work/ba1264/a270148/esm-experiments/AWICM/PD_T127e1E3
/work/ba1264/a270148/esm-experiments/AWICM/PD_T127e1E5
/work/ba1264/a270148/esm-experiments/AWICM/PD_f1979_n1979_T127e1_E1

**Comment by chrisdane** [comment]
Duplicate of #872. 
Update your esm_tools and it should work.

**Comment by antoniofis10000** [comment]
Thanks @chrisdane, and sorry for the duplicate.
It works.
