### ISSUE TITLE
automatic generation of correct namcouple file

### ISSUE THREAD

**Issue by tsemmler05** [esm-tools/esm_tools#893]
To get the correct namcouple file, I had to manually edit it in the work directory since I couldn't find the origin of it in config/finished_config.yaml.

For my new HR-TCO95 set-up the esm tools generated a namcouple with CORE2 as ocean resolution instead of HR and I therefore had to edit the namcouple manually. 

I am running on aleph with esm_tools version 6.19.3 and the run script is here:

/proj/awiiccp5/awicm3-frontiers-xios-aleph-TCO95L91-HR_generateweights.yaml

The work directory where I manually edited the namcouple file is here:

/scratch/awiiccp5/hr95_2/run_18500101-18500101/work

**Comment by mandresm** [comment]
Hi @tsemmler05,

By looking into your runscript I see that `fesom.resolution` is commented out. Many of the automatic configurations of AWICM3 and FESOM depend on that variable which is set by default to `CORE2` therefore, it's normal that that's not working. I would try with that:

```yaml
fesom:
    resolution: HR
```

Please, let me know if that works and apologies for the late reply, somehow this issue got overlooked...

**Comment by nwieters** [comment]
I will close this issue since the solution given by @mandresm works. I also tested it, and with
```
fesom:
    resolution: HR
```
I get a different namcouple than with `CORE2`.
