### ISSUE TITLE
Do not understand the content of scripts/$EXPID_chunk_date

### ISSUE THREAD

**Issue by crodehacke** [esm-tools/esm_tools#899]
**Request/contribution description**
I do not understand what is the meaning of the three entries in `$expid/scripts/$expid_chunk_date`.
In addition, is the meaning of _chunk_ identical to _phase_ in the documentation?

**Suggested chapter/section in the documents**
I should be included in a chapter allowing me to restart from an earlier state -- not branching.

**Is this specific to any model/couple setup or to any ESM-Tools functionality?**
I do not think so.

**Contribution**
n/a

**Comment by mandresm** [comment]
Hi @crodehacke,

Apologies for the confusing documentation in the workflow part. It's time to fix that!

> I do not understand what is the meaning of the three entries in $expid/scripts/$expid_chunk_date.
In addition, is the meaning of chunk identical to phase in the documentation?

Can you point me at the lines in the documentation? I do not understand those entries either...

I was not aware that we use the term "phase" in the documentation, we should delete that. Can you let me know where it is used? About the chunks (or workflow chunks, I'll add this to the documentation):

In ESM-Tools we define **runs** or **legs** as the parts in which a simulation of a standalone component (e.g. FESOM) or an online-coupled system (e.g. AWI-ESM-2.1) is divided into, to be individually submitted to the job scheduler (e.g. slurm job). Variables such as `start_date`, `end_date` and `prev_date` refer to runs, while `initial_date` and `final_date` refer to the whole simulation time-span.

Chunk instead is a concept that in ESM-Tools belongs to offline coupled models: a chunk is a contiguous set of runs of one of the offline coupled components (e.g. AWI-ESM-2.1 or PISM) in which there is no communication with the other offline-coupled component. Offline-coupled communication in between offline-coupled components occurs at the end of the chunks. Variables such as `chunk_start_date` and `chunk_end_date` are handy, for example, to be given as an input to the coupling scripts.

>  I should be included in a chapter allowing me to restart from an earlier state -- not branching.
Agreed, this chapter is missing in the `Cookbook`. We will add it.

**Comment by crodehacke** [comment]
Dear @mandresm (Miguel) thanks for taking care. I'm also totally aware that a _complete_ documentation could be hardly archived.

Regarding the use of the terms
- **chunk** please go to step nine (9) at https://esm-tools.readthedocs.io/en/latest/ten_steps.html?highlight=chunk#ten-steps-to-a-running-model
- **phase** found at https://esm-tools.readthedocs.io/en/latest/esm_runscripts.html?highlight=phase#running-only-part-of-a-job and https://esm-tools.readthedocs.io/en/latest/yaml.html?highlight=phase#file-dictionary-types

**Comment by crodehacke** [comment]
I wanted to know if I want to _restart_ from an already computed state.
For instance, We started at `start_date = 1900-01-01` and have reached the `date = 1910-01-01`, but want to restart again from `1905-01-01`. I guess I have to modify in this case the content of `scripts/$expid_$model.date`. For my example, it should be 
`1905-01-01_00:00:00 5`.

What shall be the content of `$expid_chunk_date`?

**Comment by mandresm** [comment]
> I wanted to know if I want to _restart_ from an already computed state.
> For instance, We started at `start_date = 1900-01-01` and have reached the `date = 1910-01-01`, but want to restart again from `1905-01-01`. I guess I have to modify in this case the content of `scripts/$expid_$model.date`. For my example, it should be
> `1905-01-01_00:00:00 5`.

This is a simulation for yearly runs correct? In that case, what you are suggesting is the way of doing it (we have a ticket in our project management system to simplify things here). I would also suggest that you remove or rename the `run_` folders corresponding to later years.

> What shall be the content of $expid_chunk_date?

This file tells ESM-Tools which of the offline-coupled components (PISM or AWIESM) is currently run and the current chunk number of that component. The values you should give to this file will depend on whether you want to restart with AWIESM or with PISM and in which chunk. So let's say for AWIESM you have chunks of 2 years and you want to restart the simulation in year 1905 for AWIESM (with yearly restarts), then your file should look like:

`$expid_$model.date`:
```
1905-01-01_00:00:00 5
```

`$expid_chunk_date`:
```
3 awiesm first
```

One final note, although I think the information about `$expid_chunk_date` I'm giving here is accurate, I'm not super familiar with this part of the code. If it doesn't work correctly for you right away don't hesitate to write here, providing the path to your experiment, and I'll do a deep dive into the code. As you know we want to rework the workflow manager and this is a good oportunity for us to learn what needs to be improved, so please also let us know about the problems/annoyances you find on the way :)
