### ISSUE TITLE
add environment for new machine

### ISSUE THREAD

**Issue by tsemmler05** [esm-tools/esm_tools#936]
I am trying to install AWI-CM 3.1 on hpc-login, the new ECMWF HPC Atos. I do have the compiler flags and modules to be loaded from EC-Earth 4. 

Therefore, I added a new config file under esm_tools/configs/machines/hpc-login.yaml

I also added under model_codes/awicm3-v3.1/oasis/env the hpc-login/shell file with the modules to be loaded.

In addition, I edited model_codes/awicm3-v3.1/oasis/env.sh to include the hpc-login machine (which is ac6-10?.bullx):

elif [[ $LOGINHOST =~ ^ac?+-10[0-9]+\.bullx\.ecmwf\.int$ ]]; then
    STRATEGY="hpc-login"

However, the esm scripts seem to ignore this. 

When I perform:

esm_master comp-oasis3mct-4.0-awicm-3.1, I get the following error message (I can't tell you the esm tools version: "esm_versions check" just gives me "command not found"):

(esm_tools) [duts@ac6-102 awicm3-v3.1]$ esm_master comp-oasis3mct-4.0-awicm-3.1
WARNING:root:The yaml file for this computer (ac6-102.bullx) could not be determined!
WARNING:root:Continuing with generic settings...
    Executing commands in this order:
         cd oasis
         mkdir -p build; cd build; cmake ..;   make -j 1; mkdir -p ../include/; cp lib/psmile/libpsmile.a lib/psmile/mct/libmct.a lib/psmile/mct/mpeu/libmpeu.a lib/psmile/scrip/libscrip.a ../lib; cp lib/psmile/mod_oasis*mod ../include
         cd ..
         mkdir -p oasis/lib
         cp  oasis/build/lib/psmile/libpsmile.a  oasis/lib
         cp  oasis/build/lib/psmile/mct/libmct.a  oasis/lib
         cp  oasis/build/lib/psmile/mct/mpeu/libmpeu.a  oasis/lib
         cp  oasis/build/lib/psmile/scrip/libscrip.a  oasis/lib
WARNING: "sh_interpreter" not defined in the machine yaml
Lmod has detected the following error:  The following module(s) are unknown: "something"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "something"

Also make sure that all modulefiles written in TCL start with the string #%Module

Traceback (most recent call last):
  File "/perm/duts/conda/envs/esm_tools/bin/esm_master", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_master')())
  File "/home/duts/esm_tools/src/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/home/duts/esm_tools/src/esm_master/esm_master.py", line 107, in main_flow
    user_task.execute(ignore_errors)  # env)
  File "/home/duts/esm_tools/src/esm_master/task.py", line 513, in execute
    subprocess.run(
  File "/perm/duts/conda/envs/esm_tools/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./comp-oasis3mct-4.0-awicm-3.1_script.sh']' returned non-zero exit status 1.

**Comment by mandresm** [comment]
Hi @tsemmler05,

A few things:

1. Could you please commit/push your branch so that I can see what might be going on?

2. > I also added under model_codes/awicm3-v3.1/oasis/env the hpc-login/shell file with the modules to be loaded.
    >
    > In addition, I edited model_codes/awicm3-v3.1/oasis/env.sh to include the hpc-login machine (which is ac6-10?.bullx):
    >
    >elif [[
    >]]; then
    >STRATEGY="hpc-login"
    
    This is not the way you supposed to prepare environments in ESM-Tools. For a detailed description on how to do that, here is the documentation: https://esm-tools.readthedocs.io/en/latest/esm_environment.html

    Part of the environment variables you might want to write them in the `hpc-login.yaml`, most of them you probably want them in `oifs.env.yaml`, under the corresponding `choose_` block.
    
3. > I can't tell you the esm tools version: "esm_versions check" just gives me "command not found"

    It's more than a year that that is not the command for finding the version. The command is `esm_tools --versions`. If you ever have a question of what might be the options available for an ESM-Tools command you can always use the `-h` flag (`--help`) to get that information, for example `esm_tools -h`, `esm_master -h`, `esm_runscripts -h`.

4. ```
    (esm_tools) [duts@ac6-102 awicm3-v3.1]$ esm_master comp-oasis3mct-4.0-awicm-3.1
    WARNING:root:The yaml file for this computer (ac6-102.bullx) could not be determined!
    WARNING:root:Continuing with generic settings...
    ```
    
    The problem is here, it's telling you that it does not recognise the computer and therefore, instead of loading `hpc-login.yaml` it's loading `generic.yaml`. To get it to recognise this new HPC you need to include the necessary information in the `configs/machines/all_machines.yaml` files. In that file one has the same thing for Aleph as an example:
    https://github.com/esm-tools/esm_tools/blob/2c2b4d721ae28c1017083c74dacb1ea69de43dde/configs/machines/all_machines.yaml#L45-L48
    As you can see you have to specify several things:
    - The name you are giving to the computer inside ESM-Tools as the key for the dictionary. In this case the name of your computer is `hpc-login` since you said the yaml is `hpc-login.yaml`. I would recommend to change the name to something more meaningful, for example `ecmwf-atos` which would mean you would also need to rename the yaml file to `ecmwf-atos.yaml`.
    - You have to define a wildcard that identifies the nodes names for `login_nodes`, `compute_nodes` and `post_nodes` (postprocessing). You see that in Aleph postprocessing nodes and loging nodes are the same, you can do that here too. From looking at your error message it seems that the pattern of the compute nodes might be `ac*-*.bullx`. Then, you'll need to find out what are the name pattern for the login nodes.
    
    At the end the new section of the `configs/machines/all_machines.yaml` file will look something like this:
    ```yaml
    ecmwf-atos:
        login_nodes: 'ac*-*.bullx'
        compute_nodes: '<the_pattern_for_the_compute_nodes>'
        post_nodes: 'ac*-*.bullx'
    ```
    
5. Do they use SLURM? PBS? any job scheduler?

**Comment by mandresm** [comment]
Hi again,

I have updated the previous message so it's better if you have a look at the GitHub page instead of the email notification you get, to have the latest updates on that comment.

This is not a bug, but a lack of documentation. I'll keep it open for now, when we solve the problem, I'll collect all the information in this thread and add a page in the documentation on how to implement a new HPC in ESM-Tools. Then, I will move this thread to the "Discussions" forum as this is not a bug.

**Comment by tsemmler05** [comment]
Thanks for your help! I got quite a bit further now. It starts compiling oasis3mct and now just can't find mpif.h. I guess this is an include file from the mpifort library - not sure from the documentation how I can add this as a variable. 

"esm_versions check" is shown when opening a github support issue (you get described what information you should include into the github support issue). Would be good to update this. 

I can commit a branch tomorrow.

**Comment by mandresm** [comment]
You're welcome!

I think you are right, you are missing probably an environment variable or a module load. This would be the part of the documentation where it is explained: https://esm-tools.readthedocs.io/en/latest/esm_environment.html#environment-variables

You can take inspiration from the `levante.yaml`:
https://github.com/esm-tools/esm_tools/blob/7c542e887df0602c9fca80d7de5e22cfcbccccf8/configs/machines/levante.yaml#L166-L175

To make things simple you actually won't need to indent that in a `choose_` and you can get rid of the `add_`. That's basically saying "export this variables in all comp-.sh and .run scripts ran in ecmwf-atos". 

I'm not sure that the above is what you needed, I need a bit more information about the system from ecmwf to give a better advice, for example could you share with me the documentation to the system? If you could also share with me (privately, not here for security reasons) the following scripts that would be great: `hpc-login/shell` and `model_codes/awicm3-v3.1/oasis/env.sh`.

With all of that and a branch in ESM-Tools, I will be able to give you a much better support :)

> "esm_versions check" is shown when opening a github support issue (you get described what information you should include into the github support issue). Would be good to update this.

Thanks for spotting that out, I'll fix it right away.

**Comment by tsemmler05** [comment]
Got a step further now - realised that I have to use OpenMPI and not intelmpi. Now it complains about mpif-config.h - change of ecmwf-atos.yaml committed to ecmwf-atos branch.

**Comment by mandresm** [comment]
I was looking at #938 and I cannot see why it should be complaining about mpif-config.h. For simplifying our discussion, I suggest we move to #938 and we will stay there until all problems are solved. In #938, can you paste the `comp-*.sh` script of the component that is failing and also the exact error you are having? In parallel, I am trying to get access to ECMWF-atos.

**Comment by chrisdane** [comment]
Fyi the domain names of this machine can be quite different. I have to add this to my `.ssh/config` to connect to ATOS:
```
Match exec "[[ '%h' =~ ^a[a-d]-(batch|login)$|^ecs-(batch|cron|login)$|^hpc-(batch|cron|login)$|^hpc2020-(batch|cron|login)$ ]]" # supports full regex
```
Don't know if this helps.

**Comment by mandresm** [comment]
Yes, it definitely helps @chrisdane :)
