### ISSUE TITLE
Branchoff experiments with eternal run logic in OpenIFS

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#950]
Hi all

I've been trying to branch off new experiments from an existing experiment. This should work (https://github.com/esm-tools/esm_tools/pull/380) but I've have some problems. 

To explain: Experiment FOCI_GJK029 is a piControl with initial_date: 1850-01-01 and final_date: 3000-01-01. 
On 2550-01-01 I would like to branch off a 1% CO2 run which needs to take restarts from 2549-12-31 but set the initial_date of the new experiment to 1850-01-01. 
This works mostly pretty well, with the exception of the "eternal restart" in OpenIFS. The problem seems to be that it sets "pseudo_initial_date: 2540-01-01" (I've got 10-yearly restarts) but "initial_date: 1850-01-01". The "ndays" variable then gets set to "0", and OpenIFS thinks it's doing a restart at day 0, which does not work. 

This issue seems to only apply to branch off experiments where prev_run.oifs.start_date does not agree with initial_date of the new experiment. For me those are 2540-01-01 and 1850-01-01, i.e. pretty far off! 

My work-around was to specify "pseudo_initial_date: 1840-01-01" in the runscript, but then (of course) this variable never gets moved forward in time as the run continues. 

My current solution is to add an extra option to oifs.yaml as follows:
```bash
+++ b/configs/components/oifs/oifs.yaml
 +
+# There are four kinds of runs:
+# eternal_run_number=0 - Restart from another experiment.
+# eternal_run_number=1 - Start from initial conditions
+# eternal_run_number=2 - Regular restart
+# eternal_run_number=3 - Also regular restart, but we trick OpenIFS to think
+#                        the initial_date is the start_date of the previous run
+#                        i.e. OpenIFS never knows it does more than 1 restart
+#                        This avoids both a memory issue for long runs and
+#                        overflow of some calendar variables in single precision.
+#
+# When we branch off from an existing experiment, we must set ini_pseudo_initial_date
+# in the runscript to inform ESM-Tools what initial_date it should trick OpenIFS it is.
+# For example, a piControl may start from 1850 and run to 2850.
+# A historical run would then start from 2850 of the existing run, but we would set
+# start_date for the new run to be 1850 and also trick OpenIFS to think initial_date is 1849.

 # The following choose defines a pseudo_initial_date for OIFS. This allows us to trick
 # OIFS into thinking that, from leg 3, it is always running a 2nd leg, avoiding the
 # memory issues mentioned before. This is done by declaring the pseudo_initial_date
 # as the last start date.
 choose_eternal_run_number:
+        0:
+                # If we are branching off from an existing run
+                pseudo_initial_date: "${ini_pseudo_initial_date}"
+                start_ndays_source: "${prev_run.oifs.next_ndays}"
+                branchoff: true
+                preprocess_method: "
+                    ${general.esm_function_dir}/components/oifs/change_icm_date.sh
+                        ${thisrun_input_dir}/
+                        ${oifs.input_expid}
+                        ${oifs.input_expid}
+                        ${pseudo_initial_date!syear!smonth!sday}
+                        ${start_date!syear!smonth!sday}
+                        ${oifs.wam_number}
+                        ${oifs.perturb}
+                        ${oifs.nx}
+                        ${oifs.ensemble_id};
+                    ${general.esm_function_dir}/components/oifs/change_rcf_date.sh
+                        ${thisrun_restart_in_dir}/
+                        ${pseudo_initial_date!syear!smonth!sday}
+                        ${oifs.time_step}
+                        ${oifs.seconds_since_initial}
+                        ${oifs.start_ndays}
+                        ${oifs.wam};
+                    ${slice_icml}
+                    ${append_icmcl}
+                    echo 'Long OpenIFS run. Number for internal OpenIFS timekeeping: ${eternal_run_number}'"
+
         1:
+                # If this is the first leg for an experiment
                 pseudo_initial_date: "${initial_date}"
                 start_ndays_source: "${start_ndays}"
                 preprocess_method: "
@@ -1206,6 +1258,7 @@ choose_eternal_run_number:
                     ${append_icmcl}
                     echo 'Run number for internal OpenIFS timekeeping: ${eternal_run_number}'"
         2:
+                # First restart
                 pseudo_initial_date: "${prev_run.general.start_date}"
                 start_ndays_source: "${start_ndays}"
                 preprocess_method: "${general.esm_function_dir}/components/oifs/skip.sh;
@@ -1213,6 +1266,7 @@ choose_eternal_run_number:
                     ${append_icmcl}
                     echo 'Run number for internal OpenIFS timekeeping: ${eternal_run_number}'"
         "*":
+                # Any restart that is not the first
                 pseudo_initial_date: "${prev_run.general.start_date}"
                 start_ndays_source: "${prev_run.oifs.next_ndays}"
                 preprocess_method: "
@@ -1237,9 +1291,9 @@ choose_eternal_run_number:
                     ${append_icmcl}
                     echo 'Long OpenIFS run. Number for internal OpenIFS timekeeping: ${eternal_run_number}'"
                 # If this is run 1 or 2 of an experiment, lable it as branchoff
-                choose_eternal_run_number:
-                        0:
-                                branchoff: true
+                #choose_eternal_run_number:
+                #        0:
+                #                branchoff: true
```

I hope the comments sort of explain what I tried to do. The point would be to set "ini_pseudo_initial_date" in the runscript, and this would only get used if "eternal_run_number: 0" which it only is when you're branching off. For all other restarts, the "pseudo_initial_date" should be set as normal. 

If anyone, @mandresm or @JanStreffing, have a more elegant solution, then please let me know. But I could not get branch-offs working properly without something like the above. 

Cheers
Joakim

PS. My runscript is attached (.txt format as github does not accept .yaml)
[focioifs22-1pctCO2-restart-glogin.txt](https://github.com/esm-tools/esm_tools/files/11444516/focioifs22-1pctCO2-restart-glogin.txt)

**Comment by mandresm** [comment]
Hi @joakimkjellsson, this seems to me like a great solution! I'd like to do some heavy testing of it before we can put it on release but, I think it cannot be done more elegantly. The comments are also great :)

My only question is whether we can make `pseudo_initial_date:` in the 0 case to be selected automatically so that the user doesn't need to add an extra variable in the runscript, for example:

```yaml
        previous_run_length: $(( ${prev_run.general.next_date} - ${prev_run.general.current_date} ))
        pseudo_initial_date: $(( ${current_date} - ${previous_run_length}seconds ))
```

**Comment by joakimkjellsson** [comment]
Hi @mandresm 
That's a very elegant solution as well. As long as the length of each leg is the same as for the previous experiment, then there would not be any need for the ini_pseudo_initial_date. 
Yes, please test away! I did one branched off run for myself and can confirm that it worked. 

Best wishes
Joakim

**Comment by mandresm** [comment]
> As long as the length of each leg is the same as for the previous experiment, then there would not be any need for the ini_pseudo_initial_date.

But what I proposed should also deal with the problem on changing length of the leg as well right? as we are calculating exactly the lenght of the previous leg... or am I missing something?
