### ISSUE TITLE
additional flags should be a list, not string

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#976]
For the computer (https://esm-tools.readthedocs.io/en/latest/cookbook.html?highlight=computer#example) we have the option to give additional SBATCH flags. Currently, that seems to be accepting a string. In my opinion, that should be a list.

**Comment by mandresm** [comment]
It accepts both

**Comment by mandresm** [comment]
The only thing that is needed here is that the documentation includes also the case with lists
