### ISSUE TITLE
Feature request: Model compilation and source code copying becomes part of job submission

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#99]
To make sure that we can always reproduce the source code from which a specific simulation stems, it would be perfect if the esm-tools, or runscripts, would perform the following two additional tasks _before the first model year only_:

1. before copying the model executables to the simulation base dir, trigger a compilation - and quit / do not submit compute job if compilations fails
2. also copy the whole source code branch (less than 500 MB) to the simulation folder (copying is already done for the functions, so general infrastructure that can be employed for copying the model source code should already exist in the esm tools/functions)

**Comment by pgierz** [comment]
Basically we just need to run `esm_master install-<model_name>` during the very first submission, check the exit code, and continue. Sine esm_master install is anyway just a command line wrapper around a python function, planting the function at the right place should be easy.

**Comment by dbarbi** [comment]
merged
