### ISSUE TITLE
Simulation final date not respected if the run length changes

### ISSUE THREAD

**Issue by mzapponi** [esm-tools/esm_tools#993]
I am running an historical simulation from 1950 to 2014 with 10y restarts so:

general.start_date:1950-01-01
general.final_date:2015-01-01
general.nyear:10
fesom.run_length:10

but the last run goes on until the end of 2019 instead of stopping at the end of 2014.
The problem can be easily solved running the simulation until 2010-12-31 with general.nyear/fesom.run_length:10 and then restarting from there and running the last years until 2014-12-31 with general.nyear/fesom.run_length:5, as suggested by @nwieters.
But I was wondering if adding a choose to the runscript there is a way to leave the final date as 2015-01-01 and make the run length change automatic.

**Comment by mzapponi** [comment]
I didn't notice that a question on the same topic (https://github.com/esm-tools/esm_tools/discussions/985) has been opened last week and has been also answered so I can close the issue here.

**Comment by nwieters** [comment]
Changing the length `nyear` during a simulation is not possible. Please see the answer for #985.
